### ISSUE TITLE
Commons Simulator Assistance

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#100]
## 📋   Anything to add?
I am happy to help with the Commons Simulator on some specific deliverables this month.

## 🎉   Subtasks

- [x]  Call with RandomShinichi & Griff to go over CV cadCAD model & forming standard practice
- [x]  Call outs to cadCAD community for simulator dev help
- [x]  Potential AMA on CV model & commons simulator 
- [x]  Include Commons Simulator in digital twins article to increase visibility
- [] Conversation with Z re: BSci retainer for CS Simulator completion 

## 🤼‍♂️   Reviewer

@GriffGreen
