### ISSUE TITLE
meet EVERYONE in Berlin 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1006]
## 📋   Anything to add?
Schmoozing.... etc. 

## 🎉   Subtasks

- [x] Angela
- [x] Peter
- [x] Mortiz (Holochain)
- [x] Adam McKinty (Local Currencies)
- [x] Guil (designer from DISCO / DAOist founder)
- [x] Pekko (Game Designer/Behavioral Economics
- [x] Pat & Cem (Curve Labs)
- [x] Johnathan (cadCAD Edu)
- [x] Trent
- [x] Renzo
- [x] Julio (Circles UBI)
- [x] Beth Gnosis
- [x] Kei Gnosis/Regen

## 🤼‍♂️   Reviewer

@
