### ISSUE TITLE
Managing Commons Simulator Syncs and Praise for October

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#101]
## 🎉   Subtasks

- [x] Calculate Pay for previous sprint
- [x] Tuesday Sync Call 1
- [x] Praise for 1st Call
- [ ] Make Giveth payments for work
- [x] Praise for work done that week
- [ ] Tuesday Sync Call 2
- [ ] Praise for 2nd Call
- [ ] Praise for work done that week

## 🤼‍♂️   Reviewer

@markoprljic 

## 🔗   Work doc - inspirational links
[https://docs.google.com/spreadsheets/d/1EWD2KUzq3rB1AUClWdAvLJ8xGJnI7GKrg-zrte6pI2k/edit#gid=0](url)
