### ISSUE TITLE
Distribute Regen AMA Recording

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#1011]
## 🎉   Subtasks

- [x] @krisjpi upload to YouTube (start new playlist for partners/partnerships)
- [ ] Ekene Time code topics of discussion on YouTube
- [x] Tweet recording
- [x] Post Tweet in Discord

## 🤼‍♂️   Reviewer

@krisjpi

**Comment by Ekeneodigwe** [comment]
Regen - Commons Stack AMA recording was posted on 
Twitter - https://twitter.com/commonsstack/status/1440249115791691781
LinkedIn - https://www.linkedin.com/posts/the-commons-stack_commonsstack-regen-community-activity-6846034041804750849-UPyU
& Discord
