### ISSUE TITLE
Give Lightning Talk at Doge Disco World Peace Day Event & Distribute Recording

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#1014]
## 🎉   Subtasks

- [x] Jess write Tweet promoting
- [x] Jess & Griff give talks
- [ ] Jess track down recording and pass to @Ekeneodigwe 
- [ ] Ekene write/Tweet & post in Discord

## 🤼‍♂️   Reviewer

@krisjpi
