### ISSUE TITLE
Miami Crypto Experience - CS NFT Auction

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#1016]
## 🎉   Subtasks

- [x] Write one pager / description of CS & event
- [x] Solicit art for NFT mint
- [x] Prepare submission & send to Miami mint team
- [x] Attend event
- [x] Auction & follow ups

## 🤼‍♂️   Reviewer

@GriffGreen @tamarandom

**Comment by GriffGreen** [comment]
WOOOHOOO!!! :-D Who will be our partner in this? Doingud? Project Ark?

**Comment by jessicazartler** [comment]
[Uploading Miami Crypto Exp Impact Track Deck.pdf…]

**Comment by jessicazartler** [comment]
https://docs.google.com/document/d/1eXIA121npjBENgzpYZ7BBdS8ShsfwKvbnCbqqEWOks8/edit

**Comment by jessicazartler** [comment]
@GriffGreen Miami has its own Metaverse https://3dnftworld.com/ - enter any email and es360 as the ticket code -
their NFT team will be minting for us - here is a preview of one art piece - the final will be animated and working with the artist to choose a 2nd piece as looks like we will have two spots:

![image](https://user-images.githubusercontent.com/43972522/137969719-0faa399e-f388-4c39-bbee-92890e6eca61.png)

The structure we have with the Miami event team is 10% goes to event operations / artist then chooses how much % to donate - 50-90% -- if you can Telegram me the ETH address we want to receive the funds for CS

**Comment by jessicazartler** [comment]
Here is the page where the CS NFTs were minted https://opensea.io/MiamiCryptoExperience?fbclid=IwAR3dRcq8clirXg6KrXYzHXuH3gtgrt7zbo1fh4VQZXvJVA4Oejt-IUdVhKk&search[sortBy]=LAST_SALE_PRICE&search[sortAscending]=false
As mentioned, we didn't sell them but I am working with Jon/Mihai of ImpactNFT Alliance to burn and remint for potentially another auction - they have two events coming up - one online and Miami Decentralcon https://www.dcentralcon.com/
they are attending
or sell from this page as they are already minted.. will keep you posted here

**Comment by jessicazartler** [comment]
We did not sell the NFTs at this event, awaiting info on if we can sell them at another event in Miami first week in December at Art Basil

**Comment by jessicazartler** [comment]
Follow up call with Jon with ImpactNFT Alliance scheduled for tomorrow

**Comment by jessicazartler** [comment]
Still communicating with Jon to see if there are any follow up events we could sell these at since they were not successful at Miami... Jon did not remint for Art Basil as they were too busy... so we just have these awesome works that we could do something with... due for a follow with DoinGood (NFT platform) and still talking with Jon about our Stamets projects so will keep poking and see if there is an opportunity but going to close this for now. It was an experiment still waiting for its time... To be continued... maybe we could use it for an update on the Commons Simulator or engage with this artist for that? @GriffGreen if you ever need an artist/designer for simulator/other stuff like this he'd be great...
