### ISSUE TITLE
CCA calls regular TODOs - September

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#102]
## 📋   Anything to add?

(Make September for 8th and 9th calls (and maybe 10th if it's in September?))

## 🎉   Subtasks

- [x]  Make Video link and description for 8th call on (insert date) - Julio
- [x]  Promote Call on 8th call Via Tweet - Gus
- [x]  Connect with the 8th call attendees Via Telegram - Griff
- [x]  Do the 8th Call - Griff & Julio
- [x]  Add any links to the description - Julio
- [ ]  Tweet the 8th video again with Commons Stack - Kris
- [ ]  Make Video link and description for 9th call on (insert date) - Julio
- [ ]  Promote Call on 9th call Via Tweet - Gus
- [ ]  Connect with the 9th call attendees Via Telegram - Griff
- [ ]  Do the 9th Call - Griff & Julio
- [ ]  Add any links to the description - Julio
- [ ]  Tweet the 9th video again with Commons Stack - Kris

## 🤼‍♂️   Reviewer

@Kisgus

**Comment by GriffGreen** [comment]
@krrisis did we tweet this?

**Comment by krrisis** [comment]
no. proposal to change the steps to 'Tweet the 8th video again with image preview by cca' (rt by Commons Stack), that would make more sense, as it is CCA content, so no reason to put that work on the CS side.
