### ISSUE TITLE
Creating a report in Google Data Studio for the Trusted Seed Dashboard in Notion

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1023]
## 📋   Anything to add?
Important Trusted Seed members’ KPI to track and view on a simple Google Data Studio dashboard.

## 🎉   Subtasks

- [x] Some research time.
- [x] Data validation for setting up the information that will be pulled into the report.
- [x] Creating an automated reporting dashboard with important data to track.
- [x] Embedding the report in Notion

## 🤼‍♂️   Reviewer

@knobsdao 

## 🔗   Work doc - inspirational links

https://datastudio.google.com/reporting/3b416db0-999c-4fca-98e7-d9f78c99c5e2
