### ISSUE TITLE
Managing the TE Commons Roadmap Progress - October

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#103]
## 📋   Anything to add?

Every week before the call, I will update the TEC roadmap so that i can flash it in front of everyone and it is up to date.

## 🎉   Subtasks

THIS NEEDS TO BE UPDATED

- [ ] Update Roadmap to integrate feedback on Wednesday the 2nd
- [ ] Prepare for Thursday, 3rd, call
- [x] Post Agenda for call
- [x] Promote Thursday, 3rd, call
- [ ] Have Thursday, 3rd, call / Show roadmap on the call
- [x] Roles process defined and TEC Community Stewards established
- [ ] Update Roadmap to integrate feedback on Wednesday the 9th
- [x] Prepare for Thursday, 10th, call
- [x] Promote Thursday, 10th, call
- [x] Have Thursday, 10th, call / Show roadmap on the call
- [x] Working groups topics and members identified
- [x] Update Roadmap to integrate feedback on Wednesday the 17th
- [x] Prepare for Thursday, 17th, call
- [x] Post Agenda for call
- [x] Promote Thursday, 17th, call
- [x] Have Thursday, 17th - Working groups sync
 -[ ] List here what we need to get feedback on for next week
- [x] Outline what are the next steps for the upcoming week
- [x] Update Roadmap to integrate feedback on Wednesday the 23rd
- [x] Prepare for Thursday, 24th, call
- [x] Post Agenda for call
- [x] Promote Thursday, 24th, call
- [ ] Have Thursday, 24th, call / Show roadmap on the call
- [x] Working groups proposals delivered
- [ ] List here what we need to get feedback on for next week
- [ ] Outline what are the next steps for the upcoming week
- [ ] Update Roadmap to integrate feedback on Wednesday the 30th
- [ ] Role Proposal

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1ouFisWOfJgqi7nQODvXQqNg0T49jmZGZalPFvpB121c/edit?usp=sharing
