### ISSUE TITLE
Review/Improve Notion for CS

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1031]
## 🎉   Subtasks

- [ ] Check current pages
- [ ] Feedback from teams 
- [ ] Improvements around circles 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/45

Moved to Trusted Seed Sprint Board.
