### ISSUE TITLE
Keep Pushing the Param Parties

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#1036]
## 🎉   Subtasks

- [x] Do QA on the Commons Config Dashboard to a good place 
- [x] Get the Thumbs up on releasing the CCD out to the Community
- [x] Schedule a bunch of Params parties
- [ ] Do the ones in this sprint

## 🤼‍♂️   Reviewer

@marthendalnunes

**Comment by GriffGreen** [comment]
Got config.tecommons.org to work!!
