### ISSUE TITLE
Update Budget for September

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#104]
## 📋   Anything to add?

This is done for Early August... its very much a bureaucratic milestone where Griff needs to update a few different spreadsheet and pay people for their monthly milestones

## 🎉   Subtasks

- [x] Update this month's Donations tab in the Iteration 0 Budget Spreadsheet
- [ ] Update this month's Projections tab in the Iteration 0 Budget Spreadsheet
- [x] Update this month's Holdings tab in the Iteration 0 Budget Spreadsheet
- [x] Catherd Commons Stack Core team to put in monthly milestones 
- [ ] Payout Monthly Milestones 

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links
https://docs.google.com/spreadsheets/d/1DdwfoA7u6U2hnfgmJzT5adWExnorutxKSRh_L_-u_5Y/edit#gid=1546169124
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e
