### ISSUE TITLE
Find, hire and do specification with frontend dev

### ISSUE THREAD

**Issue by Kisgus** [commons-stack/iteration0#106]
## 🎉   Subtasks

- [ ] Marko and Griff iterates with studio and devs
- [ ] Agree on a dev and starting time
- [ ] Have an initial specification call to agree on spec and timeline

## 🤼‍♂️   Reviewer

@Kisgus
