### ISSUE TITLE
ABC article, the What

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1063]
## 🎉   Subtasks

- [ ] Make a bullet point article with technical pieces
- [ ] Help get graphics for it.
- [ ] Confirm the plan by end of sprint

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Looping in @usama9500 for this issue...

**Comment by tamarandom** [comment]
@usama9500 will lead and get @GriffGreen to do reviews....
