### ISSUE TITLE
TS Project Showcase call

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1067]
## 📋   Anything to add?
Use one or more office hours calls in Dec to have members showcase current projects, ask for help, or just share possible collaborations within the community (?)

Maybe add the open call to [#1066](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/1066)
## 🎉   Subtasks

- [x] Idea to reality
- [x] 30 min... 1-2 showcases (?) Open Call
- [x] Dates 
- [x] Distribution
- [x] Big day(s)

## 🤼‍♂️   Reviewer

@

**Comment by mafer-labs** [comment]
Dates: Dec 7-14
2 speakers, moderation, 30-45 min

**Comment by mafer-cordovas** [comment]
Here's a draft for the flyer that can be used for the open call. I will be presenting it at the Comms call.

![Members' Spotlight (1).png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/f8b8dc2c-0982-4ecf-8cd9-e6c9fee806cd)

**Comment by mafer-labs** [comment]
![Members' Spotlight (3).png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/3906221a-3f70-47e7-a130-2e17042805cd)

**Comment by mafer-labs** [comment]
New date added 🥳 Dec 21

**Comment by mafer-labs** [comment]
At the end we had Dec 7th - Dec 14th.

Participants:
Mettodo - NJombe Innovation Academy & Greens for Good
Innov8tor3 - PrinterNet Africa

@iviangita suggested for the next year to have Members' Spotlights every sprint (Bi-weekly). Leave the space open so members can ask to showcase anytime. That's why I'm changing this issue's name to officially Members' Spotlight call 🥳

**Comment by GriffGreen** [comment]
will happen at the end of the sprint

**Comment by mafer-labs** [comment]
- [x] create a typeform to receive the interested proposals

**Comment by mafer-labs** [comment]
https://the-commons-stack.typeform.com/to/aRMforVA

**Comment by mafer-labs** [comment]
New date for this call is the last Wednesday of each month.

**Comment by tamarandom** [comment]
Next will be on Jan 26!

**Comment by mafer-labs** [comment]
Jan 26 we have Chris Cypher with DropList
- https://twitter.com/DropList_eth 
- https://mirror.xyz/droplist.eth/YD7rh__n4__XAljW40FKDf64QLCi0M1pFu3LF_4Bob4

**Comment by mafer-labs** [comment]
Feb 23 we have Pythagorean (also Chris) with web3:4Life

![image.png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/1d1cd025-96ca-4e74-9626-1a204b7c3d62)

![image.png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/1ab8fa7a-30d3-4a0d-8cea-d90acdc6b27e)


![image.png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/5a3dbcac-a2f8-4f6d-b6c2-1dfb46504294)

- https://web34life.com/
- https://twitter.com/web3_4Life

**Comment by mafer-labs** [comment]
February 23 speaker was Pythagorean with Web3:4life guild. Amazing job, also very fun to hang out with him.
Video: https://www.youtube.com/watch?v=o6ibmHIN8cg

**Comment by tamarandom** [comment]
Update: showcase this week Mercedes Rodriguez!

**Comment by usama9500** [comment]
Moving to Trusted Seed Repo:
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/42

**Comment by usama9500** [comment]
Closing this issue.
