### ISSUE TITLE
Implementing "Acknowledging & Rewarding Contributions to the TE Commons" proposal 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#108]
## 🎉   Subtasks

- [ ] Define a boundary process for how praise gets rewarded on September 2nd
- [ ] Share proposal on TEC discord for feedback
- [ ] set calendar work sessions to reward contributors every 2 weeks (or use part of the cultural build hacks every 2 weeks)
- [ ] document rewards in the form of a newsletter 
- [ ] create a medium account for the TEC
- [ ] Keep records of funds possibly received by Gitcoin and Aragon proposal and who is benefiting from them to subtract from the praise cred

## 🤼‍♂️   Reviewer

@GriffGreen
