### ISSUE TITLE
Spreadsheets Improvement and Data Management

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1089]
## 📋   Anything to add?

Our main spreadsheet that contains all applicants data needs improvements to keep the data clean and tractable ASAP.

## 🎉   Subtasks

- [ ] Analyze data connection
- [ ] Designing a more user friendly data management/maintenance process
- [ ] Desirable: Finding a workaround to automate data management if possible
## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1P13b4vM6ppTr3T_wGz1WorVQ-SQCuUQF4V7jLAqpoEk/edit?usp=sharing

**Comment by YineisyM** [comment]
@mafer-cordovas here's the issue to start with this task.

@GriffGreen would you be the reviewer?

**Comment by mafer-labs** [comment]
Awesome

**Comment by tamarandom** [comment]
Moved to Trusted Seed Dashboard. 🌱 
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/40
