### ISSUE TITLE
TEC and CS Community Management 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#109]
## 🎉   Subtasks
CS
- [x] Welcome people on CS main channel
- [x] Answer questions or ping who can answer
- [x] engage in conversations
- [ ] connect people or lead them to relevant resources when possible 
- [x] dish praise

TEC
- [x] Post reminder for the calls 
- [x] be an active member and make sure all comments/ questions are addressed 
- [x] monitor the voting channel so all proposals are posted in the poll by Friday afternoon
- [x] Release voting results and update the decision making 
- [x] dish praise

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
[voting spreadsheet](https://docs.google.com/spreadsheets/d/12_PK_G9-gGxPOm-mdl5dlfdh9GSZGuI5gkTLkWlfNcY/edit#gid=0)
