### ISSUE TITLE
Gitcoin Grants Round 12 - Dec 1st to Dec 16th

### ISSUE THREAD

**Issue by phacker3** [commons-stack/iteration0#1104]
## 📋  LINKS & RESOURCES:
Important Links:
- [Gitcoin Promotion Templates & Timelines](https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit)
- [Ecosystem & Partnerships](https://www.notion.so/giveth/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09) Notion page (might be mostly old content)
- "[The CS Community Fund is Back for GitCoin Grants Round XX](https://medium.com/commonsstack/the-commons-stack-community-fund-is-back-for-gitcoin-grants-round-10-b82be441aed1)" on Medium
- "[The CS Community Fund is Back](https://medium.com/commonsstack/commons-stack-community-fund-voting-round-3-dedc0f98d495)" on Medium ARCHIVE
- [Conviction Voting Walk-Through](https://www.youtube.com/watch?v=kHrI7hHJicQ) on YouTube
- [GitCoin Grant Thank You Template](https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit#)

## 📆  IMPORTANT DATES:
Nov 24th: Kick-off pre-round tasks for GitCoin Grants & Community Fund
Dec 1st: GitCoin Round 12 starts
Dec 1st: CS Community fund voting starts
Dec 12th: Community fund voting ends
Dec 16th: GitCoin round ends, post-round tasks start

FOCUS: Coordinating GitCoin grant submission and CS community fund voting for entire CS/ecosystem! woooo!

## 🎉   SUBTASKS

**Pre-round tasks**
Nov 24th
- [x] review & update list of CS Ecosystem grants (see below) @phacker3 
- ask via discord if anyone has a grant to add to the collection
- [x] Discord message to GitCoin grant owners: "FYI update your grants & links" @phacker3 
- [x] Re-open the CS Conviction Voting dApp https://cv.commonsstack.org/ @GriffGreen 
- [x] Plan comms strategy in [CS GitCoin Promo Templates & Timelines](https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit) @Ekeneodigwe 
- [x] Update "CV Walkthrough" video @krisjpi 
- [x] Update "The CS CF is Back for Gitcoin Grants Round XX" Medium post & update link on community fund DAPP @Ivy
- [x] Prepare CS newsletter for kick-off send: Announce GC & CF vote (Grants are live! Do you know where your CSTK is? activate membership & update info so you can vote!) @YineisyM
- [x] Schedule Twitter space to help with CSTK & CV voting issues @Ekeneodigwe
- [x] Curate "Commons Stack Collection" of GitCoin Grants to promote in newsletter & Twitter @phacker3 

**Round starts**
Dec 1st
- [x] grants go live
- [x] GC Round Kick-off tweet thread @Ekeneodigwe 
- [x] Comms strategy running @Ekeneodigwe 
- [ ] Engage with grants & donations (Like / Comment?) @everyone
- [ ] Update Commons Stack GitCoin Grant Thank You before round ends @krisjpi 

**COMMUNITY FUND VOTING END**
Dec 12th
- [x] close CS CV dApp @GriffGreen @krisjpi 
- [x] Record CS CV voting results via screenshot & make graphic @ivy
- [x] Tweet CF voting results w/ final push for donating to the GCG in $PAN @Ekeneodigwe 

**Round ends**
Dec 16th
- [ ] Collect $PAN from Community Fund GCG and do some magic to prepare the distribution @GriffGreen 
- [x] Promote "thank you from the CS ecosystem!" @Ekeneodigwe
- [x] Newsletter: GC thank you & CF voting donation results @YineisyM 
- [x] Tell grant owners via discord to thank their donors (use GitCoin Grant Thank You Template) @phacker3 

**CS Ecosystem Grants & owners**
- [x] [Commons Stack Community Fund - Panvala League](https://gitcoin.co/grants/1127/commons-stack-community-fund-panvala-league) (KRIS)
- [x] [Commons Stack Iteration 0](https://gitcoin.co/grants/539/the-commons-stack-iteration-0) (GRIFF/JESS)
- [x] [Token Engineering Commons](https://gitcoin.co/grants/1155/token-engineering-commons) (CHUY/GRIFF)
- [x] [Commons Simulator](https://gitcoin.co/grants/277/commons-simulator-modeling-sustainable-funding-for) (GRIFF/LAUREN)
- [x] [Giveth](https://gitcoin.co/grants/795/giveth-20) (MITCH Divine-comedian/GRIFF)
- [x] [cadCAD](https://gitcoin.co/grants/308/cadcad-computer-aided-design-for-complex-systems) (JEFF/JESS)
- [x] [Conviction Voting cadCAD Model Improvements: 1Hive Luna Swarm 🐝](https://gitcoin.co/grants/1141/conviction-voting-cadcad-model-feature-improvemen) (JEFF)
- [x] [Crypto Commons Gathering](https://gitcoin.co/grants/2073/crypto-commons-gathering-2021) (JEFF)
- [x] [TE Academy](https://gitcoin.co/grants/517/tokenengineering-community) (ANGELA)
- [x] [HG2TE](https://gitcoin.co/grants/798/a-hitchhikers-guide-to-token-engineering) (SEBNEM)
- [x] [Bloom](https://gitcoin.co/grants/1595/bloom-network) (MAGENTA)
- [x] [Impact Pirates](https://gitcoin.co/grants/1638/electric-circus-proudly-presents-impact-pirates) (SEBNEM)
- [ ] LIBRARY OF GITCOIN TEMPLATES/CONTENT LIVES IN OUR CS NOTION
https://www.notion.so/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09

## 🤼‍♂️   Reviewers
@krisjpi @GriffGreen @tamarandom @jessicazartler

**Comment by Ekeneodigwe** [comment]
The Draft of 

- GC Round Kick-off tweet thread
- Comms strategy running
can be found here https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit#

**Comment by phacker3** [comment]
Awesome Ekene!

Just a reminder for a few pre-round tasks:
- Update CV video if needed @krisjpi 
- Update Medium articles @iviangita 
- Draft CS Newsletter @YineisyM 
- Update "CS Collection" @phacker3

**Comment by iviangita** [comment]
Hello @phacker3! Just wanna clarify:

["The CS Community Fund is Back for GitCoin Grants Round XX"](https://medium.com/commonsstack/the-commons-stack-community-fund-is-back-for-gitcoin-grants-round-10-b82be441aed1) on Medium
["The CS Community Fund is Back"](https://medium.com/commonsstack/commons-stack-community-fund-voting-round-3-dedc0f98d495) on Medium ARCHIVE

These 2 articles look similar - do we update both of them? Or just the article with Gitcoin in the title? :)

**Comment by phacker3** [comment]
@iviangita you can skip the "ARCHIVE" one and update the other one! then let @Ekeneodigwe and @YineisyM know when it's ready because they will probably want to link this article on twitter and the newsletter :)

**Comment by YineisyM** [comment]
We send today an email especially to start the voting.

**Comment by phacker3** [comment]
Hey all - just wanted to check in on some of these tasks since the round is already ending on Thursday (❗🤯❓). The main thing right now is confirm the CV dApp is closed (@krisjpi) and make a final push for donations in $PAN (@iviangita & @Ekeneodigwe) there are only 2 more days to donate!!

**Due ASAP**
- Update Commons Stack GitCoin Grant Thank You before round ends @krisjpi 
- Close CS CV dApp @krisjpi the dApp looks closed for me! Can you confirm?
- Record CS CV voting results via screenshot & make graphic to tweet @iviangita
- Tweet CF voting results graphic w/ final push for donating to the GCG in $PAN @Ekeneodigwe

**Comment by Ekeneodigwe** [comment]
Could we close this issue @phacker3? I am guessing we have checked out all that was listed

**Comment by GriffGreen** [comment]
I still need to send out the PAN for the Commons Stack Community Fund

**Comment by tamarandom** [comment]
The PAN distro is being tracked in #1069. Closing.
