### ISSUE TITLE
Work on Statutes

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#112]
## 🎉   Subtasks

- [ ] @lorelei1 contact Coach B (ask for: edits, set up time with lawyers, need to confirm final statutes in board mtg?)
- [ ] incorporate edits
- [ ] Have Coach B review

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1xg3mWJuubC7XpT_FbtDTriP0NzwMVQhaVDUj4PZqN1k/edit?usp=sharing

### Do this stuff later:
- [ ] Send to lawyers for review
- [ ] Sign in the changes to statutes in board meeting?

**Comment by lorelei1** [comment]
Statutes don't have many edits in them at present, but will need to be congruent with T&Cs so after those are revised, Bernd will be able to revise the Statutes.

**Comment by lorelei1** [comment]
Statutes are updated along with T&C, just waiting for final lawyer review.
