### ISSUE TITLE
Gitcoin Twitter Space - Host & Invite Panelists

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#1129]
## 📋   Anything to add?

Gitcoin Grant Twitter Spaces on Monday week, 10am EST / 4pm CET
Talking points will include but not limited to how Gitcoin rounds has contributed to incentivising Public goods, Accountability of projects under the commons Stack Ecosystem  and a guide on how to vote
The Idea of Monday is to give us three days to gather last minute votes

## 🎉   Subtasks

- [x] Invite Joe & Scott from Gitcoin
- [ ] Prepare some topics for Monday & ask Ekene how to join and how to tell panelists to join
- [ ] Do the thing! :D 

## 🤼‍♂️   Reviewer

@tamarandom @Ekeneodigwe @iviangita

**Comment by tamarandom** [comment]
Done & closing. We learned a lot from the experience.
