### ISSUE TITLE
Work on Terms and Conditions

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#113]
## 🎉   Subtasks

- [x] @GriffGreen help Loie define this task
- [x] @lorelei1 contact Coach B, plan lawyers' involvement
- [x] Make edits
- [ ] Review internally

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1lR5b9Ui8_KXzWCO276KwSS9-8_NSNFbkVvUMXPjAWdI/edit 

Stuff to do later:
- [ ] Get lawyer approval
- [ ] Sign T&C during a board meeting?
- [ ] Add final doc as a screen of the CSTK token DApp

**Comment by lorelei1** [comment]
Bernd needs 2 weeks before he can get T&C updated enough to send to a lawyer. @lorelei1 will look through the doc first and give Bernd the go-ahead when all blaringly important changes are reflected so that he can be properly informed and effective working on it this weekend!

**Comment by lorelei1** [comment]
Finished updates and sent the T&C to Coach B to start reviewing.

**Comment by lorelei1** [comment]
Content complete. Waiting for final lawyer review.
