### ISSUE TITLE
Write job description for comms lead

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#114]
## 🎉   Subtasks

- [x] Start from existing roles 
- [x] Additions & edits by @GriffGreen 
- [x] Final approval by lorelei
- [x] share in our channels & on the socials 

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by krrisis** [comment]
https://docs.google.com/document/d/1aGZyKxfSi81hPTAWCy9Ve62JsHk8RMJpFaDV3Sd1A5M/edit#

**Comment by exiledsurfer** [comment]
I am so applying for this position as soon as the job description is released publicly :-)

**Comment by krrisis** [comment]
Well I hope you're serious :)

**Comment by exiledsurfer** [comment]
Totally serious. Email is already drafted :-)

**Comment by exiledsurfer** [comment]
applied via email :-) This job description is tailor made for my talents and experience. Looking forward to an interview :-)
