### ISSUE TITLE
Get Trusted Seed members on xDai chain

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#115]
## 🎉   Subtasks

- [x] Send out How To guide: https://www.xdaichain.com/for-users/wallets/metamask/metamask-setup
- [x] Perhaps have a quick call about it?
- [x] Spam in Panvala draft channel (that's it's own channel right?)
- [x] make a final audit of token holders and applicants
- [ ] remake the Trusted Seed spreadsheet to avoid future issues

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by lorelei1** [comment]
@GriffGreen this is you! I assume many of your voters are not on xDai yet, and voting starts... when?

**Comment by lorelei1** [comment]
not blocked - in fact closed even?

**Comment by lorelei1** [comment]
Needs to be done next sprint:  make a final audit of token holders and applicants
 remake the Trusted Seed spreadsheet to avoid future issues
