### ISSUE TITLE
Make Giveth Campaigns for Iteration 1

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#117]
## 🎉   Subtasks

- [ ] cadCAD team (250k campaign) - @Jeff-Emmett will write this one
- [ ] What are the other "flip it on it's side" categories?
- [ ] TE Commons - @liviade1 with Griff review
- [ ] Iteration 1 Field Test Commons - someone write, @GriffGreen review
- [ ] ABC - @GriffGreen with Jeff
- [ ] Cultural Build (mentioned on It 1 Roadmap doc)
- [ ] Giveth (mentioned on It 1 Roadmap doc - is this a new campaign or some pre-existing Giveth development campaign?)

## 🤼‍♂️   Reviewer

@lorelei1  

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1Zd4qQT2x2CT52gniphcxm1rQLyCqPIqH5VcVXDINyvw/edit?usp=sharing

**Comment by lorelei1** [comment]
Need someone to carry flag on these... @JulietEA project manage that all of these get done?
@Jeff-Emmett will help with writing & pulling into draft form!
