### ISSUE TITLE
Do circular resolution to accept members

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#118]
## 🎉   Subtasks

- [x] Schedule the meeting (Coach B, Loie, Jeff, Griff should be there, Z and Kris invited)
- [x] During the meeting:
- [x] Accept final statutes
- [x] Accept final Terms & Conditions

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by lorelei1** [comment]
It's more like a circular resolution: it can be over chat.
