### ISSUE TITLE
Review and polish "Iteration 0 Roadmap"

### ISSUE THREAD

**Issue by Kisgus** [commons-stack/iteration0#12]
## 📋   Description

Let's define the prioritizes and timeline for launching Iteration 0 ;)

## 🎉   Definition of done

- [x]  List all the pieces of iteration 0 
- [x]  Target end dates (internal) 
- [x]  Defining the end of iteration 0 
- [x]  List of articles and updates needed on website for It 0 (sync with Kriis)
- [ ]  Agreement of these pieces
- [x]  Assignment of a deliverable for each month can be completed 1st week of August
- [ ] Propose changes and iterate with Griff + team
- [x] Implement final version in graphical roadmap tool
- [x] Update milestones / issues / Github repos accordingly

## 🤼‍♂️   Reviewer

Rest of the team

**Comment by GriffGreen** [comment]
This work is being done in the "Outline of the Roadmap Doc" 👍

**Comment by Kisgus** [comment]
https://docs.google.com/document/d/1C2HM9Lg136ArQfyqxPh3IfRnU8AJIfwwc2SQgNU1oP0/edit#
