### ISSUE TITLE
Update 3D visuals on homepage

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#120]
## 🎉   Subtasks

- [x] debrief first visual to Alan, 2 & 3 already done
- [x] feedback comms team 
- [x] Receive elementss
- [x] upload on website

## 🤼‍♂️   Reviewer
@GriffGreen

**Comment by krrisis** [comment]
Update visual 
![image](https://user-images.githubusercontent.com/6533925/92405287-8b3fdb00-f135-11ea-96e2-7d7729bf3520.png)

**Comment by krrisis** [comment]
new update 
![image](https://user-images.githubusercontent.com/6533925/93114085-6cec5900-f6ba-11ea-9f10-1eaf4aa12173.png)

**Comment by krrisis** [comment]
Live on [commonsstack.org](http://commonsstack.org)
