### ISSUE TITLE
Re-do our user journey (Urgent) Make it clear and info friendly!

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#1201]
## 📋   Anything to add?
Make the user journey as clear as possible. Currently, the activation part is not clear until way far in the process, and this might be influencing the successful applicants to not activate.
## 🎉   Subtasks

- [x] Add dues payment info to the Typeform
- [ ] Review all documentation related to the user journey
- [ ] Create an infographic to explain the whole process

## 🤼‍♂️   Reviewer

@tamarandom 

## 🔗   Work doc - inspirational links
- App form https://the-commons-stack.typeform.com/to/nG7xc1
- Process description https://medium.com/commonsstack/join-the-commons-stacks-trusted-seed-swiss-association-ed51a356cb6c

**Comment by mafer-labs** [comment]
Changes to the Typeform 1st page
 ![image.png](https://images.zenhubusercontent.com/61140368d41f1f02056e127f/2a9351b6-f5e9-4b1d-8400-1f153a6b294d)

**Comment by mafer-labs** [comment]
Open sessions in discord's Treehouse with T!b! on Thursdays. 3 sessions so far.

**Comment by usama9500** [comment]
@tamarandom is this Trusted Seed related issue or Commons Stack

**Comment by tamarandom** [comment]
Definitely Trusted Seed.

**Comment by usama9500** [comment]
Moved to Trusted Seed Board: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/112
