### ISSUE TITLE
CS tweets creation, monitoring and retweeting any relevant content

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1230]
## 🎉   Subtasks

- [ ] Monitoring mentions and retweeting any relevant content
- [ ] Posting repeating tweets for scheduled calls (TS Lounge, etc.)
- [ ] Drafting new content as assigned

## 🤼‍♂️   Reviewer

@iviangita

**Comment by tamarandom** [comment]
Updating the Sprint board. Closing this.
