### ISSUE TITLE
Gitcoin Grants Round 13 - Mar 9th to Mar 24th

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1259]
## 📋  LINKS & RESOURCES:
Important Links:
- [Gitcoin Launch blogpost](https://gitcoin.co/blog/announcing-grants-round-13/)
- [Gitcoin Promotion Templates & Timelines](https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit)
- [Ecosystem & Partnerships](https://www.notion.so/giveth/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09) Notion page (might be mostly old content)
- "[The CS Community Fund is Back for GitCoin Grants Round XX](https://medium.com/commonsstack/the-commons-stack-community-fund-is-back-for-gitcoin-grants-round-10-b82be441aed1)" on Medium  
- "[The CS Community Fund is Back](https://medium.com/commonsstack/commons-stack-community-fund-voting-round-3-dedc0f98d495)" on Medium ARCHIVE 
- [GitCoin Grant Thank You Template](https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit#)

## 📆  IMPORTANT DATES:
Mar 9th: GitCoin Round 13 starts
Mar24th: GitCoin round ends, post-round tasks start

FOCUS: Coordinating GitCoin grant submission

## 🎉   SUBTASKS

**Pre-round tasks**
March 4th
- [x] review & update list of CS Ecosystem grants (see below) @YineisyM 
- [x] Discord message to GitCoin grant owners: "FYI update your grants & links" @YineisyM 
- [ ] Plan comms strategy in [CS GitCoin Promo Templates & Timelines] @YineisyM (https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit) @YineisyM 
- [ ] Prepare CS email for kick-off send: Announce GC (Grants are live!) (Maybe????) @YineisyM
- [ ] Curate "Commons Stack Collection" of GitCoin Grants to promote

**Round starts**
March 9th
- [x] Grants go live
- [x] GC Round Kick-off tweet thread @YineisyM 
- [x] Comms strategy running @YineisyM @iviangita 
- [ ] Engage with grants & donations (Like / Comment?) 
- [x] Update Commons Stack GitCoin Grant Thank You before round ends

**Round ends**
March 24th
- [ ] Promote "thank you from the CS ecosystem!" @YineisyM 
- [ ] Newsletter: GC thank you @YineisyM 
- [ ] Tell grant owners via discord to thank their donors (use GitCoin Grant Thank You Template)

**CS Ecosystem Grants & owners**

- [x] [Commons Stack Iteration 0](https://gitcoin.co/grants/539/the-commons-stack-iteration-0) (GRIFF/JESS)
- [x] [Token Engineering Commons](https://gitcoin.co/grants/1155/token-engineering-commons) (CHUY/GRIFF)
- [x] [Commons Simulator](https://gitcoin.co/grants/277/commons-simulator-modeling-sustainable-funding-for) (GRIFF/LAUREN)
- [x] [Giveth](https://gitcoin.co/grants/795/giveth-20) (MITCH Divine-comedian/GRIFF)
- [x] [cadCAD](https://gitcoin.co/grants/308/cadcad-computer-aided-design-for-complex-systems) (JEFF/JESS)
- [x] [Conviction Voting cadCAD Model Improvements: 1Hive Luna Swarm 🐝](https://gitcoin.co/grants/1141/conviction-voting-cadcad-model-feature-improvemen) (JEFF)
- [x] [Crypto Commons Gathering](https://gitcoin.co/grants/2073/crypto-commons-gathering-2021) (JEFF)
- [x] [TE Academy](https://gitcoin.co/grants/517/tokenengineering-community) (ANGELA)
- [x] [HG2TE](https://gitcoin.co/grants/798/a-hitchhikers-guide-to-token-engineering) (SEBNEM)
- [x] [Bloom](https://gitcoin.co/grants/1595/bloom-network) (MAGENTA)
- [x] [Impact Pirates](https://gitcoin.co/grants/1638/electric-circus-proudly-presents-impact-pirates) (SEBNEM)
- [x] [Gravity DAO](https://gitcoin.co/grants/3951/gravity-conflict-management-dao) (JUANKA)
- [x] [Incubating Governauts](https://gitcoin.co/grants/2978/incubating-governauts) (JESS/ANGELA)
- [ ] LIBRARY OF GITCOIN TEMPLATES/CONTENT LIVES IN OUR CS NOTION
https://www.notion.so/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09

## 🤼‍♂️   Reviewers
@iviangita

**Comment by iviangita** [comment]
UPDATES:
1) We removed Panvala League from the previous list of grants we used to promote
2) Community Fund medium article will not need to get updated anymore
3) For Commons Simulator, do not individually promote but don’t take it down either.
4) Add Gravity DAO (Juanka) 
5) Check if Commons Stack Collection needs a refresh

**Comment by jessicazartler** [comment]
Dear @YineisyM @iviangita - I added Governauts to the list (grant is being updated) - could you please kindly include in the tweet storm content? LMK if you need anything drafted for it 🙏😁

https://gitcoin.co/grants/2978/incubating-governauts

**Comment by tamarandom** [comment]
Hey @YineisyM @iviangita - here is a template (really just a checklist) that we can use for all future rounds. Would you mind to update any process changes and improvement in the list so they carry forward to the future rounds! 

https://docs.google.com/document/d/1adbs05kkiS4YTsPryTwT5tPc-enJ3s_TejopjbH0EGU/edit#

**Comment by cranders1** [comment]
Hey gang. Seen a few tweets re: TEC GR13. The TEC grant is currently inactive and not listed on grants explorer. 
Once it is updated, it will become active and listed. I think even just a sentence saying the update is forthcoming would activate the grant.
Happy to help if needed. Cheers.

**Comment by tamarandom** [comment]
Hey @cranders1 - heck yeah! It would be amazing if you could help the TEC by making the grant active. You already have access right? We should find a way to keep repeating this in the TEC github repo though. And come up with a checklist of the actions to take before, during and after the grand. Like we are setting up for CS too.

**Comment by tamarandom** [comment]
Closing!
