### ISSUE TITLE
CS talks short clips Griff, Livia and Tam Talks

### ISSUE THREAD

**Issue by usama9500** [commons-stack/iteration0#1261]
### 🎉 Subtasks
- [x] Griff Transcription
- [x] Griff Clip 1 Edits
- [x] Griff Clip 2 Edits

- [x] Tam Transcription
- [ ] Tam Clip 1 Edits
- [ ] Tam Clip 2 Edits

- [x] Livia Transcription
- [x] Livia Clip 1  Edits
- [x] Livia Clip  2 Edits

### 🤼‍♂️ Reviewer
@iviangita

**Comment by usama9500** [comment]
https://drive.google.com/drive/folders/1c7PWc5e49xMPrpDZhqIVkZ0uRWu8CaUq?usp=sharing

**Comment by usama9500** [comment]
Done and live on Twitter!
