### ISSUE TITLE
TAKE DOWN (for now) Commons Prize Interest campaign

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1269]
## 🎉   Subtasks

- [x] Finishing the form details

- [x] Draft content explaning:
What is a Commons
Benefits of launching a Commons
What is the Commons Prize 
“If you would like to launch a Commons, please fill out this short form...."

- [x] Brainstorm the publicity campaign.

## 🤼‍♂️   Reviewer

@tamarandom @iviangita @GriffGreen 

## 🔗   Work doc - inspirational links

Commons Prize details here: https://docs.google.com/spreadsheets/d/1zskStmZUvEd4n_x6mkavjKvcdZbmLB4_GlnF_6xcXiM/edit#gid=1067474196

Partners info here: https://docs.google.com/spreadsheets/d/1t66w6CmtpPet_h12UJBbfas5dMlev98ZSFl6Xvw15-U/edit?usp=sharing

**Comment by GriffGreen** [comment]
It seems like this is ready?

https://the-commons-stack.typeform.com/commonsprize :-D

**Comment by tamarandom** [comment]
Yes!

@YineisyM drafted her ideas for promotion part and they are included in section 4 of the commons interest doc here: https://docs.google.com/document/d/1pCC1BzHQTAJpRo3p3RuWWA11VSuU4Vv36h_W1tzYDrQ/edit#

**Comment by tamarandom** [comment]
Update: to be promoted!
Also, can we export the submissions we received so far into an xls or other readable format?

**Comment by YineisyM** [comment]
Closing this issue since the Interest Campaign ended. The results are available in the issue: [Assess results of Commons Prize Phase 1#1293](https://github.com/commons-stack/iteration0/issues/1293)

**Comment by tamarandom** [comment]
Hey @YineisyM, let's take down https://the-commons-stack.typeform.com/commonsprize for the duration of the Nomination campaign. 

Once that is over, we can make an "interest form" available again but having both forms up at the same time is confusing. Thank yoU!

**Comment by YineisyM** [comment]
Hi @tamarandom! I took the interest form down for now as requested. You will now see this message: 

This typeform isn't accepting new responses

Our interest campaign for the Commons Prize is closed for now, contact usamaahmed#9991 on our [Discord server](https://discord.com/invite/KXn9Y7jzvz) if you have any questions related to your application in this form.

Are you interested in submitting a nomination for the Commons Prize? You can find all the details on how to do it [here](https://medium.com/commonsstack/announcing-the-commons-prize-d3df343c37a9).

If you want to make any changes to the message, please, let me know. Also, let me know if I can close this issue :)

**Comment by tamarandom** [comment]
Awesome, thank you!
