### ISSUE TITLE
Update existing slide deck 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#127]
## 🎉   Subtasks

- [x] Request adapted visuals from #120 for slides
- [ ] Review rest of slides
- [ ] Present to team, integrate changes & share

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by krrisis** [comment]
Deck with designs by Alan https://docs.google.com/presentation/d/1o-Nku2Cmj6svxQ-rl24Y6O4bkFi7T-RfKYrmeVtJ6Eg/edit?usp=sharing
Fundraising deck draft by Jeff & Kris

**Comment by krrisis** [comment]
All visuals available [here](https://github.com/commons-stack/commons-stack-assets/tree/master/website/visuals)
