### ISSUE TITLE
Run Gitcoin Grant Campaigns

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#129]
## 📋   Anything to add?

With this bull market, this will be a big fundraising opportunity for us and our community 

Very connected with #50 

## 🎉   Subtasks

- [x] Deploy the Commons Stack Panvala Community Grant
- [x] Make a Gitcoin Grant for TEC
- [x]  Edit Panvala Grant
- [x]  Edit It0 Grant
- [x] Deploy TEC Grant
- [x] Edit TEC grant
- [x] Edit Simulator grant
- [x] Edit Giveth Grants (Passed to Dani and Willy!)
- [x] Make a Comms plan for promoting our grants
- [ ] Execute on the Comms Plan

## 🤼‍♂️   Reviewer

@krrisis

**Comment by GriffGreen** [comment]
<img width="1408" alt="Screen Shot 2020-09-21 at 5 45 00 PM" src="https://user-images.githubusercontent.com/14945613/93789495-35d5f480-fc32-11ea-96da-3195475c1fc5.png">

**Comment by lorelei1** [comment]
#158 shows one of the "execute on comms plan" piece

**Comment by lorelei1** [comment]
@GriffGreen  Make a new issue that has the execute on week 3 & 4 elements
