### ISSUE TITLE
🏆 Commons Prize: Phase 1 (Interest signals)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1291]
## 📋   Anything to add?

For Phase 1, we want to promote the upcoming contest and also get signal for interest. 

Specifically,
- [x] Create and publish form
- [x] Promote the campaign 
- [x] Assess results (typeform data export)

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Closing phase 1! We are good and deep into phase 2 already!
