### ISSUE TITLE
How to Migrate your DAO to xDai guide

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#130]
## 🎉   Subtasks

- [ ] Add pics/make it fun for Medium
- [ ] Send to Sem again
- [ ] Publish on Commons Stack medium? Also onehive probably

## 🤼‍♂️   Reviewer

@krrisis

**Comment by lorelei1** [comment]
We decided timing wise to not publish this right near the CV medium post. Then it got deprioritized. It's a nice goal for next month but it's a public good need, not so much a Commons Stack project need and as we all know making those happen when there's higher incentive for individual needs is hard ;)
