### ISSUE TITLE
Deploy the new Praise to Commons Stack 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1309]
## 📋   Anything to add?

To prepare deploying Praise to other communities we should first deploy to our own community. While doing so, documenting each step. 

## 🎉   Subtasks

- [x]  Kickoff session with stakeholders to capture each of the steps
- [x]  Document the steps to deploy Praise to a new community 
- [x]  Coordinate the deployment to Commons Stack 

## 🤼‍♂️   Reviewer
@kristoferlund @tamarandom @liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links
https://givepraise.xyz/

**Comment by kristoferlund** [comment]
🚀

**Comment by tamarandom** [comment]
Started this miro board: https://miro.com/app/board/uXjVOzPidHY=/#

**Comment by tamarandom** [comment]
Plan is to have Step 2 and 3 finished this week. 

 ![Screen Shot 2022-06-20 at 12.09.06 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/dd446019-fb47-46da-b989-055d591ca86d)

**Comment by tamarandom** [comment]
In progress. The next step is to organize the first quant.

**Comment by tamarandom** [comment]
We're in phase 4 quantifying part.

**Comment by Rachaelmalachy** [comment]
![deployment process.PNG](https://images.zenhubusercontent.com/62737d73b2a7cf0fc03cfbd5/1d60c69c-9f95-43de-a390-b32aee0310d5)

**Comment by tamarandom** [comment]
Update: the next step is the distribution and a review of the last quantificaiton.

**Comment by tamarandom** [comment]
Closing. Rachael will track as praise lead in #1449.
