### ISSUE TITLE
September Praise Meeting

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#131]
## 🎉   Subtasks

- [x] @krrisis let us know how much/little you'll participate in this
- [x] Loie schedule it
- [x] Facilitate and make the mints afterwards

## 🤼‍♂️   Reviewer

@
