### ISSUE TITLE
Commons Prize - Phase 3 additional tasks 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1311]
## 🎉   Subtasks

- [x] List of questions for all the finalist to answer (in video format)
- [x] Prepare 2-3 "Get to know the finalist communities" sessions
- [x] Get ready! Outreach to select the winner!

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
See the top of this doc: https://docs.google.com/document/d/1IbiZGphjJ8966Am390HQ6-DY5j5fgyxYqD-tVqbQDm8/edit

**Comment by usama9500** [comment]
Done!
