### ISSUE TITLE
Coordination April AMA Degen2Regen

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1319]
## 🎉   Subtasks

- [x] Reach out the panelists
- [x] Create the tweets for the promotion
- [x] Gather community the questions.
- [x] Making sure all is set

## 🤼‍♂️   Reviewer

@iviangita @GriffGreen 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1H9QKL6s0kOdH0xOnLLPUi1kEnUUA_QGpTevCZD7Pqs4/edit?usp=sharing
