### ISSUE TITLE
CS Community Building

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#1339]
## 🎉   Subtasks - Objectives

- [ ] in 3 months we should have enough contributors to populate a pool of quantifiers for CS praise
- [ ] strengthen Commons thought leadership 
- [ ] provide engagement opportunities to the TS 

## 🤼‍♂️   Reviewer

@mafer-cordovas @YineisyM
