### ISSUE TITLE
Analyse CS praise 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#1340]
## 🎉   Subtasks

- [x] separate CS praise from the last quant in a spreadsheet (remove TEC) 
- [x] schedule a call to categorize this praise - the idea is to create a few buckets to understand the areas of contribution been praised 
- [ ] from the categories we find - discuss what areas of contributions we think are missing in CS
