### ISSUE TITLE
Hire a Full time PM

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#135]
## 📋   Anything to add?

We have so many projects to manage, we need a full-time project manager, I'm hoping Gus can help out on this a lot.

## 🎉   Subtasks

- [x] Make a job description draft (gus)
- [x] Polish the job description (Griff)
- [x] Avertise it
- [x] Review Resumes
- [ ] Griff, Jeff and Gus conduct interviews
- [ ] A decision on candidate is made

## 🤼‍♂️   Reviewer

@Kisgus 

## 🔗   Work doc - inspirational links

**Comment by Kisgus** [comment]
Heres the draft v1, please review it @GriffGreen 

https://docs.google.com/document/d/1VmNlxDtDBFBS082JNiKwVb3CXs6ZMcwfiZMB1niWRCM/edit#heading=h.ynsyth45mu2f
