### ISSUE TITLE
Uploading Nominations to Commons Prize Repo

### ISSUE THREAD

**Issue by usama9500** [commons-stack/iteration0#1351]
## 🎉   Subtasks

- [ ] Copy the information from Commons Prize Nominations Spreadsheet
- [ ] Adding nomination video to youtube playlist "Commons Prize"
- [ ] Creating issues for all the nominations that will be used for voting on Tokenlog

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
Done and live: https://github.com/commons-stack/commonsprize/issues
