### ISSUE TITLE
Upcoming conferences, apply to talk

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#1364]
## 🎉   Subtasks

- [x] Metagame Metafest2: https://metafest.metagame.wtf (June 9 - 23) 
- [X] EthBarcelona: https://doingud.typeform.com/to/hRg0iYy3 (July 6 - 8)
- [x] EthCC (Jul 19 - 21)
- [ ] EthMexicoCity (Aug 19-21)
- [ ] Devcon +EthBogota (Oct 11 - 14)

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Tracking in a personal doc. Will keep tracking through the year!
