### ISSUE TITLE
Review Guest Writer content pieces for the Newsletter

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1377]
## 🎉   Subtasks

- [ ] Monitor communications@commonsstack.org
- [ ] Review and edit (if necessary) the submitted content to adapt it for our Newsletter
- [ ] Promote the invitation to participate twice a month

## 🤼‍♂️   Reviewer

@iviangita 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1qFaQMvQm61fyCxBHM3Yb36i8R-m5QMDdalJILyz8Iag/edit?usp=sharing

**Comment by tamarandom** [comment]
Newsletter on hold! Closing this for now. We can open it again if we need it.
