### ISSUE TITLE
Make September Payment Milestones

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#138]
- [x] Livia
- [x] Gus
- [x] Kris
- [x] Loie
- [x] Jeff
- [ ] Griff
- [x] Jess
- [ ] Juliet

## 🎉   Subtasks

- [ ] Use your current roles description + info from sprint planning and describe what you'll be doing
- [ ] Show (in milestone description) your calculations on how much you are being paid
- [ ] Add a picture!
- [ ] Propose it in https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e 

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
your previous milestones :)

**Comment by liviade1** [comment]
@GriffGreen my August milestone is here, but I see it's not showing in the list of milestones, only when I click in "my milestones" 
I did it together with Loie this time and we proposed the full time value because of the sum up of the hours, but since in the beginning of the month I wasn't full time we can do like 25 hours instead of 36/40

**Comment by lorelei1** [comment]
@liviade1 a milestone won't show on the campaign's page until it's "accepted" by the campaign manager. Griff usually doesn't accept them til the end of the month (after people have made month-end updates in the milestone reflecting back). Granted I think he did actually miss seeing yours this time so you're onto something there but generally it's ok when you are only seeing it in My Milestones. Always a good idea to send him the link to it tho and remind him that it's ready to go!

**Comment by lorelei1** [comment]
There is now a template in issue #156
