### ISSUE TITLE
governance survey 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#139]
## 🎉   Subtasks

- [ ] write the questions
- [ ] send it to Griff to review
- [ ] publish in the main chat and other community chats
- [ ] schedule a call when there is a good number of responses
- [ ] write a post with the results and notes from the call
- [ ] publish in the blog? 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by liviade1** [comment]
https://miro.com/app/board/o9J_kkC0kIM=/

**Comment by lorelei1** [comment]
team take a look at miro & share ideas!
