### ISSUE TITLE
Get intro and meet with Coach B and Stefano in CHE

### ISSUE THREAD

**Issue by Kisgus** [commons-stack/iteration0#140]
## 📋   Anything to add?

I am going to CHE and wanna meet up and synch with Coach B and Stefano if possible

## 🎉   Subtasks

- [ ] Get intro to the guys from Griff
- [ ] Connect with the guys and ask about availability
- [ ] Meet if possible

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by Kisgus** [comment]
No longer relevant
