### ISSUE TITLE
Gitcoin Grants Round 14 - June 8 to June 23

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1402]
## 📋  LINKS & RESOURCES:
Important Links:
- [Gitcoin Launch blogpost](https://gitcoin.co/blog/gr14-announce/)
- [Gitcoin Promotion Templates](https://docs.google.com/document/d/1U9XmkKwzkdp9v1ktQViRuOobZerigy7-SRK2AqQPllM/edit?usp=sharing)
- [Ecosystem & Partnerships](https://www.notion.so/giveth/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09) Notion page (might be mostly old content)
- [Gitcoin Grant Thank You Template](https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit#)

## 📆  IMPORTANT DATES:
June 8th: Gitcoin Round 14 starts
June 23th: Gitcoin round ends, post-round tasks start

FOCUS: Coordinating Gitcoin grant submission

## 🎉   SUBTASKS

**Pre-round tasks**
June 2nd
- [x] review & update list of CS Ecosystem grants (see below) @YineisyM 
- [x] Discord message to Gitcoin grant owners: "FYI update your grants & links" @YineisyM 
- [x] Plan comms strategy in [CS Gitcoin Promo Templates & Timelines](https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit) @YineisyM 
- [x] Prepare CS email for kick-off send: Announce GC (Grants are live!) @YineisyM
- [x] Curate "Commons Stack Collection" of GitCoin Grants to promote @iviangita 

**Round starts**
June 8th
- [x] Grants go live
- [x] GC Round Kick-off tweet thread @YineisyM 
- [x] Comms strategy running @YineisyM @iviangita 
- [x] Engage with grants & donations (Like / Comment?) @YineisyM 
- [x] Update Commons Stack GitCoin Grant Thank You before round ends @YineisyM 

**Round ends**
June 23th
- [x] Promote "thank you from the CS ecosystem!" @YineisyM 
- [x] Newsletter: GC thank you @YineisyM 
- [x] Tell grant owners via discord to thank their donors (use GitCoin Grant Thank You Template)

**CS Ecosystem Grants & owners**

- [x] [Commons Stack Iteration 0](https://gitcoin.co/grants/539/the-commons-stack-iteration-0) (GRIFF/JESS)
- [x] [Trusted Seed](https://gitcoin.co/grants/6197/trusted-seed) (IVY/GRIFF)
- [x] [Token Engineering Commons](https://gitcoin.co/grants/1155/token-engineering-commons) (CHUY/GRIFF)
- [ ] [Commons Simulator](https://gitcoin.co/grants/277/commons-simulator-modeling-sustainable-funding-for) (GRIFF/LAUREN)
- [x] [Giveth](https://gitcoin.co/grants/795/giveth-20) (MITCH Divine-comedian/GRIFF)
- [ ] [cadCAD](https://gitcoin.co/grants/308/cadcad-computer-aided-design-for-complex-systems) (JEFF/JESS)
- [ ] [Conviction Voting cadCAD Model Improvements: 1Hive Luna Swarm 🐝](https://gitcoin.co/grants/1141/conviction-voting-cadcad-model-feature-improvemen) (JEFF)
- [x] [Crypto Commons Gathering](https://gitcoin.co/grants/2073/crypto-commons-gathering-2021) (JEFF)
- [x] [TE Academy](https://gitcoin.co/grants/517/tokenengineering-community) (ANGELA)
- [ ] [HG2TE](https://gitcoin.co/grants/798/a-hitchhikers-guide-to-token-engineering) (SEBNEM)
- [x] [Bloom](https://gitcoin.co/grants/1595/bloom-network) (MAGENTA)
- [ ] [Impact Pirates](https://gitcoin.co/grants/1638/electric-circus-proudly-presents-impact-pirates) (SEBNEM)
- [x] [Gravity DAO](https://gitcoin.co/grants/3951/gravity-conflict-management-dao) (JUANKA)
- [ ] [Incubating Governauts](https://gitcoin.co/grants/2978/incubating-governauts) (JESS/ANGELA)
- [ ] [KindOS](https://gitcoin.co/grants/5008/kindos-a-curated-ecosystem-that-recognizes-capture) (RECOMMENDED BY JEFF)
-----
- [ ] LIBRARY OF GITCOIN TEMPLATES/CONTENT LIVES IN OUR CS NOTION
https://www.notion.so/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09

## 🤼‍♂️   Reviewers
@iviangita
