### ISSUE TITLE
Praise Lead tasks

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#1449]
## 🎉   Subtasks

- [ ] Sending recurrent messages asking the community to activate and dish praise
- [ ] Open and close quantification sessions
- [ ] Selection of quantifiers
- [ ] Having the community review sessions

## 🤼‍♂️   Reviewer

@Rachaelmalachy

**Comment by tamarandom** [comment]
Hey @YineisyM - does it make sense to you to have @Rachaelmalachy start to take this on for Commons Stack.

**Comment by YineisyM** [comment]
I discussed it with @Rachaelmalachy earlier today. I agree with the decision. I will remove myself from the assignees. @tamarandom

**Comment by YineisyM** [comment]
I discussed it with @Rachaelmalachy earlier today. I agree with the decision. I will remove myself from the assignees. @tamarandom

**Comment by tamarandom** [comment]
Update: the next step is the distribution and a review of the last quantification.

**Comment by tamarandom** [comment]
Clsoing!
