### ISSUE TITLE
Score the t.me/commons Telegram Channel Room

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#146]
## 📋   Anything to add?

t.me/commons is an abandoned Telegram chat... I think we can get it... we just need to figure out how!

## 🎉   Subtasks

- [ ]  Talk to Griff about grabbing this issue
- [ ]  Join the @commons channel on telegram
- [ ]  Research how to score an abandoned TG chat
- [ ]  Tell @GriffGreen the rest of the steps and he will add it to the issue :-D 

## 🤼‍♂️   Reviewer

@GriffGreen
