### ISSUE TITLE
Gitcoin Grants Round 15

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#1487]
## 📋  LINKS & RESOURCES:
Important Links:
- [Gitcoin Launch blogpost](https://gitcoin.co/blog/gr14-announce/)
- [Gitcoin Promotion Templates](https://docs.google.com/document/d/1U9XmkKwzkdp9v1ktQViRuOobZerigy7-SRK2AqQPllM/edit?usp=sharing)
- [Ecosystem & Partnerships](https://www.notion.so/giveth/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09) Notion page (might be mostly old content)
- [Gitcoin Grant Thank You Template](https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit#)

## 📆  IMPORTANT DATES:
Sept 7th: Gitcoin Round 15 starts
Sept 22nd: Gitcoin round ends, post-round tasks start

FOCUS: Coordinating Gitcoin grant submission

## 🎉   SUBTASKS

**Pre-round tasks**
Sept 2nd
- [ ] review & update list of CS Ecosystem grants (see below) @YineisyM 
- [ ] Discord message to Gitcoin grant owners: "FYI update your grants & links" @YineisyM 
- [ ] Plan comms strategy in [CS Gitcoin Promo Templates & Timelines](https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit) @YineisyM 
- [ ] Prepare CS email for kick-off send: Announce GC (Grants are live!) @YineisyM
- [ ] Curate "Commons Stack Collection" of GitCoin Grants to promote @iviangita 

**Round starts**
Sept 7th
- [ ] Grants go live
- [ ] GC Round Kick-off tweet thread @YineisyM 
- [ ] Comms strategy running @YineisyM @iviangita 
- [ ] Engage with grants & donations (Like / Comment?) @YineisyM 
- [ ] Update Commons Stack GitCoin Grant Thank You before round ends @YineisyM 

**Round ends**
Sept 22nd
- [ ] Promote "thank you from the CS ecosystem!" @YineisyM 
- [ ] Newsletter: GC thank you @YineisyM 
- [ ] Tell grant owners via discord to thank their donors (use GitCoin Grant Thank You Template)

**CS Ecosystem Grants & owners**

- [ ] [Commons Stack Iteration 0](https://gitcoin.co/grants/539/the-commons-stack-iteration-0) (GRIFF/JESS)
- [ ] [Trusted Seed](https://gitcoin.co/grants/6197/trusted-seed) (IVY/GRIFF)
- [ ] [Token Engineering Commons](https://gitcoin.co/grants/1155/token-engineering-commons) (CHUY/GRIFF)
- [ ] [Commons Simulator](https://gitcoin.co/grants/277/commons-simulator-modeling-sustainable-funding-for) (GRIFF/LAUREN)
- [ ] [Giveth](https://gitcoin.co/grants/795/giveth-20) (MITCH Divine-comedian/GRIFF)
- [ ] [cadCAD](https://gitcoin.co/grants/308/cadcad-computer-aided-design-for-complex-systems) (JEFF/JESS)
- [ ] [Conviction Voting cadCAD Model Improvements: 1Hive Luna Swarm 🐝](https://gitcoin.co/grants/1141/conviction-voting-cadcad-model-feature-improvemen) (JEFF)
- [ ] [Crypto Commons Gathering](https://gitcoin.co/grants/2073/crypto-commons-gathering-2021) (JEFF)
- [ ] [TE Academy](https://gitcoin.co/grants/517/tokenengineering-community) (ANGELA)
- [ ] [HG2TE](https://gitcoin.co/grants/798/a-hitchhikers-guide-to-token-engineering) (SEBNEM)
- [ ] [Bloom](https://gitcoin.co/grants/1595/bloom-network) (MAGENTA)
- [ ] [Impact Pirates](https://gitcoin.co/grants/1638/electric-circus-proudly-presents-impact-pirates) (SEBNEM)
- [ ] [Gravity DAO](https://gitcoin.co/grants/3951/gravity-conflict-management-dao) (JUANKA)
- [ ] [Incubating Governauts](https://gitcoin.co/grants/2978/incubating-governauts) (JESS/ANGELA)
- [ ] [KindOS](https://gitcoin.co/grants/5008/kindos-a-curated-ecosystem-that-recognizes-capture) (RECOMMENDED BY JEFF)
-----
- [ ] LIBRARY OF GITCOIN TEMPLATES/CONTENT LIVES IN OUR CS NOTION
https://www.notion.so/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09

## 🤼‍♂️   Reviewers
@iviangita

**Comment by usama9500** [comment]
Created the content here: https://docs.google.com/document/d/1kvXXj8gZ0vJJmMkWNrAaX-r1UXsh2Hq8ufxC9P7A3Ac/edit

**Comment by usama9500** [comment]
Done: https://docs.google.com/document/d/1kvXXj8gZ0vJJmMkWNrAaX-r1UXsh2Hq8ufxC9P7A3Ac/edit. Closing the issue
