### ISSUE TITLE
Hire a Communications all rounder #2

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#149]
## 🎉   Subtasks

- [x] Kris announce
- [x] Put Job Description on twitter
- [x] Juliet does 1st check on applications
- [x] Lorelei checks applications & makes shortlist
- [x] Griff/Jeff will be interviewing people
- [x] Kris is available for an interview round with the top 3
- [ ] Kris is available for a number of handover sessions with the final candidate

## 🤼‍♂️   Reviewer

@
