### ISSUE TITLE
Communicate our move to xDai

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#150]
## 🎉   Subtasks

- [x] Announce in main channel & Trusted Seed that we have moved to xDai
- [x] Write up how to view/access your CSTK tokens now that they are on xDai (#115 is part of this)
- [x] Possibly edit the CSTK article to include this info?
- [x] https://blockscout.com/poa/xdai/address/0xc4fbE68522ba81a28879763C3eE33e08b13c499E/transactions
- [x] Possibly include an email to correspondents re: how to vote on xDai conviction voting, how to get CSTK in order to vote
- [x] Send CSTK holders some xDai to pay for gas when voting! @GriffGreen 

## 🤼‍♂️   Reviewer

@

**Comment by lorelei1** [comment]
A little How to Use Blockscout would be helpful too... To be honest I am still incredibly confused every time I try to navigate on there and have to ask @GriffGreen for help.
