### ISSUE TITLE
Proposal and Champion a Honey Airdrop to CSTK Token Holders

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#151]
## 📋   Anything to add?

1Hive uses conviction voting to allocate funds, the goal here is to champion this proposal to the Honey Token Holders 

## 🎉   Subtasks

- [ ] Find a Champion (you?)
- [ ] Write out the exact proposal (e.g. 1 honey per CSTK token holder, 2 HNY for anyone with over 1000 CSTK, 5 for anyone over 3000 CSTK this will equate to X honey)
- [ ] Pass it around the 1Hive community to see how they like it (Advice Process)
- [ ] Pass it around the Trusted Seed community to see how they like it (Advice Process)
- [ ] Propose it to the 1Hive Conviction Voting DAO
- [ ] Get out the Vote!

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://1hive.org/#/
<img width="847" alt="Screen Shot 2020-09-16 at 3 47 55 AM" src="https://user-images.githubusercontent.com/14945613/93282947-cdb98580-f7cf-11ea-802c-2e3153d9b991.png">

**Comment by jessicazartler** [comment]
@GriffGreen do we still want to try and do this? :D

**Comment by liviade1** [comment]
Should we pass this one to Chuy?

**Comment by jessicazartler** [comment]
Oh, yes! That's a GREAT idea!! This was an idea before HNY got big haha but still I think it could be cool for them to get new folks into their DAO and also the TS people... nice Livia!

**Comment by Mettodo** [comment]
Hello! I have been exploring 1hive for some weeks and this task would be a nice way to gain more experience. Does it still make sense? I guess the rewards @GriffGreen suggested should be reviewed, right?

**Comment by GriffGreen** [comment]
I will forward this issue to church and see what he thinks
