### ISSUE TITLE
Twitter Cartel AKA Public Goods Twitter Collective

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#153]
## 🎉   Subtasks

- [x] Jeff & Jess write proposal
- [x] Griff review proposal
- [x] Jeff & Jess select tool / Griff approve 
- [x] Create Telegram channel & get community 
- [x] Jeff & Jess setup tool w/ all accounts 
- [x] Collect tweet submissions, write tweets and start cross-promotion!

## 🔗   Work doc - inspirational links
(RESTRICTED ACCESS by INVITE ONLY)
https://docs.google.com/document/d/1xd0kfBhwghm2uI1Iw2ZIwDUqAcSvzrghxtJ_kQElbVc/edit

**Comment by jessicazartler** [comment]
We have setup the process and are just waiting on Luke to come back with his login -- we've started with a few Tweets related to Gitcoin grants, article distribution and will be ironing out the process in the Telegram channel as we go and will check in with @GriffGreen in how to handle moving forward.
