### ISSUE TITLE
Make the praise bot work for discord

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#154]
## 📋   Anything to add?

The crypto crews are all on discord these days.. would be great to get the praise bot working there. Also is a prereq for getting us to move to discord

## 🎉   Subtasks

- [x] Identify a Champion
- [x] Onboard the Champion to the praise bot
- [x] Champion makes a scope of work from the praise bot resources for this task (maybe a github issue?)
- [x] find a dev, griff can help :-D
- [x] search to see if a similar discord bot already exists and is open source
- [x] Work with Dev to modify the bot to our specs
- [x] Test the Bot and identify issues
- [x] Revise the Bot and Test again!
- [x] Start using the praise bot!

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://github.com/commons-stack/CommonsStackBot 
https://github.com/Giveth/giveth-bot

**Comment by GriffGreen** [comment]
@WolfofCurrency reached out to help in general, he is a Technical Project Manager based in Miami and we discussed this issue as one that he might want to support in his free time

**Comment by krrisis** [comment]
this has all the code of the existing bot @wolfofcurrency, might come in handy :) https://github.com/commons-stack/CommonsStackBot

**Comment by krisjpi** [comment]
So the bot is active and working in several of the servers - however, we are debugging an additional direct message feature.

**Comment by krisjpi** [comment]
I believe we can close this issue now, with the potential to open a Praise Bot epic for filing new feature requests.
