### ISSUE TITLE
Create a Commons Stack Discord

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#155]
## 📋   Anything to add?

This is not an easy transition... lots of pieces need to come together...

## 🎉   Subtasks

- [x] Make a discord praise bot #154
- [x] Find someone to take on this task
- [x] Work with Kay to deploy a discord
- [x] Make telegram bridges

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by sosmissionsuccess** [comment]
@JonthanH4H is creating a discord channel for H4H community by using lessons learned from BrightID, a well organized set up from another community.  Is this something we can help with?

**Comment by krisjpi** [comment]
The Discord is now active! You can join us at https://discord.gg/KXn9Y7jzvz
