### ISSUE TITLE
Praise Video Tutorial for Period Management

### ISSUE THREAD

**Issue by Rachaelmalachy** [commons-stack/iteration0#1554]
## 📋   Anything to add?

Write video script

- [x] Have script reviewed by @kristoferlund @liviade1 @tamarandom @iviangita
- [ ] Record video and audio
- [ ] Edit recording
- [ ] Share with the team for feedback
- [ ] Make edits (if any)
- [ ] Upload video on Praise website
- [ ] Share videos on twitter, YouTube, Discord etc.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@kristoferlund @tamarandom 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/120wHRBNyVBgzUTpICK2UaBwPMnxarOPOW0JUmheM_os/edit#

**Comment by Rachaelmalachy** [comment]
Script done. Waiting for approval from @kristoferlund to start recording
