### ISSUE TITLE
Make October Payment Milestones

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#156]
## 🎉   A Milestone should include:

In the description:
- [ ] The general roles that you will hold
- [ ] Links to github issues that you'll be working on
- [ ] Explanation of how much you are being paid (either hours, or a salary agreement, or include calculations for PTO if you have any that month)

Also:
- [ ] A picture
- [ ] Descriptive title with your name & the month
- [ ] Date and DAI amount you are requesting
- [ ] Your address as the recipient

## 🎉   Subtasks

- [ ] Livia
- [ ] Gus
- [ ] Griff
- [ ] Jeff
- [ ] Loie
- [ ] Juliet
- [ ] Juan Karlos

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links
Milestone template/example:
https://docs.google.com/document/d/1B229JVdpK5m_lkrsu9bb1fMCDcN-Va4xst77V6sfNQQ/edit?usp=sharing
