### ISSUE TITLE
Push hiring!

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#157]
## 🎉   Subtasks

- [x] Assign someone to lead this task
- [x] Comms Lead job description published and promoted
- [x] Project manager job description published and promoted
- [x] Community manager job description published and promoted

## 🤼‍♂️   Reviewer

@GriffGreen
