### ISSUE TITLE
Trusted Seed Spotlight #3 : Trent McConaghy

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#160]
## 📋 Trusted Seed Spotlight #3 : Trent McConaghy

Interview about Ocean Protocol & getting to know Trent as a human, and him sharing his wisdom he has gained on his journey, reflecting on the times

## 🎉   Subtasks
- [x] Schedule a time for the interview
- [x] Edit
- [x] CS Team Review & Feedback
- [x] Re-edit/integrate feedback
- [x] Distribution

## 🤼‍♂️   Reviewer

@GriffGreen @Jeff-Emmett

**Comment by GriffGreen** [comment]
Interview went great!

Trent created his own simulation system... he created it custom for Ocean's needs

Bonding curves are awesome

Metacartel cultural build is interesting

Ocean is on v2... they don't need to do the full culture build until v4

DAOtalk as a central repository for DAOs... like the DAO Alliance group so everyone can share best practices and the news across the DAO space. 

The kickoff of this might be with the TE Book on the use cases of DAOs... then the book will get on github so it can be forked!!

https://daotalk.org/t/resource-list-dao-creation-design/522

**Comment by jessicazartler** [comment]
Finally back to good internet so will download and begin editing this week :D

**Comment by jessicazartler** [comment]
Ask Zeptimus if he can edit these going forward @jessicazartler

**Comment by jessicazartler** [comment]
Sent to team for final review

**Comment by jessicazartler** [comment]
https://www.youtube.com/watch?v=HPOA5htyHjw&list=PLy6j39s17_jQEFiF6HKiE6gXjaQfFDX6J&index=3
YAY!
