### ISSUE TITLE
Recruiting contributors for small projects

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#162]
## 📋   Anything to add?

Taking on some of the Community Management role... it all was made possible by this awesome github process :-D

## 🎉   Subtasks

- [x] Wolf of currency for the discord praise bot issue
- [ ] Check in with wolf
- [x] Exiledsurfer for swag store issue
- [ ] Check in with Michael
- [x] Jake for CSTK Token DApp issue
- [ ] Check in with Jake

## 🤼‍♂️   Reviewer

@
