### ISSUE TITLE
Go on Omar's show

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#163]
## 🎉   Subtasks

- [x] Come up with an outline of topics
- [x] Provide value to his users
- [x] Shill that we are hiring
- [x] explain how Commons Stack wants to create value for Public goods with the same techniques as defi

## 🤼‍♂️   Reviewer

@
