### ISSUE TITLE
Finish executing on Gitcoin Grants Comms plan

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#164]
## 📋   Anything to add?

See issue #129 

## 🎉   Subtasks

- [x] Content push re: success of community fundraise (using CV!)
- [x] Send out newsletter update with Stake PAN CTA
- [x] Connect 1 on 1 with beneficiary teams to make sure they love us :-D and explain how the funding will work
- [x] Consider more semi-formalized partnerships (e.g. logo swaps for websites)

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links

<img width="737" alt="Screen Shot 2020-09-30 at 6 20 46 PM" src="https://user-images.githubusercontent.com/14945613/94712361-af17ca80-0349-11eb-9369-8efb1f7a8055.png">

**Comment by jessicazartler** [comment]
@GriffGreen do we need anything further on this issue or shall we close it?

**Comment by jessicazartler** [comment]
@krisjpi @knobsdao here is a bit of a template for the next Gitcoin Grant round you guys are working on but I will close this issue since we finished

**Comment by jessicazartler** [comment]
Forwarded for next round -- if there is nothing else, closing as this is complete
