### ISSUE TITLE
Get a new email domain for legal association

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#167]
## 🎉   Subtasks

- [x] Decide on a domain (@csassociation.org or something similar?)
- [x] Create info@ address. Probably don't need anything more.
- [ ] Appoint person to manage the association's email address.

## 🤼‍♂️   Reviewer

Coach B is really the reviewer. He is the best person to check in with to make sure we are using this email address properly.

**Comment by krisjpi** [comment]
currently blocked by 2fa on the hosting account - looking to consolidate some of these details moving forward.

**Comment by GriffGreen** [comment]
info@commonsstack.foundation
legal@commonsstack.foundation

**Comment by krisjpi** [comment]
Created email and inbox, all that's left is to assign inbox management.
