### ISSUE TITLE
Create a Trusted Seed group on BrightID

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#169]
## 🎉   Subtasks

- [x] Jess check with Phil on process
- [x] Griff choose admins (Jess, Griff, Jeff)
- [x] Jess figure's out the admin setup 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by Jeff-Emmett** [comment]
Suggesting Jess as someone who can facilitate the creation of this BrightID seed.

**Comment by jessicazartler** [comment]
FROM PHIL (Discord UBIPromoter) @ BRIGHT ID:

Would be happy to help create a seed group for the Common Stack.
A Seed group needs to be founded by three people.
These 3 are the administrators of the group and have the power to invite and remove other users.
The 3 admins all need to be public and findable in the context of the project. (We could find them on discord, at meeting, that sort of thing.) The admins can invite anyone else into the seed group provided the new person is connected to at least 50% of the existing members.
Seed members need to be good actors on the BrightID network.
At this stage that means only connecting to people they have seen in real life or via live video, and not connecting to anyone you believe may be trying to harm the network. Responsibilities may increase at some point, but for now just be a good actor.
So...with all that in mind, do you know who the three founding group members should be?

@GriffGreen let me know who you would like to be the TS admins and then we can proceed

**Comment by jessicazartler** [comment]
@GriffGreen this is still ready to roll -- you had said me you and Jeff for the three admins? Doesn't matter so much, just for backup for the account

Shall I proceed?

**Comment by jessicazartler** [comment]
Created the group and got the code from here https://explorer.brightid.org/ you should check out the visualization graph/concentric circles of your own account, pretty cool!

If you are interested:
Go to the home screen of your app, hit the hamburger menu and press 'Copy your Explorer Code'.
Paste this code and your password in the https://explorer.brightid.org/ and all of your groups and connections will be visible.

Anyhoos, Phil is submitting it to the Seed DAO to vote us in as a seed group :D So he will let me know when it's done, then we are online @GriffGreen !

**Comment by jessicazartler** [comment]
@GriffGreen - FROM PHIL OF BRIGHT ID:

Y'all are a seed group now!
The three of you are the admins that control membership of the group (invite and remove members).
Anyone connected to 50%+1 of the existing members (so 2 right now) is eligible to be invited to join the group as a non-admin member.

Please limit membership to strong community members that you know well and trust to be good steward of both brightID and Common Stack.

Anyone that connects to any of the members of your new seed group will get a bump in their BrightID ratings.

This will become increasingly important as we start rolling out more algorithms and offering various different verification options to applications.

**Comment by jessicazartler** [comment]
@knobsdao @GriffGreen This falls under Dan's domain - we need to put it on the roadmap somewhere or this is a tool we have for engagement - not a priority necessarily

**Comment by jessicazartler** [comment]
@knobsdao we can discuss on TS call :D

**Comment by jessicazartler** [comment]
Going to close this --- goes with this Epic https://github.com/commons-stack/iteration0/issues/315

Whenever we want to push this forward
