### ISSUE TITLE
Get access to all the first member accounts of the Public Goods Twitter Collective

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#171]
## 📋   Anything to add?

Sharing network for Twitter/RTs

- We have cadCAD, TEC, CS, Blockscience, TE all in :-D

## 🎉   Subtasks

- [ ] @krisjpi synv w/ Dani on Giveth Twitter
- [X] share content on Public Goods Twitter Collective Telegram channel
- [x] invite partners to that channel for content sharing, later have a channel in the TEC/CS discords for social shares
- [x] long-term goal is to have a contributor from TEC / cadCAD owning Twitter so Kris doesn't have to manage ALL the accounts

## 🤼‍♂️   Reviewer

@jessicazartler @Jeff-Emmett

**Comment by jessicazartler** [comment]
Tweeted the Research Roundup on CS
Retweeted cadCAD #3 call from TE on CS
Working on Tweets for the week ahead..

**Comment by jessicazartler** [comment]
Sounds like @magentaceiba is handling Giveth's Twitter going forward.. I added her to the Public Goods Twitter Collective channel so I will close this issue as for now, everything seems to be covered and Kris/Jeff/Dan/I have Twitter Parties every Friday to schedule, Tweet, cross promote and work with Angela TE in that collective Telegram channel - many thanks guys!
