### ISSUE TITLE
Soft governance & culture working group 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#173]
## 🎉   Subtasks

- [x] transfering typeform responses to the miro
- [x] preparing and hosting weekly calls
- [x] managing and helping with action items
- [x] presenting progress in the Thursday syncs
- [x] organizing deliverables that need further work into a new working group proposal

## 🤼‍♂️   Reviewer

@
