### ISSUE TITLE
Risk-adjusted bonding curve documentation

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#174]
## 📋   Anything to add?
Documentation for the risk-adjusted bonding curve project between ixo & ICF, which is a prediction market/bonding curve hybrid cadCAD model.  This is a component that could be useful for WhalerDAO (Impact Certificates), Metagame (deliver 'x' functionality by date 'y' fundraising), and dozens of other communities & DAOs.

## 🎉   Subtasks

- [ ] 2x Weekly sprints with ixo & BSci team
- [ ] Produce notebook documentation
- [ ] Medium article
- [ ] Twitter thread
- [ ] Distribution campaign (posts, community reachouts, cadCAD community call, etc)

## 🤼‍♂️   Reviewer

@mzargham

**Comment by jessicazartler** [comment]
To discuss on our Comms call next week

**Comment by GriffGreen** [comment]
Paul Stamets meeting this week.. this will come up and it would be interesting to dust off this model...

It's a little advanced but maybe it could be a phase 5 plan... Phase 1 - NFTs

**Comment by jessicazartler** [comment]
Had a call with Shaun Conway yesterday and scaffolded a series - Jeff and I will scaffold a high level article (this one needs to be broken down into a few) and aim to publish in December

**Comment by jessicazartler** [comment]
Drafts & Scaffolding in progress
https://docs.google.com/document/d/144NmQcrOctveqSL4poJm51MHoPE66DY1f2lIE808YzQ/edit
