### ISSUE TITLE
Handoff CRM

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#175]
## 🎉   Subtasks

- [x] Loie & Griff spreadsheet session to connect telegram & twitter handles into CRM
- [x] Loie meet with Livia and show her the ropes
- [x] Upgrade to paid ($50/mo) plan where we can have several lifecycles

## 🤼‍♂️   Reviewer

@liviade1
