### ISSUE TITLE
Review comments on Felix CS paper

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#178]
## 📋   Anything to add?
Aim is to get Felix's paper on the Commons Stack out & into our community where it can help people understand what it is we are building.

## 🎉   Subtasks

- [ ] Review final comments & discuss wrap up with Felix

LATER
- [ ] Host paper somewhere (CS github?)
- [ ] Distribution campaign for completed paper

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1NdZMBbLROVBXtuqpkLkdPDwu0CN_zE_1e_7bQakxWRE/edit?disco=AAAAJn3QiD8&ts=5f74e795&usp_dm=true

**Comment by GriffGreen** [comment]
Waiting on Felix... no action this week

**Comment by Jeff-Emmett** [comment]
Felix mentioned this publication may have to wait until the new year, with recent conversations requiring he revisit the manuscript of his case study.

**Comment by Jeff-Emmett** [comment]
Blocked for the moment until Felix has the time to finalize content & publish, hopefully in early 2021.
