### ISSUE TITLE
Hire a project manager 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#180]
## 🎉   Subtasks

- [x] Create a job description
 

- [x] Put Job Description on twitter

 

- [ ] Juliet does 1st check on applications

 

- [ ] Griff/Jeff/Lorelei will be interviewing people

- [ ]  Griff is available for an interview round with the top 3

🤼‍♂️ Reviewer
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by Kisgus** [comment]
Closing and moving to #135
