### ISSUE TITLE
Hand off management of info@ email

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#183]
## 🎉   Subtasks

- [x] Send login to Jeff, Griff and Juliet
- [ ] New person create new secure password & keep it in a password manager
- [ ] Loie give a description of what needs to be done in holding this role
- [ ] Mail script research - Jeff

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links

**Comment by GriffGreen** [comment]
I have the login!
