### ISSUE TITLE
Handoff CSTK registry sheet management

### ISSUE THREAD

**Issue by loietaylor** [commons-stack/iteration0#184]
## 🎉   Subtasks

- [ ] Work session with Griff
- [ ] The manager of this sheet needs to either a) also manage Praise accounting or b) work closely with the person who does
- [ ] Loie find video walk thru made in june & make accessible to the new holder of this role

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links

**Comment by tamarandom** [comment]
Closing out all the old issues and epics. 🧹 🧹 🧹
