### ISSUE TITLE
October ongoing fundraise for Iteration 0

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#185]
## 🎉   Subtasks

- [ ] "Let it trickle in" passive approach from last month continues?
- [ ] Loie make sure ppl have knowledge they need to continue this
- [ ] Appoint someone to deal with "yes I'll donate after filling out this form" ppl
- [ ] Help people donate

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by lorelei1** [comment]
Jeff has a current hot donor - we should talk about this in standup call today
