### ISSUE TITLE
Spreadsheet with contribution reward info for Sem 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#186]
## 🎉   Subtasks

- [x] List all the contributors since the beginning of the praise quantification 
- [x] reach out to them individually and collect their addresses, ALERT THEM THAT THEIR ADDRESS WILL BE LINKED TO THEIR NAME 
- [x] sum everyone's impact hours so far 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by liviade1** [comment]
Craig finished completed this issue
