### ISSUE TITLE
Get CSTK tokens dished for gitcoin and praise

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#187]
## 📋   Anything to add?

We are doing a CSTK Token play on Thursday... we need CSTK token Balances right before then

## 🎉   Subtasks

- [x] token math done for gitcoin
- [x] token math done for praise
- [x] add token math to sheet
- [x] Create Vote
- [x] Pass vote

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by lorelei1** [comment]
tokens minted on monday last week
