### ISSUE TITLE
onboarding working group attached to soft gov

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#188]
## 🎉   Subtasks

- [ ] call with Angela to start planning
- [ ] add info to the soft gov manifesto

- [ ] add to thusrday sync agenda call 

- [ ] plan weekly syncs with the new group that is going to be formed
- [ ] attend system value flow classes 
- [ ] review documents 

## 🤼‍♂️   Reviewer

@
