### ISSUE TITLE
Hire a Communications all rounder #1

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#190]
## 🎉   Subtasks

- [x] Write Job description
- [x] Announce position
- [x] Put Job Description on twitter & all the channels
- [x] Juliet? does 1st check on applications
- [x] Livia? checks applications & makes shortlist
- [x] Livia? emails back applicants w/ no thank you or yes schedule a call
- [x] Griff/Livia? will be interviewing people
- [ ] Make a final decision

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by lorelei1** [comment]
We are starting to get a decent flow of applicants... let's kick this process into gear

**Comment by lorelei1** [comment]
https://commonsstack.org/open-positions listing is here

**Comment by GriffGreen** [comment]
Hired Kris!
