### ISSUE TITLE
Gitcoin Grants Thank Yous on GG Platform

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#192]
## 🎉   Subtasks

- [x] Jess write template
- [ ] Jeff & Griff edit templates
- [x] Jeff post thank you to cadCAD grant 
- [x] Jeff post thank you to Conviction Voting model upgrades
- [ ] Lorelei & Griff post thank yous to CS grants (Panvala League and others?)

## 🤼‍♂️   Reviewer
@GriffGreen @lorelei1 

## 🔗   Work doc - GG Thank You Template
https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit

**Comment by GriffGreen** [comment]
sort of done, split 2 thankyou's off into their own issues #198 and #199

**Comment by Jeff-Emmett** [comment]
Send outs for CV & cadCAD were sent last week, checked the boxes above and I believe my action steps are completed on this task.  Let me know if you need help with anything else on my end!
