### ISSUE TITLE
Community Email/Newsletter: GG Thank You & News 

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#193]
## 📋   Community Email/Newsletter
Content: Thank you for fundraise, news & TEC Invite

## 🎉   Subtasks
- [x] Jess write draft 
- [x] Jeff Edit 
- [x] Griff Edit
- [x] Jess put in Mail Chimp / Graphics & Design
- [x] Jess & Jeff send

## 🤼‍♂️   Reviewer
@GriffGreen @Jeff-Emmett 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1Oc6imWoIcknhGPtZxCzJh1Hijlrfnoe7pMkmLZh-to8/edit

**Comment by jessicazartler** [comment]
<img width="746" alt="Newsletter Analytics" src="https://user-images.githubusercontent.com/43972522/97225594-13367e80-1790-11eb-9c86-e248cf448086.png">
<img width="479" alt="Links" src="https://user-images.githubusercontent.com/43972522/97225597-13cf1500-1790-11eb-97ca-713b3b8bc615.png">

**Comment by jessicazartler** [comment]
Great work everyone! Thank you!
