### ISSUE TITLE
Academic Study Group on TE Commons

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#194]
## 📋   Anything to add?

Felix has been leading a group of awesome people talking about Commons Management, with a few months worth of sessions on the Economic Space Agency. Next up is the Commons Stack & TEC!

## 🎉   Subtasks

We would start with just an introduction call

- [x] Talk with Felix & Livia about TEC soft gov processes & a date for a first sync call
- [ ] Set up CS/TEC Academic Study Group session(s)
- [ ] Invite the TEC community to chat about the story
- [ ] have the call
- [ ] see where we go from there

## 🤼‍♂️   Reviewer

@liviade1 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1BM0Kf9psfBNOXIZzBOA_K7tTzMsaBWXSfwds8_jc4ZA/edit?usp=sharing

**Comment by liviade1** [comment]
Can we make this a group to discuss best practices on decentralized governance? I saw some interest on in in CS chat last week @Jeff-Emmett

**Comment by Jeff-Emmett** [comment]
That sounds like a great topic for discussion with the group for sure!  Felix seemed very interested to focus the next phase of his case study on the application of the CS toolkit in the TEC, especially in the addition of other forms of soft governance (one of his critiques of the CS was that Conviction Voting is an insufficient governance tool for the myriad complexities of commons governance).

**Comment by GriffGreen** [comment]
@ataberkcasur what do you think?

**Comment by tamarandom** [comment]
Leaving in the product backlog but of interest to all to get some love on this during this sprint.

**Comment by GriffGreen** [comment]
CCG might addd some more action
