### ISSUE TITLE
Happy Praisegiving! Meetup & Virtual Potluck

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#196]
## 🎉   Subtasks

- [x] Jess start doc and make plan
- [x] Jess & Livia get feedback and input from the community
- [x] Jess/Marko/Tom make promotional graphic/meme
- [x] Get volunteers to help invite people
- [x] Jess & Livia talk to Angela and make Meet Up event
- [x] Promote event
- [x] Have fun at potluck and everybody leaves feeling full of gratitude and love <3 And.. wanting to join TE Community :D

## 🤼‍♂️   Reviewer

@jessicazartler @liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links
SIGN UP SHEET 
https://docs.google.com/spreadsheets/d/1QYOJJeitDqZ9ZZ5CDZDP_0lPUPuNJgvoOmHl4GQhp1E/edit#gid=0

WORK DOC
https://docs.google.com/document/d/1RfKcUErI77LjJF9Uy-CKVmf-O3b-4QXcgkOxuHgwE98/edit

**Comment by GriffGreen** [comment]
We can remove this from the October sprint planning right?

**Comment by jessicazartler** [comment]
Oops! Didn't mean to check that box... will take some next steps :D

**Comment by jessicazartler** [comment]
In case you missed it 🍿 
https://www.youtube.com/watch?v=vMbs1Yv68Sg
