### ISSUE TITLE
CRM 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#197]
## 🎉   Subtasks

- [ ] get familiar with the CRM
- [ ] schedule another call 
- [ ] make notes on people 
- [ ] life cycle flow of contributors

## 🤼‍♂️   Reviewer

@lorelei1
