### ISSUE TITLE
Panvala League thank you after all the funds are sent out

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#198]
## 📋   Anything to add?

Part of #192 decided to save this gratitude explosion for when the final results are in and we can give concrete numbers

## 🎉   Subtasks

- [x] Identify large donors (Lorelei did this!0
- [x] write out a draft of the email
- [x] Do accounting on PAN and make the send ASAP
- [ ] Send out the email too 

## 🤼‍♂️   Reviewer

@jessicazartler

**Comment by jessicazartler** [comment]
@tamarandom @GriffGreen should this be closed or is this a recurring?

Just wondering when the Panvala totals will be in for the last round to send out the newsletter/final thank you - just want to make sure it's on the board

Thanks!

**Comment by tamarandom** [comment]
Closed, dupe of #699
