### ISSUE TITLE
TEC Thank you for Gitcoin Donations

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#199]
## 📋   Anything to add?

Part of #192 decided to save this gratitude explosion for when the social links for the TEC are ready

## 🎉   Subtasks

- [ ] Identify large donors (Lorelei did this!)
- [ ] write out a draft of the email
- [ ] Get all the TEC twitter, website and all that sorted
- [ ] Send out the email too 

## 🤼‍♂️   Reviewer

@jessicazartler 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit

**Comment by jessicazartler** [comment]
@GriffGreen did the ship sail on this? I feel like at least the thank you on Gitcoin itself could be good promo for TEC

Whatcha think?

**Comment by liviade1** [comment]
https://docs.google.com/spreadsheets/d/1Z-VqJFTeVdMcjDYFOVLjHxjHWsPdbY4-8k76bC6Iji0/edit?usp=sharing praise list

**Comment by JuankBell** [comment]
(Really basic idea)

Hello {}, 

We want to thank you for contributing in this #GR8! your support means a lot to us. 

Our community is working to apply knowledge from different areas to generate value for all humankind.

The Token Engineering Commons Team wishes you wealth and happiness in this holidays, and a prosper 2021.

**Comment by cranders1** [comment]
Thnx Juan. Appreciated. I'm on it once the round ends.

**Comment by cranders1** [comment]
Individual donor thanks done via GC board emojis
TEC Gitcoin Rd8 thank you sent via GC board (automated GC emails also enabled)
https://gitcoin.co/grants/1155/token-engineering-commons

**Comment by tamarandom** [comment]
Closing!
