### ISSUE TITLE
CSTK Token DApp

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#2]
## 📋   Description

Automating the creation of CSTK tokens when Members of the Trusted Seed donate. 

## 🎉   Definition of done

- [x] Review the scope and confirm the direction... reconsider approach since doing smaller raises
- [x] Make a roadmap with Sponnet/Pavle 
- [x] Finalize Design with new changes for subprojects within Iterations
- [x] Create Giveth Bridge for xDAI
- [x] Finish front end and web3 connections
- [x] Write Smart Contracts for Registry
- [x] Deploy Registry Contracts to xDAI
- [x] Connect them to xDAI Giveth Bridge and CSDAO
- [ ] App tested by core team to confirm it does what we want
- [ ] Integrate changes
- [ ] App tested with Trusted Seed Superstars (people with over 3000 CSTK Tokens) to confirm it does what we want
- [ ] Integrate changes

THEN WHOOO HOOOO We are ready to start the raise!
## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Links
Design: https://www.figma.com/file/zShSUtGA4wZBtTlaxEDEVU/Figma-School?node-id=207%3A2024

CSDAO: https://aragon.1hive.org/?#/csdao/0xaa89fb730a83146cbf06661fd436e7445b4d0232/vote/10/

**Comment by Kisgus** [comment]
Please specify this issue further @GriffGreen

**Comment by lorelei1** [comment]
Token DApp has it's own repo: https://github.com/commons-stack/tech-token/issues

**Comment by lorelei1** [comment]
This one also feels HUGE, so let's discuss it! @GriffGreen am I right that @sponnet is the key starter on some of these things?
Would probably be good to have a little sprint roadmap just for the CSTK DApp being finished sometime in October

**Comment by GriffGreen** [comment]
Ok! I found someone to lead this charge :-D 

https://github.com/johnnyxrilla

He is going to try to kick us in the ass to make this happen

**Comment by johnnyxrilla** [comment]
CSTK HACKATHON!!!   Two day weekend free for all!  Let's get these contracts done. @GriffGreen @sponnet lets have a call and a sprint por la manana !!

**Comment by GriffGreen** [comment]
Roadmap

1. Minter contract: add the admin role to the minter so we can have multiple authorized keys - @paxthemax can you do that?

2. Minter: The Minter should check the maxTrust, but instead of reverting it should change the amount of tokens to meet maxTrust... here is the expected behavior: if  there is 1 million tokens, and Sponnet has 45,000 CSTK and a max trust of 500,000 (5% of the supply) then he donates enough that should get him 10,000 more CSTK, but instead he only gets 5000 CSTK because (maxTrust(addr) / 10,000,000)*totalSupply in this case means: (500,000/10,000,000)*1,000,000 = 50,000 so Sponnet can only have 50,000 CSTK so he only gets minted 5000 CSTK....
^^^ Make that happen 😃 - Pavle 😊?

3. Then we redeploy the minter and wire up all the things? - Amin & Sponnet... you might have to work together on that

4. Then we can test donations and try to get donations to mint CSTK - @aminlatifi 

5. Visualize everything  on the front end - @Sponnet2 
- MaxTrust
- Description from Milestone
- Total supply from CSTK token
- make everything pretty

6. Test a donation thru the UI - Team celebration!!!

7. Rewire things to work with the mainnet Giveth Bridge and test with a real donation to a real Milestone on the test DAO - Griff and Amin

8. Then connect the minter to the real CSTK DAO and play with it make sure it works.

9. Let Marko & Gus make some UX suggestions 😃 and improve the front end a bit 😃

10. Launch to the public!

**Comment by tamarandom** [comment]
Done. https://member.commonsstack.foundation/

Spring cleaning up old issues. 🧹
