### ISSUE TITLE
Gitcoin Grants Rd 8

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#200]
## 📋   Anything to add?

Scott | Gitcoin, [22.10.20 18:58]
basically, we're running a hackathon alongside Round 8 in December and we'd love to have you all post some prizes, no need for a sponsorship fee or anything like that

we're trying to get out of the habit of doing more community focused events

we have a bit of EF budget we could probably put towards the prizes as well

Any guidance on what sort of hackathon bounties you are looking for... if its prescriptive or if its pretty open ended... i would be open to hear more

super open I think as long as they're public goods related which I think will be hard to avoid in this case lol

## 🎉   Subtasks

- [x] Find someone to carry the flag.
- [x] have them fill out this issue.
- [x] Organize a meeting to launch the effort.
- [x] Sync with TEC efforts.
- [x] Create a dedicated issue to do CV and for Comms.

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links

[Gitcoin Grants Rd 8: TE Commons Grant Development, Submission, Tracking](https://app.zenhub.com/workspaces/core-team-organization-5f1206c0362e7b000fc0161b/issues/tecommons/coordination/66)
[Rd 7 Gitcoin Grants Comms Plan](https://github.com/commons-stack/iteration0/issues/164)

[TEC GC Rd 7 Grant](https://gitcoin.co/grants/1155/token-engineering-commons)
[Token Engineering Grant Collection](https://gitcoin.co/grants/collections?collection_id=11#)
[Commons Stack Community Grants Collection](https://gitcoin.co/grants/collections?collection_id=8#)
[Token Engineering, Commons Stack & Friend Collection](https://gitcoin.co/grants/collections?collection_id=49#)
[Panvala League](https://panvala.com/)
[cadCAD Education Bounties](https://gitcoin.co/grants/308/cadcad-computer-aided-design-for-complex-systems)
[Luna Swarm Conviction Voting Model](https://gitcoin.co/grants/1141/conviction-voting-cadcad-model-feature-improvement)

**Comment by Jeff-Emmett** [comment]
Added myself to this task as I'm helping to manage the cadCAD and Conviction Voting Gitcoin Grants.

**Comment by jessicazartler** [comment]
TEC Gitcoin issue that is linked
https://github.com/TECommons/coordination/issues/66

**Comment by jessicazartler** [comment]
**HIGH LEVEL PLAN & ROADMAP:**
**_Dec. 2- 17_**

**Dec. 1** - Update Gitcoin Grants 
**Dec. 1 & 2** - Blog post high level & CV how to, Newsletter 1: Announcing and linking to blog(s)
**Dec. 2** -  Send out to the community via Telgram/distribution channels, Submit proposals to CS CV: 3 so far - CSTK tokens/add proposal 
**Dec. 13** - Close CS Conviction Voting

**NOTES:**
Matching opps - Gitcoin has $1 million this round / Panvala matching league

**Comment by cranders1** [comment]
Updated and posted to cv.commonstack
https://gitcoin.co/grants/1155/token-engineering-commons

Shifted #66 to in progress due to tracking and follow-up component
