### ISSUE TITLE
Take Jonathan's cadCAD Beginner Course

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#201]
## 📋   Anything to add?
I was offered the opportunity to take the cadCAD Beginner course designed by Jonathan & crew, to give feedback and reviews as necessary.  Seems like a great opportunity to get an in-depth look at a course that could help onboard new cadCAD users.

## 🎉   Subtasks

- [ ] Review course materials
- [ ] 2-3 two hour sessions for review & feedback
- [ ] write & submit review for course

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by Jeff-Emmett** [comment]
Wow - definitely recommend taking & distributing this course when it's live!
