### ISSUE TITLE
Frontiers Paper Reviewer Responses

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#202]
## 📋   Anything to add?
Wasn't expecting to have to reply to the reviewers so soon, but we do!

## 🎉   Subtasks

- [x] Review & discuss with author team
- [x] Drafting & editing replies, revising manuscript
- [x] Submit to reviewers

## 🤼‍♂️   Reviewer

@mzargham 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1zW4D57AkY0yfVmWccF0Aw8dT4oRWbgUGgryVcfkalOQ/edit?usp=sharing
