### ISSUE TITLE
cadCAD Onboarding TL;DR creation and distribution

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#203]
## 📋   Anything to add?
Put together a Notion of all relevant cadCAD links, videos, tutorials, demos & more. 

## 🎉   Subtasks

- [x] Create notion doc: https://www.notion.so/cadCAD-Onboarding-TL-DR-8d36c3a53260497c8cd6068a434336f8
- [x] Share & feedback round
- [x] Put into content distribution workflow

## 🤼‍♂️   Reviewer

@mzargham 

## 🔗   Work doc - inspirational links
https://www.notion.so/cadCAD-Onboarding-TL-DR-8d36c3a53260497c8cd6068a434336f8

**Comment by jessicazartler** [comment]
Team work session knocked it out! Thank you @krisjpi for supporting Jeff and I in blasting this out!
