### ISSUE TITLE
Get PrimeDAO partnerships set up for Commons Stack, Giveth and TEC

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#204]
## 📋   Anything to add?

We had a grat call with Pat and feel very aligned with the PrimeDAO effort. Now we just gotta figure out how to become officially involved

## 🎉   Subtasks

- [x] Research our options... How do we get involved as a partner Org?
- [x] Present the options to Jeff Griff and Livia for Commons Stack
- [x] Present the options to Jess for TEC
- [x] Present the options to Griff for Giveth
- [ ] Figure out the steps for each move after that...

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by Zion-code** [comment]
Would like to be assigned to this issue! As I have a good understanding of DAOstack's tool and know quiet some of the longtime users!

**Comment by GriffGreen** [comment]
Hey @Zion-code !!! 

> Would like to be assigned to this issue! As I have a good understanding of DAOstack's tool and know quiet some of the longtime users!

We missed this issue, some how it fell out of our sprint planning and was happening with Ruben!

But oh man we would love to loop you in on other issues!! Thank you for messaging us!

**Comment by Zion-code** [comment]
The TEC partnership and the Giveth partnerships are set on PrimeDAO xdai chain.

The logos have been shared and the appointed DAO ambassadors are joining the PrimeDAO community calls. 

Commons Stack appointed PrimeDAO ambassador @tamarandom  will hopefully complete the Commons Stack related proposal this friday!

Hopefully closing this issue.

**Comment by tamarandom** [comment]
Hi there!

The Commons Stack proposal was submitted this morning. (Yay!) 
Pat confirmed he received the logo from Jeff already. 
We are all set. As long as it gets approved ;) 

https://alchemy-2-xdai.herokuapp.com/dao/0xe3a89ed4956c4f7173418e4dec2a77a5f60807de/proposal/0xa877a4a2c40aff92b72fac202390d5af099961302618f597f868d90c6749ece7
