### ISSUE TITLE
cadCAD 1Hive Model Expansion

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#205]
## 📋   Anything to add?
A network collaboration is forming to model more features of the 1Hive system in cadCAD. There will be another call in two weeks to keep pushing the ball in scoping work and submitting a proposal to 1Hive to fund the work. Will update when the next call is scheduled. 
https://www.youtube.com/watch?v=IZZUDnCBhYg&feature=youtu.be

## 🎉   Subtasks

- [x] Forum post (Jeff/Jess)
- [x] Fork/transfer CV model to 1Hive repo (Z/Luke/Sem)
- [x] Set up next call in 2 weeks & coordinate (Jeff)

## 🤼‍♂️   Reviewer

@Jeff-Emmett @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1UkWflaDNh5aF8BeRUoIQx3g3z7P2mE0cU0N4dbwz4Sk/edit?usp=sharing
