### ISSUE TITLE
Process for Onboarding Contributors and Community Engagement

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#209]
## 🎉   

**THE PROCESS**
- [ ] Contributor Journey mapping
       A) Contributor joins organically -
       B) Contributor applied for a job to CS -

Dan as filter & project lead -- _BI-WEEKLY AMA FOR CONTRIBUTORS_ (January?) @knobsdao 
-Contributor gets passed to Dan 
-Dan examines experience/background, checks with appropriate project lead 
-Agree on salary/tokens - default tokens only (project head is responsible for making sure they get paid/milestone)
-Project leads takes them under their wing for one session
-Assign managers who to report to (Dan or head of project)
-Milestone learning sessions
-If not qualified, send general contribution ways to support infogx / help with SM advocating
**-Dan follows up and makes sure they are all good -- REGULAR CHECK INS** (weekly office hours / very important)
-If they are superstars, maybe they get permanent place 

**SUBTASKS**

MUST HAVES 
- [x] Clean Github issues and add welcome/intro template w/ project lead contact @krisjpi 
- [ ] General onboarding guide update - Understanding what is the commons stack? 
            - [ ] Glossary of terms - project-specific and reference within the onboarding process.

OTHER NEEDED TASKS
- [ ] **Create list of current active / past inactive contributors** and people who said they wanted to contributed via TS application @knobsdao 
- [x] Milestone learning party sessions (once per month/bi-weekly) DO IT LIVE! @GriffGreen 
](https://github.com/commons-stack/iteration0/issues/240)
- [ ] infographic 4-5 ways to support the commons stack (i.e. tweeting social share templates) / Benefits to contributing -- social media advocate @jessicazartler @krisjpi 

**NICE TO HAVES**
- [ ] (stretch) an idea that came up chatting to Dan - a popup with an actionable issue from this area on website 

**WHERE WE NEED HELP**
-Channel participation / filtering: ambassadorships
-Social media: finding thought leaders and engaging, Tweeting, sharing in their networks
-Activity on the TEC forum
TAGGED ALL W/ "FOR CONTRIBUTORS"

## 🤼‍♂️   Reviewer

@liviade1 @jessicazartler @GriffGreen 

## 🔗   Work doc - inspirational links
TEMPLATE IF NEEDED
- [x] Review [TEC Onboarding Guide](https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit?pli=1#) and [TEC Coordination Issues](https://github.com/TECommons/Coordination/issues) as starting

**Comment by jessicazartler** [comment]
@liviade1 @krisjpi what did we decide for next steps on this? Was it document the process that we discussed and did we want to ask Tamara to help manage? Also we had discussed documenting who are current / past contributors and where they are at... like contributor mapping @liviade1 like we did with TEC.. just a lot flying so can't remember what we need to do to keep moving forward - thanks guys!

**Comment by GriffGreen** [comment]
See #217 we need to combine this with #162 as well hopefully we can close all these issues

**Comment by jessicazartler** [comment]
Suggestions from Griff
i think we need one person negotiating payments with clear guidelines... Here is my crack at it:

Everyone gets paid 19 DAI an hour if they want pay
Everyone is trusted to track their own hours... we have had a lot of success with assigning one person to cat herd everyone to fill in their hours... ideally this would be on a weekly basis... like every friday, someone goes around and chases all our contributors down to get them to put down their hours
They can choose to get 50% pay and 50% IH and CSTK or only IH and CSTK which would be lavishly slathered on them if they work for just those.
The work must be attached to a github issue with a reviewer
The reviewer is someone deep in the game
The reviewer is their buddy and onboarder and main point of contact for that issue.
That issue should be added to our weekly sprint

**Comment by jessicazartler** [comment]
FROM GRIFF

This issue is very similar to #162 #217 .... in fact i think they are all the same issue... and #242 and #224 might also be connected

We need to clean this up!!! :-D

@knobsdao I'm calling on you for help on this?

**Comment by GriffGreen** [comment]
https://miro.com/app/board/o9J_kkC0kIM=/?moveToWidget=3074457351528109791&cot=12

**Comment by jessicazartler** [comment]
What do we need to do next to move this forward? I feel like we need someone to manage contributors - there was discussion around @tamarandom taking this on as part of PMing the PMs or Dan as community manager?

I think another big step would be creating a list of contributors/agreements/info for tracking in a private permissioned doc..

**Comment by jessicazartler** [comment]
Any thoughts on this @tamarandom @GriffGreen @knobsdao ? :D

**Comment by Jeff-Emmett** [comment]
Hey @jessicazartler @liviade1, August Domanchuk reached out about being interested in the community management position - I know he's an engaged & informed community member of the Commons Stack, so hopefully we can use this process to find ways for him to contribute cuz he's awesome!

**Comment by tamarandom** [comment]
@jessicazartler Yes! This has to be tackled. ;) The sense of urgency vibrates harder every day it's open.

Let's start with a real time working session focused on what we know, what we need and what comes next. 
https://doodle.com/poll/id3pfb6d2pe7myaw?utm_source=poll&utm_medium=link

It can be open to whomever wants to join but needs you, @jessicazartler, and @liviade1, @knobsdao and maybe @krisjpi and @GriffGreen too. Does that sound right to you?

[Doc](https://docs.google.com/document/d/1H-E9VBNc7pObM1NzPHy53P3vY4kYgZavKuXnm6N7YR8/edit) to add the to agenda.

**Comment by jessicazartler** [comment]
Thank you so much @tamarandom! Meeting set for this Wed, 2:15PST/11:15CET and @knobsdao will be our Contributor Champion - woohooooo Dan!!!!

Will scope out/ID issues under this epic in the meeting to move forward :D

**Comment by jessicazartler** [comment]
For the template at the top of Github issues:
-TL;DR Commons Stack mission - why these tasks are important
-Project lead/Dan contact weekly office hours/AMA eventually
-Rewards in tokens? Application to the Trusted Seed (if they are not already)
-What is considered completing the issue or success
-What to do when they finish

**Comment by liviade1** [comment]
my inputs on template @krisjpi 
- Welcome and a tldr of what is the Commons Stack or what is the TEC (depending on the issue)
- What is the purpose of this issue
- Resources related to this issue
- What is deadline
- Who are the people that can help them in case they get stuck and best ways to contact them
- expectations for completion

I had this on draft and left the computer, seeing what you posted now @jessicazartler we're pretty in sync :) +1 to what to do when they finish, good idea

**Comment by jessicazartler** [comment]
@knobsdao @tamarandom just going through all my issues - this one looks like it might need to be broken down, cleaned up or is maybe represented elsewhere? Looks like from before we got more organized with Github -- just tagging for refinement/clean up

**Comment by tamarandom** [comment]
Good #refinement tagging, @jessicazartler! I'm marveling at how we are ALL assigned to this one! 
 
Some pieces are done, some are no longer relevant. 

When I look at this I see an epic for Community Management and the Onboarding Process being one of the issues within. I say we do that, reference this issue in case we need to go back to the thinking from October, and close this one. Then in our upcoming Sprint Planning sessions we can discuss when we want to prioritize this work into a Sprint.

**Comment by jessicazartler** [comment]
Great moves thank you!
