### ISSUE TITLE
Implement Ostrom's principles 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#211]
## 🎉   Subtasks

- [ ] principle 1 and 2 - propose a written agreement of our boundaries and rules
- [ ] principle 3 - experiment the advice process in the forum as part of submitting a proposal
- [ ] principle 4 - it will come out of the legal working group
- [ ] principles 5,6,7 - proposal coming out of the conflict management working group
- [ ] principle 8 - proposal for our fractal configuration 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by GriffGreen** [comment]
This needs to probably be closed in favor of issues in TEC Coordination

**Comment by iviangita** [comment]
Copied to TEC Coordination workspace [issue 216](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/216)
