### ISSUE TITLE
Contributor tracking TEC xls

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#212]
## 🎉   Subtasks

- [x] Create an onboarding sheet to add all participants and who is their main point of contact
- [x] Share with community stewards 
- [ ] keep this sheet updated with the last status of contributors 
- [ ] Add the doc to the TEC Stewards weekly agenda notes & pin to the top of Telegram

## 🤼‍♂️   Reviewer

@

**Comment by liviade1** [comment]
https://docs.google.com/spreadsheets/d/1DRSPA9RwuTM4UCtFLF7UYq-ORZxItmy9y7XROmiXpbM/edit#gid=0

**Comment by tamarandom** [comment]
Closing this issue. Moved it to [TEC repo](https://app.zenhub.com/workspaces/core-team-organization-5f1206c0362e7b000fc0161b/issues/tecommons/coordination/206).

**Comment by liviade1** [comment]
https://docs.google.com/spreadsheets/d/1DRSPA9RwuTM4UCtFLF7UYq-ORZxItmy9y7XROmiXpbM/edit#gid=0
