### ISSUE TITLE
update TEC documentation 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#213]
## 🎉   Subtasks

- [x] track all the documents from all working groups
- [x] add wg's info to the onboarding guide 
- [x] sync with onboarding wg 
- [x] sync with Kris to implement a discord onboarding page 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Check! Closing!
