### ISSUE TITLE
Onboard and Support Ata on the Cultural Playbook - Sprint 2

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#214]
## 🎉   Subtasks

- [x] weekly syncs with Griff, Ata, Livia 
- [x] onboard Ata on everything TEC
- [x] review and support his work on whatever is needed 

## 🤼‍♂️   Reviewer

@GriffGreen
