### ISSUE TITLE
Update the Team Portion of the Website

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#221]
## 🎉   Subtasks

- [x] Talk about making Kris and Loie Advisors :-D 
- [x] Get headshots of the new members (Livia, Jess, Dan, Gus, Kris, Tamara)
- [x] Update the page on tilda

## 🤼‍♂️   Reviewer

@jessicazartler 

## 🔗   Work doc - inspirational links
commonsstack.org/team

**Comment by tamarandom** [comment]
@knobsdao and @tamarandom <-- send pics and links (twitter, linkedin, etc) to Kris!

**Comment by tamarandom** [comment]
@krisjpi [Here ya go!](https://docs.google.com/document/d/1vOCMBsse4u-tRjgymj3HHwAktcDotqk8WAJ7ky_jCCQ/edit?usp=sharing)

**Comment by krisjpi** [comment]
All team edits made - now onto larger site refresh.
