### ISSUE TITLE
Aragon Conviction Funding Report

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#226]
## 📋   Anything to add?
A short, data-driven report on the Conviction Funding pilot carried out by Aragon, with conclusions & suggestions for successive deployments of CV/CF.

## 🎉   Subtasks

- [ ] Z & Andrew pull data from CF pilot
- [ ] Data analysis in cadCAD
- [ ] Draft report, edit & publish
- [ ] Distribute report on Aragon forum, medium, twitter etc

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/13jGgNhKdwsvv4pwrelTOYOGR9NpdyjaI2Q0rcn192p0/edit?usp=sharing

**Comment by GriffGreen** [comment]
Data science driven analysis for CV
