### ISSUE TITLE
Propose (Iteration 1) Initial Roadmap 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#23]
## 📋   Description

Our fundraise is going to support the projects we need to build a foundation for Commons proliferation while also creating Commons to train our Trusted Seed.

## 🎉   Subtasks

- [x] Determine a strategy for funding our work while funding the specific tasks 
- [x] Create an ordered list 
- [ ] Get validation from our team and advisors on the order
- [ ] Validate Budget Assumptions
- [ ] Write detailed description for each one
- [ ] Organize on Giveth by category (cadCAD, CV, ABC, etc)

## 🤼‍♂️   Reviewer

@Kisgus 

## 🔗   Links
Working doc: https://docs.google.com/document/d/1Zd4qQT2x2CT52gniphcxm1rQLyCqPIqH5VcVXDINyvw/edit?usp=sharing

**Comment by lorelei1** [comment]
Griff got validation from the team, now it's time to move to advisors!

**Comment by lorelei1** [comment]
Griff task list:
- integrate team feedback on Iteration 1 roadmap
- with Zargham: ask how much money for cadCAD, and approval on roadmap (schedule a call for week of 9/14)
- with Luke/1hive: ask them how much generalized ABC will cost, and approval on roadmap (chat & make a call happen by 9/18)
- with Simon, Trent, Eden, Abbey and Jordi less crucial
- with Jeff: review cadCAD milestone

**Comment by lorelei1** [comment]
helpful to schedule regular 1 hour advisor meetings once/month

**Comment by Kisgus** [comment]
Hey @GriffGreen do you need any more help on this issue? Happy to review
