### ISSUE TITLE
cadCAD onboarding and organizing

### ISSUE THREAD

**Issue by seichris** [commons-stack/iteration0#231]
## 📋   Anything to add?

Currently, cadCAD is in a shift from blockscience to the community. To get towards a fully community-owned cadCAD, this needs work on the core dev side, in infrastructure/admin tasks, as well as outreach and education to get more people involved.

## 🎉   Subtasks

[This sheet lists all tasks](https://docs.google.com/spreadsheets/d/1CQ8_Iy-j2tw39l6pmSCAf-YFGK4dksigYtauoowSj0o/edit#gid=828917017). The next milestone is the release of the [blockscience labs](https://blocksciencelabs.com/), a collaborative modelling environment, simplifying the process around getting started with and coding cadCAD.

From those tasks, I started working on:

- [x] Read and watch all the stuff on cadCAD
- [ ] Outreach/Education: Help with Token Engineering workshop
- [x] Infra/Admin: Convert spreadsheet issues to public github issues
- [ ] Infra/Admin: Help with bridging chats and Twitter from and to the cadCAD Discord chat

## 🤼‍♂️   Reviewer

@ Jeff-Emmett

## 🔗   Work doc - inspirational links

We coordinate in the cadCAD channels for [Infra/Admin](https://discord.com/channels/722946313775480845/733036591588835399) and for [Outreach](https://discord.com/channels/722946313775480845/733040735712182324)

**Comment by GriffGreen** [comment]
Great issue @seichris! What do you expect to get completed in the next 2 weeks? We are setting up some sprints :-D

**Comment by seichris** [comment]
It's still hard to pin this down in an issue..

**Comment by Jeff-Emmett** [comment]
I think we could scope this issue to be "onboarding and organizing" the channels/boards/tasks/permissions needed to get started.  I have bridged the cadCAD Github board with the Commons Stack boards, so we can use the same processes of tracking associated tasks in epics and cross them off one by one.

**Comment by iviangita** [comment]
Copied to cadCAD Working Group repo [issue #30](https://app.zenhub.com/workspaces/cadcad-working-groups-5fc92eaaf15f6a00165ebe0d/issues/cadcad-org/working-groups/30)
