### ISSUE TITLE
Luna Swarm initialization - modelling 1Hive in cadCAD

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#235]
## 📋   Anything to add?
This initiative is to iteratively improve on & add to the Conviction Voting model produced for 1Hive/Aragon, to provide better operational decision support in the design & maintenance of the 1Hive $HNY token ecosystem.

## 🎉   Subtasks

- [x] Create overarching modelling manifesto & post on 1Hive forum: https://forum.1hive.org/t/luna-swarm-expanding-the-1hive-cadcad-model/1190
- [x] Schedule recurring call @Jeff-Emmett 
- [x] First proposal submitted to 1Hive Conviction Voting - for initial month of work

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
Modeling Manifesto
https://docs.google.com/document/d/1UkWflaDNh5aF8BeRUoIQx3g3z7P2mE0cU0N4dbwz4Sk/edit?usp=sharing

**Comment by GriffGreen** [comment]
I deleted Model off the issue to make it 2 weeks

**Comment by jessicazartler** [comment]
> I deleted Model off the issue to make it 2 weeks

I actually thought this is a whole epic in itself as there are many steps -- or we can break it down -- this sprint is about submitting a proposal to 1Hive DAO to get funding

**Comment by jessicazartler** [comment]
We had another meeting last week to discuss mission/method and started a spreadsheet to track contributors https://docs.google.com/spreadsheets/d/1k0ezsUvC4D2HmQJYlrv__pERxjWfC1Qc4_ZX84TuVuw/edit#gid=0

@Jeff-Emmett and I will work on writing the draft of the proposal to submit to 1Hive - and run it by Luke & Z before submitting. Luke will send us an ETH address for a Gnosis safe/escrow to submit and use as the address to receive funds. Luke will act as PM with some contributors and us supporting.
