### ISSUE TITLE
Finalize the 2 month contracts with Dan

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#236]
## 📋   Anything to add?

Same issue basically 3 times for Dan, Kris and Tamara

## 🎉   Subtasks

- [x] Dan writes lots of github issues
- [x] Dan and Griff schedule a call to talk about the contract 
- [x] Dan and Griff have the call
- [ ] Dan's Contract is shared with team fo veto
- [ ] Dan's Contract is revised if needed and then 

## 🤼‍♂️   Reviewer

@??????

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1njtH2jq3nCL8DlZ1K0o_WVxZptuepPv6nkTd5zKqdCs/edit
