### ISSUE TITLE
Finalize the 2 month contracts with Tamara

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#237]
## 📋   Anything to add?

Same issue basically 3 times for Dan, Kris and Tamara

## 🎉   Subtasks

- [x] Tamara writes lots of github issues
- [ ] Tamara and Griff schedule a call to talk about the contract 
- [ ] Tamara and Griff have the call
- [ ] Tamara's Contract is shared with team fo veto
- [ ] Tamara's Contract is revised if needed and then 

## 🤼‍♂️   Reviewer

@??????

## 🔗   Work doc - inspirational links

**Comment by tamarandom** [comment]
Well, I just finished the contract and sent to Griff for review before sharing with team for a vote! Very exciting start to my 4th week with you all! 😂
