### ISSUE TITLE
Finalize the 2 month contracts with Kris

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#238]
## 📋   Anything to add?

Same issue basically 3 times for Dan, Kris and Tamara

## 🎉   Subtasks

- [x] Kris writes lots of github issues
- [x] Kris and Griff schedule a call to talk about the contract 
- [x] Kris and Griff have the call
- [ ] Kris's Contract is shared with team fo veto
- [ ] Kris's Contract is revised if needed and then 
- [x] Kris's November Milestone is created
- [x] Kris's November Milestone is filled
- [x] Kris's November Milestone is paid out

## 🤼‍♂️   Reviewer

@??????

## 🔗   Work doc - inspirational links
