### ISSUE TITLE
Create a proposed roadmap to get to 2 more Field Test Commons

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#24]
## 🎉   Subtasks

- [ ] Create an ordered list 
- [ ] Get validation from our team and advisors on the proposed order (will always be able to be revised)
- [ ] Validate Budget Assumptions
- [ ] Write detailed description for each one
- [ ] Organize on Giveth by category (cadCAD, CV, ABC, etc)

## 🤼‍♂️   Reviewer

@Kisgus
