### ISSUE TITLE
Giveth Milestone Onboarding Party (recurring every month)

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#240]
## 📋   Anything to add?

Should happen around Dec 1st

## 🎉   Subtasks

- [x] Make doodle for a call with anyone who wants help making a Giveth Milestone
- [ ] Kris's November Github issues are set up
- [X] Tamara's November Github issues are set up
- [X] Dan's November Github issues are set up
- [x] Ata's November Github issues are set up
- [x] Ruben's November Github issues are set up
- [x] Chris' November Github issues are set up
- [x] AND KAT
- [ ] AND JAKE
- [x] Have the call

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
https://doodle.com/poll/cqcwcmtz859wedh9
