### ISSUE TITLE
Assist Kate in her work to strengthen our internal culture.

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#243]
## 📋   Anything to add?

We have a lot of new people coming into the team and we are about to double down on working with contributors... we are bound to end up with conflicts and such... It might be good to start working with Kate to create a conflict management system and start following the Ostrom Principles

## 🎉   Subtasks

- [ ] Make a milestone for Kate
- [x] Support Kate in working with the team
- [x] Set up all the 1 on 1 calls

## 🤼‍♂️   Reviewer

@????

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1TjyNtyCymaOyZYTPAVTJ0yFU2VYndpKqBQ31w_mmy00/edit?usp=sharing

Pdf Version exists if you want to see it :-D 
[Briefing for The Common Stack(1).pdf](https://github.com/commons-stack/iteration0/files/5477279/Briefing.for.The.Common.Stack.1.pdf)
