### ISSUE TITLE
Support Ata on the TEC Case Study

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#245]
## 📋   Anything to add?

@liviade1 please fill out plan for the sprint

## 🎉   Subtasks

- [x] Help him to plan the first steps for TEC case study 
- [x] feedback to data points
- [x] Interviews with Livia and Griff
- [x] feedback to the results of the interview applied to the data points 
- [x] Map the parts that need more input

## 🤼‍♂️   Reviewer

@GriffGreen
