### ISSUE TITLE
Hand off regular tweeting of CS twitter to people who have more bandwidth

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#247]
## 🎉   Subtasks

- [x] Make a plan for regular tweets from which accounts
- [x] Pick top trusted people 
- [x] Delegate tweeting responsibilities

## 🤼‍♂️   Reviewer

@???

**Comment by jessicazartler** [comment]
@krisjpi is our Twitter champion! Jeff and I will continue to support the efforts by creating and pushing content to Kris, and we will hold a one hour work session every week to team up to handle the distribution because it is such a HUGE job. Worked great today in our first one - thank you again Kris for taking this on and to the next level - we appreciate you!
