### ISSUE TITLE
Overhaul our Digital Security Management

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#249]
## 📋   Anything to add?

Kris... maybe you can fill this out a bit more... This is an epic so there are probably lots of small tasks

## 🎉   Subtasks

- [ ] Passwords - create a shared password management solution
- [ ] Get all team members access to passwords, create and implement password hygiene and intrusion processes.
- [ ] Create a general Commons Stack email account for setting up shared accounts/google drive. (communications@commonsstack.org)
- [ ] Ensure there is a way to share passwords with contributors who need it with either limited access to data or permissions.
- [ ] Create login details for our most used platforms within the password manager.
- [ ] Google drive - Migrate to a Google Drive on a shared account - limit to team access, and create a separate drive for documents used by contributors - more open access. Determine which folders/files can go to each location. Make the migration once so that no one loses work.
- [ ] youtube... may need more detail here
- [ ] 

Likely much more we can improve, feel free to add subtasks if there are security practices you don't feel comfortable with, and let's get it cleaned up!

## 🤼‍♂️   Reviewer

@

**Comment by jessicazartler** [comment]
Regarding Mail Chimp this is a BLOCKER
 We either need one access with no 2FA - or have to buy subscriptions with everyone to get 2FA

Also need to update access for Medium / YouTube / other channels

**Comment by tamarandom** [comment]
Closing this issue. 🧹 🕸️ 

@iviangita - you have taken this on so I want to put this old epic on your radar in case there is anything you need to pull out of here.
