### ISSUE TITLE
Calibrate Zenhub for better program, project and operations visibility 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#252]
## 🎉   Subtasks
For the 1st Iteration 
(Creating new issues for future iterations and improvements)
- [x] Get buy-in from Griff & Gus & all core team
- [x] Housekeeping for old milestones & epics
- [x] Implement first iteration : Board, Roadmap (depends on Epics)

## 🤼‍♂️   Reviewer

@
