### ISSUE TITLE
How to : Commons Stack PrimeDAO ambassador <-- do the needful

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#255]
## 🎉   Subtasks
- [ ] Find out what is the needful?
- [ ] Follow Ruben's telegram explanation
- [ ] Ask for help when I get lost
- [ ] Need an Epic name for these joint collaborations.

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
The proposal was submitted. Status is pending approval.

https://alchemy-2-xdai.herokuapp.com/dao/0xe3a89ed4956c4f7173418e4dec2a77a5f60807de/proposal/0xa877a4a2c40aff92b72fac202390d5af099961302618f597f868d90c6749ece7

**Comment by tamarandom** [comment]
Duplicate of #204
