### ISSUE TITLE
Check if Tokenlog is a good fit and if yes try and test it out 

### ISSUE THREAD

**Issue by Kisgus** [commons-stack/iteration0#256]
## 🎉   Subtasks

- [ ] Do spec with Wesley
- [ ] Set on timeline
- [ ] Go or no go

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links

https://tokenlog.xyz/compound-finance/compound-protocol
