### ISSUE TITLE
Pay out Giveth Milestones for New Contributors and New Core Team members

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#258]
## 🎉   Subtasks

- [ ] Kris's November Milestone is created
- [ ] Kris's November Milestone is filled
- [ ] Kris's November Milestone is paid out
- [ ] Tamara's November Milestone is created
- [ ] Tamara's November Milestone is filled
- [ ] Tamara's November Milestone is paid out
- [x] Dan's November Milestone is created
- [x] Dan's November Milestone is filled
- [x] Dan's November Milestone is paid out
- [ ] Ata's November Milestone is created
- [ ] Ata's November Milestone is filled
- [ ] Ata's November Milestone is paid out
- [ ] Ruben's November Milestone is created
- [ ] Ruben's November Milestone is filled
- [ ] Ruben's November Milestone is paid out
- [ ] Chris' November Milestone is created
- [ ] Chris' November Milestone is filled
- [ ] Chris' November Milestone is paid out
- [ ] KAT November Milestone is paid out
- [ ] JAKE November Milestone is paid out
- [ ] Griff November Milestone is paid out
- [ ] Gus November Milestone is paid out
- [ ] Livia November Milestone is paid out
- [ ] Jeff November Milestone is paid out
- [ ] Jess November Milestone is paid out

## 🤼‍♂️   Reviewer

@iviangita
