### ISSUE TITLE
TEC Diagram Drafts

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#260]
## 📋   Anything to add?
Transcribing Griff's TEC diagrams into Lucidchart for a designer to take & run with

## 🎉   Subtasks

- [x] Draft diagrams for TEC in Lucidchart: https://lucid.app/lucidchart/invitations/accept/a906f2ef-dbbb-43b4-9578-fd303f8a48d2
- [ ] Approval round with Griff
- [ ] Hand off to designer

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://lucid.app/lucidchart/invitations/accept/a906f2ef-dbbb-43b4-9578-fd303f8a48d2

![image.png](https://images.zenhubusercontent.com/5cae1c1852320c5dff5b4586/c6b8b6b0-6373-462d-8e70-3b2358f5a3f2)

**Comment by jessicazartler** [comment]
This goes with this TEC issue https://github.com/TECommons/coordination/issues/64

**Comment by Jeff-Emmett** [comment]
Jess and I looked at this diagram again, and came to the conclusion that Marko can work off of your Hatch diagram produced in past google slides presentations.

**Comment by GriffGreen** [comment]
https://docs.google.com/document/d/1UI6FOkKatNCRNNSffCHaoNb87mJzQh9dCJAFK4UIg4M/edit?usp=sharing


https://docs.google.com/document/d/1v8rCByLYQrpyaLRXW5v0ZSPD5gecu-G1B99FMrcnSOw/edit#

**Comment by Jeff-Emmett** [comment]
https://miro.com/welcomeonboard/zqrRKAJYgFZU98DvkFiGGBYljrI6Rv5LsYSCLSMKXE1RyTpnPkI7nJ15ijXujmqt

**Comment by GriffGreen** [comment]
![Screen Shot 2021-02-15 at 1.48.41 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/f9d42de9-8b43-448f-8ac3-ee3bb71b8fdd)
