### ISSUE TITLE
Finalize Social Workflow in Github

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#263]
## 🎉   Subtasks

- [ ] Sort out social streams into GH issues
- [ ] Integrate sign-offs
- [ ] Grabbing notion links for each issue

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Notion?
