### ISSUE TITLE
Kickoff Partnerships Process

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#264]
## 🎉   Subtasks

- [x] Setup Brainstorming Work Session.
- [x] Gather documentation / inspiration docs.
- [x] Sync with TEC efforts

## 🤼‍♂️   Reviewer

@Jeff-Emmett @GriffGreen

**Comment by jessicazartler** [comment]
Yay! We had a meeting and are working from Establish a D2D partnership template for the communities related to Commons Stack#288
