### ISSUE TITLE
Create a method to accept fiat (if needed)

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#27]
## 📋   Anything to add?

Accepting fiat seems like a no brainer if we don't have to hold it. To hold fiat (likely in EUR, CHF and USD) requires cooperating with banks in Switzerland and is often difficult for crypto-focused organizations, but using a partner like Moonpay, Wyre, and/or Bity are all very accessible.

## 🎉   Subtasks

- [ ] Validate assumption that this is needed. Has anyone asked to Donate in fiat?
- [ ] Decide on Fiat onramp approach and whether we pursue a non-profit partner
- [ ] Fill this issue out with the rest of the plan

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by Kisgus** [comment]
Im not really sure how to go about this issue in terms of "validate the assumption". Who makes a decision if this is needed @GriffGreen, @krrisis, @jessicazartler ?

If we decide to do it it does not have to be harder than:

1) create a button that says donate
2) link to moonpay widget
3) get API key and test on testnet
4) go live

**Comment by krrisis** [comment]
see issue #31

**Comment by lorelei1** [comment]
Will fiat donors get CSTK? How do we link their fiat donation (which I assume comes to us in crypto from an address owned by Moonpay) to their ethereum address to hold CSTK?

**Comment by krrisis** [comment]
Good point :) I would say people who donate in fiat do not get any cstk tokens, it gets really complicated and a lot of follow-up otherwise. In general I would advise against this if it takes too much time, our desired audience lives & breathes crypto. If it's easy to set up we could add it, but I wonder if there are legal repercussions if we have a fiat moneystream embedded on our website.

**Comment by krrisis** [comment]
@Kisgus @GriffGreen has said we can go ahead with this so I will create that button, let me know what link to put under this and what else you need.

**Comment by Kisgus** [comment]
I think only people that apply and get accepted has the option to get CSTK in the first place. If I donate with credit-card and put in an email that matches the email I was accepted to the Trusted Seed with I guess one could get CSTK this way.

I guess accepting FIAT is also relevant for a) tokendapp (namely to automitze the issuance of CSTK) as well as b) Giveth in general. I think it makes sense to have a comprehensive plan for this. 

Anyways I have created a room with Moonpay guys now to start this discussion
