### ISSUE TITLE
Revise Tweet for sharing after people have paid their membership dues

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#287]
## 🎉   Subtasks

- [x] Review CSTK Fundraising app on Figma
- [x] Define targetting.
- [x] Draft some messages.
- [x] Tried Octalysis on the messaging draft.
- [x] Have messages reviewed.
- [x] Tune messages if needed.
- [ ] Review again if needed and ship.

## 🤼‍♂️   Reviewer

@katzcaban 

## 🔗   Work doc - inspirational links
https://www.figma.com/file/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?node-id=1285%3A2733
Octalysis flow: https://www.notion.so/CSTK-Token-DApp-Tweets-01c8c56fb95d4ab0b20a5e79f17a84a7

**Comment by knobsdao** [comment]
Still have some ideas to polish intention/CTA but here's the draft of three tweets based on the "Why CSTK Tokens?" list:

I've just contributed to advancing the development of the toolkit that will ensure public goods sustainability! 🎉🌱🌌✌🏻 Contribute here: "link for others to contribute"

I've just committed to stewarding the development of the toolkit that will ensure public goods sustainability! 🎉🌍🌌✍️ Join me: "link for others to contribute"

I've just become a member of the Swiss Commons Stack Association! 🎉🌍🌌🎩🥂 Join us: "link for others to contribute"

🌱🎉🌍🌌✌🏻🎩✍️🥂

**Comment by tamarandom** [comment]
Griff to review.

**Comment by GriffGreen** [comment]
I like:

I've just become a member of the Commons Stack's Swiss Association! 🎉🌍🌌🎩🥂 Join us: commonsstack.org/apply

**Comment by knobsdao** [comment]
Awesome @GriffGreen! Better order. Capitalized "the". 

I've just become a member of The Commons Stack's Swiss Association! 🎉🌍🌌🎩🥂 Join us: commonsstack.org/apply

**Comment by GriffGreen** [comment]
I've just become a member of the Commons Stack's Swiss Association! 🎉🌍🌌🎩🥂 Join us: commonsstack.org/apply

I removed the "the"
