### ISSUE TITLE
(Iteration 2) Calibrate Zenhub for better program, project and operations visibility

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#292]
## 🎉   Subtasks

- [ ] Zenhub Roadmap : Separate roadmap for separate TEC and CS workspaces. 
- [ ] Updates github orientation page (include Zenhub link : https://github.com/commons-stack/iteration0)
- [ ] Non-closable template for repeating tasks

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Closing! 
1. Roadmapping in Miro board is working quite well.
2. The github page was updated by @GriffGreen last month :pray_tone3: 
3. #repeating label is working quite well.
