### ISSUE TITLE
Review the members of the Commons Stack Association

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#302]
## 🎉   Subtasks

- [x] Lorelei is still currently a member... not sure if we should keep that or not
- [x] Is Coach B's correct address holding a CSOM token?
- [ ] Add Kris & Livia to the CSOM token holders
- [ ] Do a board meeting

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by krisjpi** [comment]
This will all take place at the next Annual General Meeting in early January.

**Comment by GriffGreen** [comment]
Should we add Dan or anyone else?
