### ISSUE TITLE
Make a Commons Stack Association Campaign on Giveth

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#303]
## 🎉   Subtasks

- [x] Decide if we do a Campaign or a DAC
- [x] Create a very short and sweet message for the Campaign that is approved by Coach B (maybe out of the terms)
- [x] Make a new campaign that has that message in it (Griff must do)

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://beta.giveth.io/dacs/5cffd214f0fcb951b8e2bc87

**Comment by tamarandom** [comment]
Passed to @GriffGreen for review.

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6
