### ISSUE TITLE
Figure out the rules for how we need to use Commons Stack Association funds

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#304]
## 🎉   Subtasks

- [x] Ask Coach B
- [x] Make sure it is part of #303
- [x] Confirm AML requirements!
- [x] Legal Contracts from Lorelei

## 🤼‍♂️   Reviewer

@krisjpi
