### ISSUE TITLE
send emails to job applicants

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#307]
## 🎉   Subtasks

- [x] draft email and get feedback from Kris and Dan 
- [x] find the people that haven't been emailed yet
- [x] email everyone that is remaining 

## 🤼‍♂️   Reviewer

@
