### ISSUE TITLE
get ready for 1 more hire.... Fundraising lead!

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#308]
## 🎉   Subtasks

- [ ] Make a job description 
- [ ] post in the website
- [ ] promote it on all comms channels 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
See #914 for more details
