### ISSUE TITLE
Twitter Content Weekly Scheduling of tweets! 

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#309]
## 📋   Anything to add?
Create a new issue per sprint!

## 🎉   Subtasks

New content
- [ ] Year end wrap, happy new year - link year summary call
- [ ] 
- [ ]

post link - check when posted
- [ ] Algorithms as Policy - Z RT - https://twitter.com/mZargham/status/1338971194939338752
- [ ] 
- [ ] 
- [ ]

Aligned content
- [ ] Token Economies thread: https://twitter.com/AlimKhamisa/status/1346838612579643392
- [ ] Metagame MetaSys: https://twitter.com/MetaFam/status/1341096993859510281 and/or https://metagame.substack.com/p/meta-42-metasys-kicking-off-the-year
- [ ]
- [ ]

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Friday sesh where we schedule tweets!

**Comment by liviade1** [comment]
What about having a moment in the contributors call for them to add one topic to the twitter content list of the week? Too much extra work? 
otherwise we can take the for contributor label out
