### ISSUE TITLE
Donation/Contribution landing page

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#31]
## 📋   ITERATION A OF DONATE/CONTRIBUTION PAGE

We are updating our contribution page with content / analytics to improve the accessibility and cut down blockers to accepting donations and diversify the currencies we accept

## 🎉   Subtasks

- [x] Kris & Griff to review landing page before wed 
- [x] Verify & set up fiat option 
       From Gus: The steps are:
       1) I create a group with you and Moonpay here
       2) You get API key access
       3) implement some small frontend code (should not take more than a few hours to have it ready for production)
- [x] sign off on final version of doc by kris & griff
- [x] change apply to contribute on page (kris) and create donation page on tilda (kris)

## 🤼‍♂️   Reviewer

@krrisis 
@jessicazartler 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1LDHO37lLnoLG71i6OTY52_LrlRRiFj6Irmg5DAz0QDE/edit

**Comment by krrisis** [comment]
Open Qs/feedback - to discuss with @markoprljic : 

Temp page: http://commonsstack.org/donate 
- biggest oppen issue: apply vs donate button top
- reduce text to a minimum 
- QR codes with cs logo in it 
- no subheaders
- Push text to end of page

**Comment by krrisis** [comment]
- homepage add donate button top right
- @markoprljic to create mockup and send to kris 
- optimize donation flow through giveth dapp - kris to add copy 
- kris to add text to thank you message of of application form 'if you haven't already donated... ' see #67

**Comment by markoprljic** [comment]
![Donate](https://user-images.githubusercontent.com/5704285/91226078-d533c480-e724-11ea-99b5-32849e4a7b89.png)
@krrisis Here's the mockup. You can also preview it here https://www.figma.com/proto/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?node-id=1288%3A1&viewport=386%2C338%2C0.3892725110054016&scaling=min-zoom

cc/ @GriffGreen

**Comment by krrisis** [comment]
Live: http://commonsstack.org/donate

**Comment by krrisis** [comment]
Adding QR color codes for future reference.
Made with https://www.qrcode-monkey.com/#bitcoin

Color 1: 0047B0
Color 2: 23E126

BG 000000
