### ISSUE TITLE
Pre-Launch Checklist

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#310]
## 🎉   Subtasks

- [x] T&Cs are confirmed
- [x] Statutes confirmed and signed
- [x] CSTK Token DApp FIGMA reviewed
- [x] Write out explicit AML requirements for the Membership Fees (Chat with B to get it)
- [x] Assn Member check (advice process - Message in the team channel, individual messages as well) #302 
- [x] CS Assn Campaign text on Giveth Approved - make a draft, run it by coach B)
- [x] Try to get Raph and Patrick to apply to the Trusted Seed 
- [x] CSTK Token DApp reviewed (in a dream world it would be Raph as our first user :-D)
- [ ] Write out explicit AML requirements for the Hatch

## 🤼‍♂️   Reviewer

@santi
