### ISSUE TITLE
Update cadCAD Linkedin to direct to active channels

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#318]
## 📋   Anything to add?

 let's add an issue to our medium term socials plan to get our Facebook and LinkedIn pages with a couple of posts and redirects to our more active channels, at the least. Starting to see some traffic (e.g. on Facebook) from some folk engaging in discussions on the P2P foundation

@krisjpi can you take this on?

## 🎉   Subtasks

- [x] Update CS Linkedin
- [x] Update cadCAD Linkedin
- [x] Update CS Facebook
- [ ] Any others @Jeff-Emmett @krisjpi ?

## 🤼‍♂️   Reviewer

@Jeff-Emmett

**Comment by liviade1** [comment]
I think updating our social pages shouldn't be labeled for contributors because requires login info. So I'm removing for contributors label of this one

**Comment by jessicazartler** [comment]
Going to get Peter (Heater) into our Github to take this on - sent msg in Core Team Discord to ask for permission/add him

**Comment by phacker3** [comment]
Hey all! I've updated the cadCAD linkedIn w/ community links (discord, telegram, twitter, forum) and added re-directs to CS and BlockScience LinkedIn pages.

Feel free to ping me if there's anything I missed!

**Comment by jessicazartler** [comment]
Whoop whoop! Thank you so much @phacker3 !!!! Closing
