### ISSUE TITLE
Create a "We have received your application" auto email for TS App

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#325]
## 📋   Anything to add?

Part of #242
There is a drop off right now in the flow or a not that great auto mail - we need an acceptance mail so people aren't wondering what happened with their application

Maybe something like "Thank you so much for submitting your application to the Trusted Seed! We are currently reviewing your application and will respond as soon as we can. Meantime, join our Telegram https://t.me/CommonsStack (Discord soon) and feel free to introduce yourself! You can also follow us on Twitter @CommonsStack for the latest news & updates"

Something like this -- any other CTAs until we respond?

## 🎉   Subtasks

- [ ] Write draft @krisjpi 
- [ ] Create template with a graphic @krisjpi @knobsdao 
- [ ] Put on auto send :D @knobsdao 

## 🤼‍♂️   Reviewer

@krisjpi @Jeff-Emmett @jessicazartler

**Comment by knobsdao** [comment]
This is what people are currently getting from Typeform:

Subject: Typeform: Thank you for filling out ______

> Hello _____,
> 
> We’ve received your submission. The Commons Stack team will review your application and get back to you.
> 
> Thank you very much & have a nice day!
> 
> Below you can find your answers: 
> __
> __
> __

Note: I added info@commonsstack.org in the Reply To field.

**Comment by jessicazartler** [comment]
@krisjpi we forgot to do this on our last newsletter run -  do we want to do this during this sprint? I think it wouldn't take more than one hour.. up to you guys

**Comment by knobsdao** [comment]
Drafted a new Typeform auto-reply. Can't hyperlink there, so it looks longer, but is a fix until we automate! Added myself as the human-touchpoint. Check it: @krisjpi @Jeff-Emmett @jessicazartler 

Subject: Thank you for filling out your Commons Stack Member Application Form!

> Hello [NAME],
> 
> We’ve received your application! The Commons Stack team will review it and get back to you.
> 
> If you are eager to contribute ASAP, you can:
> 
> - Claim an issue on our Github: [https://github.com/commons-stack/iteration0/labels/For Contributors](https://github.com/commons-stack/iteration0/labels/For%20Contributors)
> - Offer your support in our Telegram channel: [https://t.me/CommonsStack](https://t.me/CommonsStack)
> - Donate: [https://commonsstack.org/donate](https://commonsstack.org/donate) (please notify us!)
> - Or ask Dan for guidance: [https://t.me/knobsDAO](https://t.me/knobsDAO)
> 
> Thank you very much, and have a nice day!
> **The Commons Stack**
> 
> Below you can find your answers:
> [All answers]
