### ISSUE TITLE
Review Orbit for community engagement

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#327]
## 📋   Anything to add?

(carry over from #242)

Orbit might be useful for taming the flow: https://github.com/orbit-love/orbit-model

## 🎉   Subtasks

- [x] Review Orbit Documentation
- [x] Connect Orbit to Github (TEC/CS)
- [x] Connect Orbit to Twitter? (TEC/CS)
- [x] Connect Orbit to Discourse (TEC) 

## 🤼‍♂️   Reviewer

@

**Comment by knobsdao** [comment]
@krisjpi After login with Github, you should be able to connect Twitter and Discourse to the TEC Orbit, [here](https://app.orbit.love/tec/activate). And to the CS Twitter, [here](https://app.orbit.love/cs/activate). Ping me if anything.

**Comment by krisjpi** [comment]
@knobsdao I don't have high enough permissions in Orbit to add the integrations - lets sync and close this issue! Should only take a couple of minutes :)

**Comment by knobsdao** [comment]
@krisjpi I just made you an Owner inside the app; my bad I missed that. You should be able to do the integrations now. I'll take over after that!

**Comment by krisjpi** [comment]
All of these connections have now been made and integrated in Orbit!
