### ISSUE TITLE
FINAL EDITS on Frontiers Journal "Global Commons" Paper Submission

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#341]
## 📋   Anything to add?
Unfortunately this paper came back from near-completion with a few final changes requested by the editor.  Hopefully we can finalize everything this sprint!

## 🎉   Subtasks

- [x] Meet with author team to discuss strategy
- [x] Respond to Leanne and open collaborative document
- [ ] Coordinate and draft edits
- [ ] Editing process for re-submission
- [ ] DONE FOREVER! 🍾

## 🤼‍♂️   Reviewer

@mzargham 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1zW4D57AkY0yfVmWccF0Aw8dT4oRWbgUGgryVcfkalOQ/edit#heading=h.a7tm5sbr2zti
