### ISSUE TITLE
Onboard community contributors to praise process

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#343]
## 📋   Anything to add?
Praise is probably a good entry point for eager contributors in our community - and how better to recognize contributions on the edges of our community network!

## 🎉   Subtasks

- [x] Create simple onboarding for contributors to the praise process.
- [ ] Identify active contributors
- [ ] Grant the power!

## 🤼‍♂️   Reviewer

@GriffGreen @knobsdao

**Comment by knobsdao** [comment]
Maybe set a baseline requirement for this, like being active for an x amount of time, in some key tasks/ways/aspects, or being featured in a certain way previously/currently during praise. More for context than anything else, so better insight can be given to the quantification.

**Comment by krisjpi** [comment]
Let's prioritize this for the next sprint if possible - onboarding praise givers on Discord would be awesome!
