### ISSUE TITLE
Partnerships Inbound - Webpage for partners / typeform

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#351]
## 📋   Anything to add?

Need a page on our site for inbound partners

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey @jessicazartler! Doing backlog refinement with @usama9500 and I think we can close this issue, right? Is there any reason to keep it open?

**Comment by jessicazartler** [comment]
![partners](https://user-images.githubusercontent.com/43972522/157682114-17c9425e-c80e-4335-bfa6-b926bb2b1b58.png)

@tamarandom I just looked on the site and I would suggest adding more - standard is usually 8-12 logos (looks a little lonely and insular with 2). 

We can immediately add:
- [ ] Regen Network 
- [ ] ixo (https://www.ixo.world/)
- [ ] 1Hive
- [ ] TEC
- [ ] Token Engineering Academy
- [ ] cadCAD

... and could discuss if you would want to leave it at 8 or expand to 12... If 12 could consider:
- [ ] https://positiveblockchain.io/
- [ ] MetaGame
- [ ] Bloom Network
- [ ] Panvala
- [ ] Gitcoin (would need to just ask to make sure)
- [ ] Project Ark or NFT Impact Alliance
- [ ] RMIT Blockchain Innovation Hub (would need to ask Kelsie) or some other 

Others that represent the variety of work / vision that CS represents and wants to align with visually? Perhaps looking at the Trusted Seed membership catalogue to represent some of our TS folks orgs / that would be a nice value add for them
