### ISSUE TITLE
Announce Conflux Partnership

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#359]
## 📋   Anything to add?

Our partnership with Conflux is official thanks to Jeff's intro & our call with them! And they have asked us to help co-write a press release that they can publish a medium article on and send out for publication

## 🎉   Subtasks

- [x] Camilla w/ Conflux does first draft
- [x] Jess edit / write quote / co-write
- [x] Camilla finalize and send out
- [x] Jess and @krisjpi distribute and Tweet about it

## 🤼‍♂️   Reviewer

@knobsdao @krisjpi @GriffGreen @Jeff-Emmett 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1Rw76xfa4bW0vC-xXDBIkosh8ELK2qV-rdWuPjL7HVGQ/edit?ts=5fcac228#

**Comment by jessicazartler** [comment]
MEDIA MENTIONS AS A RESULT:
https://twitter.com/Conflux_Network/status/1336358013914017795?s=20
https://aithority.com/technology/blockchain/conflux-network-and-commons-stack-partner-to-accelerate-growth-for-decentralized-communities/
https://www.fxwrite.com/conflux-network-announces-partnership-with-the-commons-stack/
https://www.cryptoninjas.net/2020/12/08/conflux-network-and-commons-joins-forces-to-accelerate-growth-for-decentralized-communities/
