### ISSUE TITLE
Social Media content 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#36]
## 📋   Anything to add?

Content that still needs to be shared on Twitter and in our telegram chat for retweets 

## 🎉   Subtasks

- [x] Metacartel Cadcad workshop [recording](https://www.youtube.com/watch?v=kyuSWD4CxOQ)
- [x] Everything that is still in the [sheet](https://docs.google.com/spreadsheets/d/1S8Au_Q2nSt8WehNGRnJBdkhSAA4LAjpn6XUgxoXdsJA/edit#gid=0)
- [x] Cadcad community call vid + workshop - will be tweeted by cadcad
- [x] Accelerator initiative (after copy check)
- [x] Research roundup, was 2 actually tweeted - tweet the playlist

## 🤼‍♂️   Reviewer

@Jeff-Emmett 

## 🔗   Work doc - inspirational links
https://docs.google.com/spreadsheets/d/1S8Au_Q2nSt8WehNGRnJBdkhSAA4LAjpn6XUgxoXdsJA/edit#gid=0
