### ISSUE TITLE
Rethink Praise and incorporate Discord praise bot

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#360]
## 🎉   Subtasks

- [ ] Fix internal accounting for praise to handle both discord and Telegram (work with griff)
- [ ] Figure out how we can openly quantify praise without connecting it to someone's ETH Address
- [ ] Make a blog post explaining the praise plan

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by GriffGreen** [comment]
Important thoughts:

We need to tell people when they got tokens. 
- discord bot
- tracking where they are in the process



Openly quantify praise
- Do it in a discord channel?
- make a cal invite
- make a public sheet
- make it clear in the blog post that we are doxing everyone


Standardize how we quantify praise
- Kris finishes faster because of his great standard... but its normalized


Praise in discord and telegram
- we need to start collecting discord handles
- we need to match Discord to ETH address and Telegram handles (add to hubspot too!)


Add more Dishers! (What are the parameters)
- pretty easy
- active contributors
- Requires training

Rotate in Community members to be CSTK Quantifiers
- Absolutely! 
- Invite the high CSTK winners (top 5ish in the last rounds)

Standardizing how quantifiers get rewarded
- Average per praise
- Do we subtract a % for full time people?
      - No CSTK is a different thing than IH in TEC

Dishing praise to ourselves is not in our culture! 
- let's change it! 

Dishing praise for dishing praise!
- Make a column that counts someones praises and award a certain amount of CSTK for everyone that dishes (Griff can Implement) 

Dishing praise to ecosystem partners more often.
- Making a list of awesome that we want to have CSTK tokens and dish them praise on the reg for the awesome shit they do.

Praise Testing Channel!
- invisible 


**We need a blog post to update praise!**
- Addresses are identity and bank accounts
- Talk about the praise past
- talk abut the new praise updates!
- Discord, open praise, praise yo self. 
- How to claim :-D (apply to trusted Seed, pay membership dues)
- How to get the power...

**Comment by knobsdao** [comment]
What's the key data when showcasing praise progress? # of total/monthly praises, # of recipients, # of CSTK dished?

**Comment by tamarandom** [comment]
Closing this Epic. The work that @kristoferlund is doing with Praise as an open source system addresses it.
