### ISSUE TITLE
Share our review call

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#371]
## 📋   Anything to add?

[Dec 23 Year End Review call 
](https://www.youtube.com/watch?v=PGaT0eWBKk8)[Dec 10 Sprint 4 Review call 
](https://www.youtube.com/watch?v=675QjO_aat0)

[YouTube Playlist](https://www.youtube.com/playlist?list=PLy6j39s17_jR9Sn10HFY-aoS-dSIWD1GL)

## 🎉   Subtasks

- [ ] Craft comms based on the model
- [ ] Share on Discord
- [ ] Share on Telegram

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
- [Draft model for review share](https://docs.google.com/document/d/1RReaP-nEYRWVnH1NLb6C_4Itb5WG-6bx7FMZa3BhlWg/edit).

**Comment by tamarandom** [comment]
@knobsdao the Sprint 6 review call is live! Here's the link : https://www.youtube.com/watch?v=PxOUIWjqQPQ

**Comment by tamarandom** [comment]
@knobsdao The Sprint 7 review call is live! Here is the link : [https://www.youtube.com/watch?v=U2P3Xqn423M](https://www.youtube.com/watch?v=U2P3Xqn423M)
CC @iviangita

**Comment by GriffGreen** [comment]
@krisjpi do you have a link to the Praise study?

**Comment by knobsdao** [comment]
Created a [model draft](https://docs.google.com/document/d/1RReaP-nEYRWVnH1NLb6C_4Itb5WG-6bx7FMZa3BhlWg/edit) for the comms of the share in Discord/Telegram and included it in the description above.

**Comment by YineisyM** [comment]
Here's the current doc where we are working this task: https://docs.google.com/document/d/1uKuKG4rXciiAPsqVLhf7u_c1UldVQ-kH1XsKCH4vBJ0/edit?usp=sharing
