### ISSUE TITLE
Support Felix in Publishing the CS Case Study (and eventually distribute)

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#376]
## 🎉   Subtasks

- [ ] Finalize language around iterations
- [ ] Publish to ResearchGate or other 
- [ ] Distribution campaign on behalf of CS comms

## 🤼‍♂️   Reviewer

@jessicazartler @krisjpi 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1NdZMBbLROVBXtuqpkLkdPDwu0CN_zE_1e_7bQakxWRE/edit?ts=5fb5a33c#

**Comment by Jeff-Emmett** [comment]
Felix published! 
 https://www.researchgate.net/publication/347390484_The_Commons_Stack_Realigning_Incentives_Towards_Public_Goods_Case_Study
