### ISSUE TITLE
CS Trusted Seed to TEC IH holders/non-holders

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#380]
## 📋   Anything to add?
The issue sparked from the MailChimp to HubSpot migration #378 and is now focused on communicating to CS TS on opting into TEC comms.

## 🎉   Subtasks

- [x] add some additional historical details
- [x] Clean up MC data sets

- [x] Double-check data integrity x2-3 times
- [x] Create TS IH Holders List in HubSpot
- [x] Create TS Applicants and TS Members Lists in HubSpot (blocker for sending newsletter/applicant emails)
- [x] Draft TS IH Holders Email Campaign
- [x] Create the campaign in HubSpot.
- [x] Review Email Campaign w/CS Comms
- [x] Send Emails!

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
Campaign draft: https://docs.google.com/document/d/1dduKeUsDhi1B6ZLDHMyXAsT-qyxD_sbNoqpMsigDV8s/edit

**Comment by tamarandom** [comment]
Update : Ok to send to the Trusted Seed emails to inform those that have IH that they have IH and allow them to opt-into TEC communications and, importantly, (hard requirement!) ask if we can share their email and ethereum address with TEC.
