### ISSUE TITLE
Refine TS application emails

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#384]
## 📋   Anything to add?
Update the current TS app emails. Add more clarification on where the applicant is in their TS journey, provide a human-touchpoint for any questions/guidance.

## 🎉   Subtasks

- [x] Review current email templates
- [x] Hack on upgrading/updating them
- [ ] Review and ship

## 🤼‍♂️   Reviewer

@GriffGreen @krisjpi

**Comment by knobsdao** [comment]
Draft here: https://www.notion.so/TS-Application-Emails-891c7d2a9d134886b9c0ebc6048d28de

**Comment by GriffGreen** [comment]
Has my 👍

**Comment by knobsdao** [comment]
Could be further refined later on and according to refinements in the community member journey.
