### ISSUE TITLE
Trusted Seed Applicants Review

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#392]
## 📋   Anything to add?

Recurring task to accept new Trusted Seed applicants.

## 🎉   Subtasks

- [x] Assign Trust Scores
- [x] Prepare data to be uploaded to the CRM
- [x] Take care of any duplicates #551
- [x] Upload data to CRM and prepare emails by type of contributor (time and funds/both)
- [x] Update Registry https://blockscout.com/poa/xdai/address/0x73e7427428f6C77C180d17F48909780c839954a7/write-contract #644
- [x] Send emails
- [x] Send custom 1-1 emails / messages when necessary

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by GriffGreen** [comment]
Taking this week off... getting the infrastructure settled!

**Comment by usama9500** [comment]
Moved to Trusted Seed Repo: https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/103
