### ISSUE TITLE
TEC Hatch Agreements

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#394]
## 📋   Anything to add?

Part of Soft Gov agreements

## 🎉   Subtasks

- [ ] Make a bullet point list
- [ ] Get it reviewed by Santi
- [ ] Flesh it out into a forum post?
- [ ] 

## 🤼‍♂️   Reviewer

@santi

**Comment by santi** [comment]
I think you got the wrong Santi here... 

@GriffGreen or somebody else, could you change your template to be more precise about who to tag in these issues?

**Comment by iviangita** [comment]
Copied to TEC Coordination Workspace [issue 217](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/217)
