### ISSUE TITLE
Work with Ravi and Marko to agree on a Roadmap

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#40]
## 📋   Anything to add?
Marko is rethinking the overall design and this will have a huge impact on the roadmap... that said, we started an initial doc and I am excited to revise it once we have more complete designs

The cadCAD roadmap is very well defined, but the rest is dependant on the Designs

## 🎉   Subtasks

- [x] Start initial doc
- [ ] Schedule a roadmap sesh with Marko & Gus
- [ ] Get roadmap into github issues in Commons Simulator Repo

## 🤼‍♂️   Reviewer

@Kisgus 

## 🔗   Work doc - inspirational links

cadCAD roadmap: https://github.com/commons-stack/coodcad/issues/10

Initial Roadmap Doc: https://docs.google.com/document/d/1oSUkW5IDRmkrLcNNwp1vfLNIU0yH5JqsmLxpMB-OuJY/edit?usp=sharing

Initial Design: https://www.figma.com/proto/cuFTOOajO4aouz4SLnIINz/Commons-Simulator?node-id=557%3A3556&viewport=-434%2C66%2C0.2207019180059433&scaling=scale-down-width

**Comment by GriffGreen** [comment]
Ravi is no longer working on the project, Marko is on top of the Designs and that will define the roadmap

**Comment by Kisgus** [comment]
Setting up call with Marko
