### ISSUE TITLE
Prepare zenhub board for next Sprint 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#401]
## 🎉   Subtasks

- [ ] Add "Next sprint" label to all issues under "Sprint Backlog", "In progress", "Review", Blocker
- [ ] Move all to Product Backlog
- [ ] Create a new milestone

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Closing for this sprint :)

**Comment by tamarandom** [comment]
Hey @iviangita ! Zenhub just released new features that automates a few of these preparation we have been doing. Yay! We can test them out together in the next 2 sprint closes!

**Comment by tamarandom** [comment]
Closing older issues.
