### ISSUE TITLE
TEC Vision Mission & Values Mini Case Study

### ISSUE THREAD

**Issue by ataberkcasur** [commons-stack/iteration0#425]
## 🎉   Subtasks

- [x] get it ready for review

- [x] Reviewed by Griff  
- [ ]  Edit
- [ ] Reviewed by Livia
- [ ] Edit
## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1AOKI6B7UOJbKhLvWVYxI92u2duXtUvF5riwl639SHac/edit?usp=sharing

**Comment by ataberkcasur** [comment]
@GriffGreen @liviade1 need your reviews!

**Comment by tamarandom** [comment]
****
