### ISSUE TITLE
September Monthly Newsletter 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#43]
## 🎉   Subtasks

- [x] Jess to decide on outline/structure with Jeff/Griff
- [x] Jess to collect info for first draft 
- [x] Jess to write draft & submit to Lo/kris/Griff/Jeff for review
- [x] Jess/Jeff to create a bullet pointed version for the Trusted Seed telegram channel
- [x] Jess/Jeff newsletter version to input in Mailchimp
- [x] Test sends + final sends 

## 🤼‍♂️   Reviewer

@Lorelai @Jeff-Emmett @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1EazaOSxbIkqi8tpU-fOtpZ7bZuBslFa2gXiZ2mYjR9c/edit?usp=sharing

**Comment by jessicazartler** [comment]
Jeff and I picked up this task and sent for September. Will make a new issue for October newsletter currently underway. 
Thanks!
