### ISSUE TITLE
Test Octalysis Framework for the Trusted Seed

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#433]
## 🎉   Subtasks

- [x] Review Octalysis Framework
- [x] Compile documentation on TS current onboarding and engagement
- [x] Draft a 2x2 Octalysis player matrix
- [x] Draft Community Member Journey Map [Desired Actions + Win States]
- [x] Draft Feedback [Vehicles + Mechanics + Triggers]
- [x] Draft Incentives and Rewards
- [x] Review

Additional steps if given a go (may turn into issues):
- [ ] Community Member Journey [Desired Actions + Win States] Strategy
- [ ] Feedback [Vehicles + Mechanics + Triggers] Strategy
- [ ] Incentives and Rewards
- [x] Community Member Journey Hack Sesh
- [ ] Power/Ease Hack Sesh
- [ ] Desired Actions Hack Sesh
- [x] Rewards Hack Sesh
- [ ] Levels and Achievements Hack Sesh
- [ ] Ongoing review for wireframming and tech + comms

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
[Primer on Octalysis Framework](https://yukaichou.com/gamification-examples/octalysis-complete-gamification-framework/)
[MetaGame's Mention to Octalysis](https://metagame.substack.com/p/meta-40-forking-the-society)
[DADA's adaptation for the Invisible Economy](https://miro.com/app/board/o9J_kiimivw=/)
