### ISSUE TITLE
Should we add someone from the outside to join the CSTK issuance Multisig? 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/iteration0#436]
## 🎉   Subtasks

- [ ] host a conversation about this 
- [ ] list pros and cons 
- [ ] if pros are prominent contact the Trusted Seed member who will be invited to join 

## 🤼‍♂️   Reviewer

@
