### ISSUE TITLE
Migrate Mailchimp contacts

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#44]
## 🎉   Subtasks

- [ ] Prep csv and split first names / names
- [ ] Compare with TS applications for missing data 
- [ ] Import in Mailchimp

## 🤼‍♂️   Reviewer

@krrisis

**Comment by lorelei1** [comment]
How to make Google Sheets separate the first and last names for you: 
https://spreadsheetpoint.com/separate-first-and-last-name-google-sheets/
