### ISSUE TITLE
Shorts Comms

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#45]
## 📋   Anything to add?

This is just an issue to add short discussion topics to for the weekly comms call - feel free to add if you have any in the comments or below!

## 🎉   Subtasks

- [x] signup form, we need opt-in #67 
- [x] Migrate mail! Check with @geleeroyale 
- [x] Edcon
- [x] Sneak peek content felix?
- [x] Content to review - gimme some time + deadline :) 
- [x] Praise dishing for Social #49 

## 🤼‍♂️   Reviewer

@krrisis
