### ISSUE TITLE
Spotlight Video #2

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#46]
## 🎉   Subtasks

- [x] Finalize editing
- [x] Kris to review 
- [x] Finalize 
- [x] Share with Trusted Seed
- [x] Share on Twitter 

## 🤼‍♂️   Reviewer

@krrisis
