### ISSUE TITLE
LAUNCH THE SWISS MEMBERSHIP DAPP!

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#462]
## 📋   Anything to add?

(Note from Tamara : I updated the below until I can make them into individual issues)

## 🎉   Subtasks

- [x] Get everyone on the team to give the thumbs up and become members
- [x] If they don't have the Thumbs up, make issues for the those problems
- [x] Solve those issues
- [x] (Griff)  Add everyone to the Registry
- [x] Deploy code to Prod 
- [x] (prod support plan = 1) Devs on stand-by are Amin & Fabio and 2) "for help" people are sent to telegram channel : https://t.me/CSTKSwissMembershipDApp) 
- [x] Soft launch : word of mouth invitations pre-release 
- [x] (Sponnet) Walk through video 
- [x] How-to blog post
- [x] Friday, 2/26, we announce it on the CS Sprint Review
- [x] (Comms) Email Trusted Seed, Twitter, Newsletter  (on the team agenda for 2/23)

- [x] RELEASE!!!

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

Dev : https://develop--tech-dapp.netlify.app/pay-dues
Prod  : https://member.commonsstack.foundation/pay-dues
