### ISSUE TITLE
CS Video introduction 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#464]
## 📋   Anything to add?

Add the Commons Stack video intro to the last Sprint Review video on YouTube. 
https://drive.google.com/file/d/1f_ToW-PPouSC9l4JgATpGcfcILxM-KQh/view?usp=sharing

## 🎉   Subtasks

- [ ] Add the intro to one video
- [ ] Decide if it should be added to all future CS videos
- [ ] Decide if it should be added to existing CS videos too
- [x] Ask customer support about adding intro to existing videos and reuploading edited videos but using the URL of the original one

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Awaiting response from Youtube customer support

**Comment by iviangita** [comment]
I didn't get any response from Youtube support. In the meantime, I will download the new videos and manually add the intro logo. Once done, I will reupload it in our channel and that's the one that goes public.

Will reopen this issue in the future if there are updates or if necessary.
