### ISSUE TITLE
Facilitate team discussions around the 2021 CS Narrative

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#465]
## 📋   Anything to add?
This sprint, I plan to facilitate some CS team calls around 2021 Narrative plans for the Commons Stack.

## 🎉   Subtasks

- [x] Set up team call
- [x] Discuss narrative as presented in docs & unify into a coordinated plan: 
- Jeff's proposal of our narrative (can be considered the SPACE in which we work): https://docs.google.com/document/d/1buAPUNGMyHe3gAV2yD9gm8vgRkD6NbteppSMcIdEBiw/edit?ts=6001fc70#heading=h.23hbvmkkj4n9 
- Griff's proposal of the timeline of tasks to carry out (can be considered as tasks organized in TIME):  https://docs.google.com/document/d/10zYrsad1qgeZ5MWHzyWQ7zC1xTwT9JZSLn6mXETOyTI/edit?usp=sharing
- [x] Create plan to carry out narrative plan, in accordance with short, medium and long term goals.
- [x] Draft article for next sprint

## 🤼‍♂️   Reviewer

@tamarandom @GriffGreen 

## 🔗   Work doc - inspirational links
Jeff's Narrative proposal: https://docs.google.com/document/d/1buAPUNGMyHe3gAV2yD9gm8vgRkD6NbteppSMcIdEBiw/edit?ts=6001fc70#heading=h.wlgq0re2nu0j

Griff's CS/TEC roadmap: https://docs.google.com/document/d/10zYrsad1qgeZ5MWHzyWQ7zC1xTwT9JZSLn6mXETOyTI/edit?usp=sharing

**Comment by Jeff-Emmett** [comment]
Article draft thus far: https://docs.google.com/document/d/1aSxu77XfZADpwDI0akFH1P-P_M1jRgfjGeWO341Lbok/edit#heading=h.wlgq0re2nu0j

**Comment by tamarandom** [comment]
@Jeff-Emmett access requested ;)

**Comment by Jeff-Emmett** [comment]
Granted, updated the above link to a shared version as well :)

**Comment by tamarandom** [comment]
It looks great!
