### ISSUE TITLE
Facilitate team discussions around 2021 CS Funding Strategy

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#466]
## 📋   Anything to add?
This sprint I plan to facilitate team discussions around potential funding strategies for the CS, and the associated risks and opportunities.

## 🎉   Subtasks

- [ ] Set up team call
- [ ] Discuss funding opportunities laid out in Jeff's proposal: https://docs.google.com/document/d/1zxI4SA7ox6y7TmBB4oot3wG4wVxiJmJ1vVDYuNTME20/edit#
- [ ] Make a plan to coordinate next steps on funding avenues worth exploring further

## 🤼‍♂️   Reviewer

@tamarandom @GriffGreen 

## 🔗   Work doc - inspirational links
Jeff's funding opportunities proposal: https://docs.google.com/document/d/1zxI4SA7ox6y7TmBB4oot3wG4wVxiJmJ1vVDYuNTME20/edit?usp=sharing

**Comment by Jeff-Emmett** [comment]
Given the relaxation of funding constraints due to the bull market, I will close out this issue.

**Comment by tamarandom** [comment]
🙌🏼
