### ISSUE TITLE
Commons Stack Website Review

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#469]
## 📋   Anything to add?
We are going to do a major website refresh - get your feedback in now! Organizational changes, issues with things mentioned, missing stuff, changes to copy (simplifications!), any major gripes or pet peeves about it?

http://commonsstack.org 

## 🎉   Subtasks
- [x] Take some time to look at the website a couple times over the course of this sprint, and take notes on your impressions. 
- [x] Share any feedback in the working doc
- [ ] Prioritize edits and move on them!

## 🤼‍♂️   Reviewer
@krisjpi 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1xLlfVVhbBOFZBbqZnf04aOqKosWS3RB-rRs5fDrqwaM/edit?usp=sharing

**Comment by krisjpi** [comment]
An older issue to review website and suggest needed edits. Some of these have been implemented already, but details on the review by team members is in this Doc - https://docs.google.com/document/d/1xLlfVVhbBOFZBbqZnf04aOqKosWS3RB-rRs5fDrqwaM/edit?usp=sharing

**Comment by tamarandom** [comment]
Going to close this epic. The reviews were all competed and ad @krisjpi mentions, we have the docs for reference if we want to embark on a website redesign.
