### ISSUE TITLE
Website visual & content fixes 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#47]
## 🎉   Subtasks

- [x] Kris review work @geleeroyale (orgs fix for mobile + newsletter design) & push live) 
- [x] Update privacy policy, cookie notif
- [x] Design updates - check in with alan & debrief what was discussed before vacation

## 🤼‍♂️   Reviewer

@
