### ISSUE TITLE
Commons Stack Library

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#470]
## 📋   Anything to add?
Brainstorm here (or organize a short session)
Where does it live?
short term, could be on the website, organized well. 
long term, a decentraland gallery with organized topic areas 🤯

## 🎉   Subtasks
- [ ] Talk about how awesome this would be
- [ ] Realize it's super possible especially built as community, multi-contributor task
- [ ] Setup contributor templates for success
- [ ] buidl

## 🤼‍♂️   Reviewer
@
