### ISSUE TITLE
Giveth and Commons Stack Nonprofit Legal Entity Exploration

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#48]
## 📋   Anything to add?

Giveth 2 needs a legal entity by September 5th. There are many options, the most promising one being just working under the Commons Stack Association and connecting to Jess' DAF in the US

## 🎉   Subtasks

- [x] Call with SDG Impact Fund to understand our requirements
- [x] Share this doc with the CS team and Coach B, as well as Giveth (Dani and Willy especially)  
- [x] Understand what magic Bernd has up his sleeve for making a Swiss nonprofit :-D
- [x] Call with Bernd to understand if adding Giveth to the CS Ass has any drawbacks 
- [x] Outline proposed path forward with amendments and approval from Jeff, Lorelei, Bernd, and rest of CS Team 
- [ ] Outline proposed path forward with amendments and approval from Willy, Dani, and Giveth team
- [x] Make a new issue for the execution of both plans

## 🤼‍♂️   Reviewer

@Kisgus 

## 🔗   Work doc - inspirational links
Notes from the call and Griff's proposal: https://docs.google.com/document/d/10-esS0tbr5WzA88MeQ6TGBoT1-GQLjOfBU8ikIR9GeM/edit?usp=sharing

**Comment by Kisgus** [comment]
Looks done to me
