### ISSUE TITLE
Commons Simulator Article Launch

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#484]
## 📋   Anything to add?
Prep comms materials for Commons Simulator launch (planned for distribution next sprint).  Griff would like to soft launch the simulator to our TG channels for this sprint to work through some last data/chart adjustments.

## 🎉   Subtasks

- [x] Scaffold article with CS comms team in next comms call
- [x] Share in csddev telegram channel!
- [x] Draft article (Jeff)
- [x] Draft tweets
- [x] Load content into distribution hopper

## 🤼‍♂️   Reviewer

@krisjpi 

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1kKwEKptnvU-mwABF7ORHWlSn6NmYJZfGS7ThTqRqZ3Q/edit?usp=sharing

**Comment by Jeff-Emmett** [comment]
@jessicazartler @krisjpi and I have been tracking links, drafts and tweet threads thus far in the CS Notion under "Active Content" in the Comms area.  All info can be found at the link below:

https://www.notion.so/giveth/Commons-Simulator-Announcement-ecfc186aebfa4ae1b2444848d7406afb

**Comment by Jeff-Emmett** [comment]
Moving into distribution of the Commons Simulator piece, starting today and continuing into next week.
