### ISSUE TITLE
Write a newsletter for Jan

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#485]
## 🎉   Subtasks

- [x] Should include Swiss membership dapp - not ready for the newsletter
- [ ] TEC update? 
- [x] Sprint Review Call?
- [x] Year End Review Call
- [x] CSLove? Swag Shop - almost there but not in newsletter yet

## 🤼‍♂️   Reviewer

@

**Comment by krisjpi** [comment]
Newsletter draft link circulated in CS team channel

**Comment by krisjpi** [comment]
Made the final suggested changes and sent it out.
