### ISSUE TITLE
Twitter Praise July 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#49]
## 🎉   Subtasks

- [x] Use the july tab, filter out the non-existing ones ànd check if you find/know others (in our chat), add these for Juliet
- [x] Test dish & dish + tag people who haven't spoken up & mention people's accounts who we don't know about
- [x] example of praise [here ](https://t.me/CommonsStack/9259) and unknown accounts+not spoken up [here](https://t.me/CommonsStack/9261)

## 🤼‍♂️   Reviewer

@krrisis 

## 🔗   Work doc - inspirational links

https://docs.google.com/spreadsheets/d/1c9jpGbteqyXCaC_XeB480JDx2m4yqQSq885jqgSAk-A/edit?usp=sharing
