### ISSUE TITLE
Plan CS Twitter posts and praise engagement/invite to Telegram

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#495]
## 📋   Anything to add?

Content planning will be done every Monday, praising engagement will be every Friday.

## 🎉   Subtasks

- [ ] Plan content for the week, draft copies and send to Kris for review every Monday
- [ ] Ask team members if there's anything specific to share for the week
- [ ] Praise people on Twitter for engagement and invite to Telegram channel (will draft the message here as well)

## 🤼‍♂️   Reviewer

@krisjpi 

## 🔗   Work doc - inspirational links
https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit?ts=601004ae#gid=0

**Comment by iviangita** [comment]
Closing this issue for now. Ekene is now handling the content planning for Twitter, and we recently decided to stop tagging people on Twitter for their engagement.
