### ISSUE TITLE
Panvala League Community Goals for Gitcoin

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#50]
## 📋   Anything to add?

This Gitcoin grant round Panvala is doing something different. Each community is going to have one grant that people will stake their Panvala on. We need to make this grant and get the Trusted Seed to participate in ordering it, it's a great opportunity for engagement and will help drive funds from our community to our community projects. It's going to be a really good round this time!

## 🎉   Subtasks
- [x] First draft of Gitcoin Grant due August 14th
- [x] Engage the Trusted Seed about it before August 21st, and get feedback on the idea 
- [x] Small Test vote on xDAI DAO
- [x] Make a walkthru vote on xDAI DAO
- [x] Test vote on xDAI DAO open for all Top Level Trusted Seed members
- [ ] Promote to our community that they buy PAN to donate and stake!
- [x] Have them vote for where our PAN goes (BEFORE Sept 14th)

## 🤼‍♂️   Reviewer

@liviade1 

## 🔗   Work doc - inspirational links
Gitcoin Grant:
https://gitcoin.co/grants/1127/commons-stack-community-fund-panvala-league
CSDAO on xDAI: 
https://aragon.1hive.org/?#/csdao/0xaa89fb730a83146cbf06661fd436e7445b4d0232/
VOTE!
https://cv.commonsstack.org

**Comment by lorelei1** [comment]
Make a new issue for Oct  Promote to our community that they buy PAN to donate and stake!
