### ISSUE TITLE
Commons Stack Trusted Seed Applicants "Praise"

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#505]
## 📋   Anything to add?
Obtain the list of monthly applicants that were sent the next steps email to be praised.

## 🎉   Subtasks

- [ ] Review "To Be Praised" column from the "Trusted Seed Assessment Email Outreach" spreadsheet.
- [ ] Avoid applicants marked with "No" or highlighted in red.
- [ ] Send !dish message to applicants with correct Telegram handles.
- [ ] If a Telegram handle or other missing info is found during the process, add it to the spreadsheet with a mention in the "Praise Comments" column.
- [ ] If an applicant lacks a handle... [TBD]
- [ ] Coordinate with Dan if necessary.

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by knobsdao** [comment]
@iviangita I'm making this comment as a reminder to discuss with you and nail down the exact process to praise TS applicants. It should repeat each sprint but the first will be for January. I'll most likely do it myself but this will help to standardize it. ( :

**Comment by iviangita** [comment]
@knobsdao thanks Dan! Looking forward to our discussion :)

**Comment by knobsdao** [comment]
It was decided in conversation with @GriffGreen not to praise applications at this moment. The issue may rise again for successful Swiss Memberships.
