### ISSUE TITLE
Inforgraphic: 4 Ways to Support the Commons Stack

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#52]
## 📋   Anything to add?
Infographic for posting on various channels and in articles

## 🎉   Subtasks

- [x] Jess Write & Design DRAFT
- [ ] Kris/Dan/Jess Review & suggest - just 4 or 5?
- [ ] Justice edit content & Fix Design
- [ ] Push to distribution

## 🤼‍♂️   Reviewer

@krisjpi @knobsdao @jessicazartler 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1PQHS74NJ0LjtBD1z6XYO846Ev4WkVuTRf1Ip92hgrz4/edit?ts=5f04f4af

**Comment by Kisgus** [comment]
Please assign a milestone to his issue @krrisis or @jessicazartler :)

**Comment by jessicazartler** [comment]
> Please assign a milestone to his issue @krrisis or @jessicazartler :)

**Comment by tamarandom** [comment]
Backlog refinement. Closing out these old (15 months old!) issues.

**Comment by jessicazartler** [comment]
@YineisyM this was the project I was talking about if you were interested in working on this with me it's a quick job to finish - I just never got anyone to give me feedback :D

**Comment by YineisyM** [comment]
Awesome! Let's work together in this issue, I'm reviewing the old doc! Thanks Jess!

**Comment by tamarandom** [comment]
@YineisyM @mafer-cordovas I want to make sure this is on your radar before I close it. The idea @jessicazartler raises here - how you can support the CS - is important! It might be worth having Rodri design something based on her original designs in the doc link above. 

Also worth noting that the TS Dashboard will also be a place where "how to support" can be shared. @mafer-cordovas I think you are working with @kristoferlund on that content, right?
