### ISSUE TITLE
See the dashboard idea in Jeff's Jan 29, 2021 comment!

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#522]
## 📋   Anything to add?

Should we create an issue for each call we hold and what happens? We will also have the CRM soon so maybe we do the tracking there? Let's discuss Monday in next sprint planning meeting

## 🎉   Subtasks

- [x] Start with a call to figure it out
- [ ] Make a fuck ton more issues

## 🤼‍♂️   Reviewer

@jessicazartler @Jeff-Emmett

**Comment by Jeff-Emmett** [comment]
I propose a simple & lightweight way for @knobsdao to update the team on calls that occurred in the sprint via a Trusted Seed KPI dashboard that could be presented each sprint.

Please no more issues for every single thing we do - let's aggregate info and display summaries for easy team digestion. I also don't think we should expect our whole team to be logging into the CRM to follow up on leads & stats.  I am happy to help pull together a high level vision of info that would be useful to see each month, so that we can track and display this info easily, without additional overhead on behalf of each team member.

**Comment by Jeff-Emmett** [comment]
Trusted Seed KPI dashboard (example):

**Total Members of the Trusted Seed:** 999
**New members this sprint:** +34
**New donations this sprint:** +$1000
**Calls were carried out with the following groups:**
- CarbonBase.co
- Digital Supercluster Vancouver
- Project xyz

**Upcoming TS events:**
- Trusted Seed AMA - Feb 13 @ 10 am EST - <calendar event>

**Distribution of CSTK tokens**:  (pie chart)

**Feedback from Trusted Seed this month:**
- Max from Carbonbase requested <xyz>

**Comment by jessicazartler** [comment]
☝️ So one issue with this info would be great +1

**Comment by GriffGreen** [comment]
An initial Trusted Seed Dashboard...

Probably starts with a kick off call between @Jeff-Emmett and @knobsdao 

3 parts

- [ ] Infrastructure part
- [ ] Dashboard print out
- [ ] What hits the review call

**Comment by knobsdao** [comment]
Related to #350

**Comment by jessicazartler** [comment]
Heya @knobsdao where are we tracking these for now? Would love to be able to input calls I am having and the progress.. keep me posted and thanks you!

**Comment by tamarandom** [comment]
Update: Ideally in Hubspot (thinks @knobsdao) ;)

**Comment by tamarandom** [comment]
Hey @mafer-cordovas Can you look at @Jeff-Emmett's comment from Jan 29, 2021. The idea of a Dashboard like that was really great and would be very helpful to the team. Do you already have something like this you are working on? (Ignore the title of this issue as the ideas evolved since it was first created).

**Comment by tamarandom** [comment]
@knobsdao used to share with the rest of Commons Stack some information about our new members so that we ourselves would know who our members were. A update every Sprint that included those kinds of info would be really great for the core team to know what is happening.

**Comment by tamarandom** [comment]
Created issue #1267 to track the dashboard idea we want to pull out of this issue. Closing now! 🧹 🧹 🧹
