### ISSUE TITLE
Openly Quantify Praise Plan

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#524]
## 🎉   Subtasks

- [ ] Do it in a Discord channel?
- [ ] make a cal invite
- [ ] make a public sheet
- [ ] make it clear in the blog post that we are doxing everyone

## 🤼‍♂️   Reviewer
@
