### ISSUE TITLE
Updated Blogpost on Praise

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#528]
## 📋   Anything to add?
**We need a blog post to update praise!**

## 🎉   Subtasks

- [ ] Make clear addresses are identity and bank accounts
- [ ] Talk about the praise past
- [ ] Talk about the new praise updates!
- [ ] Discord, open praise, praising yo self.
- [ ] How to claim :-D (apply to trusted Seed, pay membership dues)
- [ ] How to get the power...

## 🤼‍♂️   Reviewer

@

**Comment by knobsdao** [comment]
Note to self: What's the key data when showcasing praise progress? # of total/monthly praises, # of recipients, # of CSTK dished?

**Comment by GriffGreen** [comment]
Ata's praise case study....

**Comment by GriffGreen** [comment]
Praise case study blocking

**Comment by tamarandom** [comment]
Close this now, right? @GriffGreen

**Comment by tamarandom** [comment]
On second thought, it's a good idea to write up a new post about "new" Praise. Let's do this after we deploy to CS. Giveth and Gnosis deployments are right behind that and there are other communities interested already too.

**Comment by tamarandom** [comment]
Created new issue for that: #1410

**Comment by tamarandom** [comment]
Created new issue for that: #1410
