### ISSUE TITLE
Prepare documents for CS Sprint Review/Retro (every end of sprint)

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#534]
## 🎉   Subtasks

- [x] [CS Sprint Agenda](https://docs.google.com/document/d/1KDNEYsV4O-6Mm64w_MgpWg2uBNI3SWC2JG49IRmU3oE/edit#heading=h.c805vvkra0vi)
- [x] [CS Sprint Retrospective](https://docs.google.com/document/d/1QZXDkf2oWTK0OnKc9v6BPWjDAgS_lPKVOtvuedBxpOc/edit)
- [x] [Retrospective Miro Board](https://miro.com/app/board/o9J_lb1jJt4=/)

## 🤼‍♂️   Reviewer

@tamarandom

**Comment by tamarandom** [comment]
🙌🏼  Great work, @iviangita
