### ISSUE TITLE
Revise Acceptance Email

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#54]
## 🎉   Subtasks

- [x] General acceptance to cold donors - page 8 of email template doc
- [x] related to issue #44 - when first names are updated we can "personalize" all emails

## Later
- [ ] Personalized acceptance to hot donors - page 2-3 of email template doc
## 🤼‍♂️   Reviewer 

@lorelei1

**Comment by lorelei1** [comment]
Test emails were sent out for 2 types of "cold" donor on Friday. I need to integrate that feedback and send test again, then we are good to start sending those ones!

**Comment by lorelei1** [comment]
These are complete and have been being sent out for a couple weeks now!
