### ISSUE TITLE
Draft the CS 2021 Direction Article

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#543]
## 📋   Anything to add?
Turning our 2021 Narrative doc into a 2021 project direction article, to remind people about all the awesome work we do and why they should fund us.

## 🎉   Subtasks

- [x] Rough points and diagramming (Jeff)
- [x] Draft article (Jess)
- [x] Jeff edit
- [x] Share with team for feedback 
- [ ] Publish
- [ ] 
## 🤼‍♂️   Reviewer

@krisjpi @GriffGreen @tamarandom 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1aSxu77XfZADpwDI0akFH1P-P_M1jRgfjGeWO341Lbok/edit?usp=sharing

**Comment by Jeff-Emmett** [comment]
Working on diagrams and content for this piece, but will hold on sharing with the comms channels until the simulator piece commentary is completed and the draft is ready to go out.

![image](https://user-images.githubusercontent.com/46964190/109045171-42f38580-76a1-11eb-883c-733289f6f14b.png)

**Comment by GriffGreen** [comment]
Should we push some of these concepts into discord?

We could do this! Discord is still fluid and evolving

Onboarding needs to be streamlined... maybe this flows into it?

**Comment by jessicazartler** [comment]
Jeff has scaffolded and listed everything out - I will turn it into sentences and edit a bit to take the next step
Then we can have a review & publish

**Comment by jessicazartler** [comment]
Finished the 1st draft, passed to Jeff to review

**Comment by jessicazartler** [comment]
@tamarandom @liviade1 @GriffGreen @krisjpi @knobsdao can you please review? Would love all of your inputs/feedback on this  - Would love to publish this week :D 

https://docs.google.com/document/d/1aSxu77XfZADpwDI0akFH1P-P_M1jRgfjGeWO341Lbok/edit

**Comment by tamarandom** [comment]
Reviewed and find it excellent. Left some minor comments. 😇

**Comment by jessicazartler** [comment]
I put it on Medium - publishing today - then putting in distribution pipeline - thanks everyone!
