### ISSUE TITLE
Internal Review of Commons Stack Notion

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#544]
## 📋   Anything to add?
Aggregating our plan, links and repos into a one stop shop for sharing with our audience.

## 🎉   Subtasks

- [x] TL;DR of all of our articles
- [x] Aggregate links for a couple of these: simulators, code repos, working groups, research initiatives, etc.
- [ ] Walk through appropriate sections with responsible team members
- [ ] Publish public pages & distribute 

## 🤼‍♂️   Reviewer

@krisjpi 

## 🔗   Work doc - inspirational links
https://www.notion.so/CS-Internal-Coordination-9003dfe3088e4bda96507505bd6e3125

**Comment by jessicazartler** [comment]
I will also integrate the links I have / started in this issue 

https://github.com/commons-stack/iteration0/issues/468

**Comment by GriffGreen** [comment]
Talk to @Danibelle if we can some how attach our notion to Giveth's...
