### ISSUE TITLE
Ensure TS Data Integrity 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#551]
## 📋   Anything to add?

This issue is a reminder for ongoing data integrity work across our data-sheets and the CRM during the sprint.

## 🎉   Subtasks

- [x] Create a list of TS Applicants that also hold TEC IH (done up till January 2021)
- [x] Build Group of TS Properties.
- [x] Build Group of MailChimp-related Properties
- [x] Take care of dupe applications
- [x] Merge duplicates in the CRM. [Ongoing]
- [ ] Other to come...

## 🤼‍♂️   Reviewer

@

**Comment by knobsdao** [comment]
46 TS dupes identified and currently being sorted.

**Comment by knobsdao** [comment]
All identified dupes sorted, merged and/or marked for refinement.

**Comment by tamarandom** [comment]
Moved to Trusted Seed Dashboard. 🌱 
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/56
