### ISSUE TITLE
New CTA template for CS articles 

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#573]
## 📋   Anything to add?

We need to create a new CTA template for CS articles. 
You can use the TEC CTA as a reference: 

"We warmly welcome you to join and share:
👋 Pop by our Discord or Telegram channels, introduce yourself and share what you are working on
☎ Say hi on our weekly community calls at 2pm EST / 8pm CET on our general voice channel on Discord — add it to your calendar
💸 Submit a proposal for funding for your TE project
📑 Read more about our working groups and join one
📣 Follow us on Twitter & Medium to stay up to date on the upcoming hatch" 

## 🎉   Subtasks

- [ ] Create a Call To Action template that can be added to all CS Medium publications. The content should have: 
- [ ] An invite to our active Discord and Telegram Channels. 
- [ ] Invite to our calls with time and place where they happen
- [ ] Invite to apply to the Trusted Seed 
- [ ] Invite to become a contributor with Dan's handle as a point of contact 
- [ ] Link to our Youtube channel and a shoutout to the Trusted Seed Spotlight
- [ ] Invite to follow us on Twitter  

## 🤼‍♂️   Reviewer
If you have any questions you can contact Kris and Jess. Communication can happen in the comments of this issue! 
@krisjpi  @jessicazartler 

## 🔗   Work doc - inspirational links
https://medium.com/token-engineering-commons/towards-robust-and-resilient-economies-and-communities-8effcc5bc20d

**Comment by GriffGreen** [comment]
See the medium post for the TEC template and copy for our old articles...

**Comment by jessicazartler** [comment]
I did two new ones in these two articles:

https://medium.com/commonsstack/zen-and-the-art-of-understanding-commons-stack-f5266b300912
https://medium.com/commonsstack/whats-in-a-hatch-3799a398243a

Would be great to combine/synthesize these ones @krisjpi 

And maybe @tamarandom @liviade1 we could ask Anna Marie Swan if she would be up for this one too?
