### ISSUE TITLE
Proposal for Seeds Partnership

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#575]
## 🎉   Subtasks

- [x] Work sesh with Dan/Griff
- [x] Jess draft proposal
- [x] Jeff edit / Griff review
- [x] Jeff/Jess/Dan send & schedule follow up call

## 🤼‍♂️   Reviewer

@GriffGreen @knobsdao 

## 🔗   Work doc - inspirational links
Proposal template
https://docs.google.com/document/d/1V7KhUyyFbz_UBJoAM_xeJhC6D0qpvz8ufI5TzihxXfA/edit

**Comment by jessicazartler** [comment]
https://docs.google.com/document/d/1RQeZYYpeQT9qU4CByT7zf1pQ6UHeXAZ7JhO268Ji-_8/edit

**Comment by jessicazartler** [comment]
Final version sent & working to schedule a follow up call :D

[SEEDS_Commons Stack Partnership Proposal.pdf](https://github.com/commons-stack/iteration0/files/6013109/SEEDS_Commons.Stack.Partnership.Proposal.pdf)
