### ISSUE TITLE
Draft v1 of Cultural Playbook for launching Commons 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#60]
## 📋   Anything to add?

Documenting the Cultural build for the TE Commons, identifying what we did and what we should have done on a weekly basis will be huge here.

## 🎉   Subtasks
- [x] Schedule Weekly Review meetings
- [x] Gather all the relevant links!
- [x] Create a Doc where we track the progress
- [x] Incorporate points from the previous week to be discussed on Wednesday, September 2nd work session 
- [x] Start formalizing a process for the weekly sync documentation
- [x] Incorporate points from the previous week to be discussed on Wednesday 9th work session
- [x] Research best practices from other communities
- [x]  Incorporate points from the previous week to be discussed on Wednesday 16th work session
- [x]  Incorporate points from the previous week to be discussed on Wednesday 23rd work session
- [ ]  Have a first draft of the progress for feedback by Wednesday 30th

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links

Final stuff for finishing the Playbook includes

- [ ] Get feedback from other experts (PeterPan, Luke D, Luke S, James D, James W, etc)  
- [ ] Determine wiki location  
- [ ] Transition the doc into a wiki and maintain the wiki 
- [ ] Determine the best way to make the information more accessible.

https://docs.google.com/document/d/1T8Tc7z7Eg1U94JNLG9T-HvyTy3EhNReRm4Mq8cpQ42o/edit#heading=h.vwkadyyemdc4

**Comment by lorelei1** [comment]
Livia's super close!!
