### ISSUE TITLE
Youtube management

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#607]
## 🎉   Subtasks

- [ ] Can the order of the playlists be changed so that the more recent+important ones are at the top.
- [x] Remove playlist “TEC calls”? The content in that playlist is from Oct 24 and before.
- [x] Can we add playlist “Commons Stack Reviews”

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
Can the order of the playlists be changed so that the more recent+important ones are at the top.
-> Not possible for the creator (us) to do this in the Playlists section but the viewers can sort them by date when they go to our channel

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/1b619305-cd96-4ef1-8573-c57b069db39d)


BUT, I was able to update the homepage of our channel and added the recent playlists on the top: CS Reviews, Commons Simulator, and Trusted Spotlight

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/f9417313-50b6-481a-a1a7-4d1af65e16f3)

Closing this for now. Will reopen when there are new tasks to do for this :)
