### ISSUE TITLE
Finalize Design with Marko

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#61]
## 🎉   Subtasks

- [ ] Put Markos v1 out for Community Review
- [ ] Update text with newest from Dani
- [ ] Get frontend dev to review changes within the budget
- [ ] Done, start development

## 🤼‍♂️   Reviewer

@markoprljic
