### ISSUE TITLE
Tweet thread for Simulator article/release

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#610]
## 🎉   Subtasks

- [x] Draft Tweet thread from article
- [x] Get new images /GIF from simulator
- [x] Jeff review Tweet thread
- [x] post on Twitter

## 🤼‍♂️   Reviewer

@Jeff-Emmett @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1kKwEKptnvU-mwABF7ORHWlSn6NmYJZfGS7ThTqRqZ3Q/edit

**Comment by jessicazartler** [comment]
Drafted! Jeff will review and add latest images, then we are ready to tweet when you say go @GriffGreen :D

https://getchirrapp.com/drafts (must be signed into CS twitter to access)
