### ISSUE TITLE
Fill out CS Notion sections

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#613]
## 📋   Anything to add?

Update your section and remove yourself from task when you're done..

## 🎉   Subtasks

- [ ] @jessicazartler -[ Ecosystem Funding ](https://www.notion.so/giveth/6-Public-Goods-Ecosystem-Funder-Gitcoin-Panvala-7c54f478955b42028625398e6a37fc09)(w/Gitcoin Grants stuffs)/Partnerships
- [ ] @liviade1 - [Knowledge Base](https://www.notion.so/giveth/4-Knowledge-Base-dfce1195694a42f79836b8ddce5d0ccd) links (Handbook drafts, Case Studies, Implementation Lessons Learned, etc)
- [ ] @krisjpi - [Relevant comms links & organizational processes](https://www.notion.so/giveth/0-CS-Communications-668737ad87a5482b96d3317f29ea242e)
- [ ] @knobsdao - [Trusted Seed links, KPI Dashboard/Partnerships](https://www.notion.so/giveth/1-Trusted-Seed-Curation-Partnerships-fd39192ac7cf49b29cb9e8481ba0326e)
- [ ] @GriffGreen @tamarandom - [Development group links to smart contract repos etc](https://www.notion.so/giveth/2-Development-Group-5e4fa97246864bb78524cac07d5ab2cf)
- [ ] @Jeff-Emmett - Assist, review & polish

## 🤼‍♂️   Reviewer

@Jeff-Emmett 

## 🔗   Work doc - inspirational links
https://www.notion.so/Commons-Stack-f7242caca28a4f60b28148b7677cac60

**Comment by tamarandom** [comment]
Hey @jessicazartler Let me turn this into an epic so we can stick to our one issue = one assignee practice. Looks like you've done your piece but there are some pieces of work that we'll need to carry to the next Sprint. 🧘🏻‍♀️

**Comment by jessicazartler** [comment]
Yes thank you Tam! I haven't made time for this.. was hoping people would make theirs but everyone is so busy.. we appreciate you doing that!!! Thanks very much :D <3

**Comment by jessicazartler** [comment]
@tamarandom reassigned from me to @iviangita as this is a Comms decision on whether or not to continue using this. I still use it for myself for link tracking on the library front but copying to my own notion... Let me know if further support is needed. Thank you!

**Comment by tamarandom** [comment]
Closing! @iviangita will open a new issue to reformat the notion page for internal and external audiences.
