### ISSUE TITLE
Execute Swiss Membership Dapp Release - Comms Plan

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#615]
## 🎉   Subtasks

- [x] Release Dapp
- [x] Email blast (NEWSLETTER)
- [ ] Tweet/thread

Post Tweet thread link w/ tailored message in:
- [ ] CS Discord or Telegram
- [ ] TEC general discord
- [ ] TE general discord

## 🤼‍♂️   Reviewer

@GriffGreen @Jeff-Emmett @jessicazartler @tamarandom

**Comment by jessicazartler** [comment]
Email blast draft https://docs.google.com/document/d/1qwITu17_3Eu6XRW6iaEDrW-zvVU6ZMoaffItiUmPaxk/edit#heading=h.s4amv1sbtw1d

**Comment by jessicazartler** [comment]
@krisjpi to write Tweet thread and post the link here for Nate to distribute in channels

Kris also to write newsletter - ask me if you need support
