### ISSUE TITLE
cadCAD simulation vertical

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#62]
## 🎉   Subtasks

- [x] Keep the roadmap updated with Andrew
- [ ] Get a second dev to support him
- [ ] Get feedback on his cadCAD sims from blockscience
- [ ] Track progress in weekly meeting

## 🤼‍♂️   Reviewer

@Kisgus 

## 🔗   Work doc - inspirational links
https://github.com/commons-stack/coodcad/issues/10
