### ISSUE TITLE
Gitcoin Grants Round 9 Kickoff!

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#623]
## 📋   Anything to add?

It's that time again.... March 10-25 Gitcoin Grants Round 9!
Let's kick it off a little earlier this time and get everything prepared.. I will try and get everything in the Notion from the past rounds beginning next week and we can have a kick off meeting to discuss

## 🎉   Subtasks

- [x] Organize past campaign info in Notion
- [x] Schedule kickoff meeting
- [x] Create issues for all the things - maybe it needs its own epic? 

## 🤼‍♂️   Reviewer

@GriffGreen @krisjpi @Jeff-Emmett @cranders1 @tamarandom @knobsdao 

## 🔗   Work doc - inspirational links

![image](https://user-images.githubusercontent.com/43972522/109024114-69a6c180-768b-11eb-89a6-59274ea03fbc.png)

**Comment by jessicazartler** [comment]
EPIC #658 https://github.com/commons-stack/iteration0/issues/658
