### ISSUE TITLE
Article: The Commons Stack Pattern as a Public Goods Funding Machine

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#624]
## 📋   Anything to add?
Another article up on the chopping block.

## 🎉   Subtasks

- [x] Collate rough points and diagramming
- [ ] Draft article (next sprint)
- [ ] Share with comms team
- [ ] Add to publication & distribution plan

## 🤼‍♂️   Reviewer

@krisjpi 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1yKh_1F-rtrl4SCk8_fcWBx9mpBOY7rT5Ke8l5xlbF6E/edit
