### ISSUE TITLE
Managing Commons Simulator Syncs and Praise for August

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#63]
## 🎉   Subtasks

- [x] Tuesday, 18th, Sync Call
- [x] Praise for 18th Call
- [x] Praise for work done in August from before 18th
- [x] Tuesday, 25th, Sync Call
- [x] Praise for 25th Call
- [x] Praise for work done 18th-25th

## 🤼‍♂️   Reviewer

@lorelei1
