### ISSUE TITLE
Managing the TE Commons Roadmap Progress - August

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#64]
## 🎉   Subtasks

- [x] Vote on Code of Conduct
- [x] Vote on Mission
- [x] Get feedback on Decision Making process
- [x] Get feedback on Incentive Design
- [x] Get feedback on Roadmap
- [x] Prepare for Thursday, 20th, call
- [x] Post Agenda for call.
- [x] Promote Thursday, 20th, call
- [x] Have Thursday, 20th, call
- [x] Vote on Decision-Making process
- [x] Vote on Incentive Design
- [x] List here what we need to get feedback on for next week
- [x] Clean up Incentive Alignment Doc 
- [x] Ping everyone about incentive alignment doc 
- [x] Talk to Angela, Sebnen, and Cyprien about their expected roles and rewards
- [x] Merge Decision-Making docs into one proposal and add Advice Process explicitly into it
- [x] Internal Comms Strategy proposal
- [x] Visioning a working Commons Meeting plan
- [x] Prepare for Thursday, 27th, call
- [x] Outline what are the next steps for the upcoming week.
- [x] Promote Thursday, 27th, call
- [x] Have Thursday, 27th, call 
- [x] Vote on stuff on Friday the 28th
- [x] Vote on Decision-Making process AGAIN
- [x] Vote on Incentive Design AGAIN
- [ ] Role Proposal - to be moved to September
- [x] Sync with Jess and Jeff for Aragon proposal

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by liviade1** [comment]
We still need feedback for the incentive alignment and for the decision making process. 
IMO we need to touch on boundaries before we follow up with the ones above.

**Comment by GriffGreen** [comment]
Great work Livia... I was tracking hard on this one... I will close it and have Juliet recreate it for September
