### ISSUE TITLE
Distribution Simulator Tweet thread 

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#641]
## 📋   Anything to add?

Need to write a lil post and distribute in all the channels

## 🎉   Subtasks

- [x]  CS dDev channel (will get lots of love & RTs!)
- [x] CS Telegram
- [x]  Radical xChange
    - [x]  RT on twitter
    - [ ]  Newsletter? (Dan request)
- [x]  cadCAD forum
- [x]  cadCAD telegram channel
- [x]  cadCAD Gitcoin Grant email
- [x]  Twitter
- [x]  TE cadCAD
- [x]  TEC general
- [x] 1Hive buzz channel
- [x]  CS newlsetter
- [x]  Partners: Conflux
- [x] Metagame
- [ ] Seeds
- [x] NEAR
- [x] Dacade/ApeUnit

## 🤼‍♂️   Reviewer

@Jeff-Emmett @GriffGreen 

## 🔗   Work doc - inspirational links

See #610 &
https://www.notion.so/Commons-Simulator-Announcement-ecfc186aebfa4ae1b2444848d7406afb

**Comment by jessicazartler** [comment]
I've finished sharing in all the channels - working with Jeff for cadCAD/seeds - just @krisjpi if you could do RadExchange contact/Metagame/CS newlsetter we're well covered - thank you :D
