### ISSUE TITLE
Update CSTK Registry on xDai

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#644]
## 🎉   Subtasks

- [x] Add newly assessed TS successful applicants to the xDAI Reg tab
- [x] Check formulas are working and that there are no dupes
- [x] Add them to the xDAI Registry
- [x] Mark as added in the xDAI Reg tab
- [x] Double-check all's good

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
Taken forward after the initial addition of successful TS applicants to the xDAI Registry #10
