### ISSUE TITLE
Create Praise onboarding call!

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#645]
## 🎉   Subtasks

- [x] Find a date/time that should work
- [x] Add date to CS calendar
- [x] Start hosting calls and inviting new members to come!

## 🤼‍♂️   Reviewer

@krisjpi

**Comment by krisjpi** [comment]
This is complete! We have a standing call in the CS calendar - Wednesdays 9PST, 12EST, our first call was last week!
