### ISSUE TITLE
Monthly Newsletter ! 

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#647]
## 🎉   Subtasks

for March :
- [ ] target send date - Thursday March 4th
- [ ] Commons Sim, Trusted Seed Spotlight, Discord invite, ...?
- [ ] Membership Dapp Email to follow next week

## 🤼‍♂️   Reviewer

@krisjpi

**Comment by jessicazartler** [comment]
Newsletter draft here https://docs.google.com/document/d/1qwITu17_3Eu6XRW6iaEDrW-zvVU6ZMoaffItiUmPaxk/edit#heading=h.s4amv1sbtw1d

**Comment by jessicazartler** [comment]
@krisjpi what is a good target send date? So I can prioritize the TS #5 edit accordingly

**Comment by krisjpi** [comment]
Sent out Monday May 3rd.

**Comment by jessicazartler** [comment]
Woop woop!

**Comment by GriffGreen** [comment]
sent a ton of hatch emails... maybe we leave this for the next month... 

Could also get a Hatch Follow up email... could add the AMA, and other content... Anna-Marie's guest blog..

**Comment by GriffGreen** [comment]
Anna- Marie to write a content piece for her part of the email

**Comment by tamarandom** [comment]
February newsletter sent! Closing.

**Comment by tamarandom** [comment]
Newsletter on hold. Closing for now. We can open a new one when needed.
