### ISSUE TITLE
Async Praise meeting

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#65]
## 🎉   Subtasks

- [x] Make Doodle for Thursday/Friday meeting times 
- [x] Gather results by Tuesday from everyone
- [x] Make a regular meeting calendar invite for the chosen time

## 🤼‍♂️   Reviewer

@Kisgus

**Comment by Kisgus** [comment]
@GriffGreen how about we also loop in Julio on this call for CCA?
