### ISSUE TITLE
Submit Seeds Proposal to the Seeds DHO

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#655]
## 📋   Anything to add?

Had a follow up call about our partnership, now we have some next steps to submit our proposal and request funding

## 🎉   Subtasks

- [x] Edit proposal content to suit decentralized DHO audience
- [x] Primer on CSTK benefits/rights/value
- [x] Create Hypha account
- [x] Contact Reiki when ready to submit to the DHO 
- [ ] Withdraw Seeds stable coin to ETH/BTC & transfer to Commons Stack wallet

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1RQeZYYpeQT9qU4CByT7zf1pQ6UHeXAZ7JhO268Ji-_8/edit

**Comment by jessicazartler** [comment]
Primer draft
https://docs.google.com/presentation/d/1GnBiXP5sUeCwsCPItXwmqsCzK9TL71pkyGmF5xHlBA0/edit#slide=id.p

**Comment by jessicazartler** [comment]
Jeff and I both struggling to access our private keys to get set up on Hypha, contacted Rieki for call or walk through to sort this so we can submit the proposal

**Comment by jessicazartler** [comment]
Jeff and I got our wallets set up and submitted our membership applications to the DHO. Rieki is working on approving, and then we will work with him to submit a proposal. Should finish this sprint.

**Comment by jessicazartler** [comment]
I am setting up one last call with Rieki to get this thing submitted to the DHO!!

**Comment by jessicazartler** [comment]
The Seed token price went down ALOT before we get everything submitted (Reiki is SUPER busy also and was hard to get his attention to support us in this process).. I talked with Julio Holon but he said to approve anything in the realm of 25k it would have to be more like an advisory project for governance that would require a lot more CS resources. We could re-open this with another Julio discussion but it seemed like a lot of work for just 25k that would require dedicated resources for a few months project... Closing this task but if you are interested to pursue you could contact Julio Holon#2942 - he did say they might be willing to fund Gravity work - otherwise would have to be a very focused project that would benefit Seeds.
