### ISSUE TITLE
Gitcoin Grants Rounds 

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#658]
## 📋   Anything to add?

Qs & Ideas from last round:
- Plan & Organize a twitter AMA for all the basic things... "how do I vote", "what is a CS score", "what is 

Important Links:
- Comms Strategy templates, timeline & ideas: https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit
- Notion page w/ some old content links: https://www.notion.so/giveth/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09
- Community Fund 'How-To' article: https://medium.com/commonsstack/the-commons-stack-community-fund-is-back-for-gitcoin-grants-round-10-b82be441aed1
- Community Fund 'How-To' video: https://www.youtube.com/watch?v=kHrI7hHJicQ
- End of Round 'Thank you' templates for grant owners: https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit# 

## 🎉   Subtasks

IMPORTANT DATES:
JUNE 14: pre-gitcoin-round tasks start
JUNE 16: GitCoin Round 10 start
JUNE 21: pre-community-fund tasks start
JUNE 23: CS Community fund voting starts
JUNE 28: Community fund voting ends
JULY 1: GitCoin round ends
JULY 1: post-round tasks start

FOCUS: Coordinating GitCoin grant submission and CS community fund voting for entire CS/ecosystem

**PRE-ROUND, FYI TO GRANT OWNERS**
MON. JUNE 14
- [ ] Discord poke to GitCoin grant owners: "FYI update links, more details coming at round start" (PETER)
- [x] Re-open the CS Conviction Voting dApp https://cv.commonsstack.org/ (GRIFF/SEM)

**ROUND STARTS, PUSH FOR PEOPLE TO SUBMIT GRANTS**
WED. JUNE 16
- [ ] Tweet / Twitter Plan: individual shares + thread (PETER)
- [ ] Discord message / Community Management: Can we help you to submit your grant? (PETER)
- [x] Comms push every XX days (PETER / EKENE / IVY) this will be on-going (https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit)
- [ ] "Like" contributions for CS + cadCAD grants (PETER / EKENE) this will be on-going

**PRE COMMUNITY FUND VOTING**
JUNE 21
- [ ] Create/Update/plan to re-use video walk through on how to submit grant to community fund (PETER / KRIS) https://www.youtube.com/watch?v=kHrI7hHJicQ
- [ ] Refresh & post blog: "How to Vote/xDAI" and update link on community fund DAPP (PETER/KRIS/EKENE) https://medium.com/commonsstack/commons-stack-community-fund-voting-round-3-dedc0f98d495
- [ ] Prep newsletter for Wednesday send: Announce Community fund vote! (Do you know where you CSTK is? activate membership & update info preparing for the vote!) (PETER/EKENE) w
- [ ] Create "Commons Stack Collection" to promote in newsletter

**COMMUNITY FUND VOTING START**
JUNE 23
- [ ] Tweet (PETER/EKENE)
- [ ] Discord message / Community Management plan: "got voting issues? here's helpful troubleshooting resources" (PETER / CS DISCORD)
- [ ] Newsletter subject: "Community Fund voting open!" (KRIS/PETER/EKENE)

**COMMUNITY FUND VOTING END**
JUNE 28
- [ ] close CS CV dApp (GRIFF/SEM)
- [ ] aggregate data & determine top 15 grants (GRIFF)
- [ ] Tweet out Community Fund voting results w/ final push for donating to the GCG in $PAN (PETER/EKENE)

**ROUND ENDS, WRAP UP AND THANK YOUS**
JULY 1 - ONGOING
- [ ] Collect $PAN from Community Fund GCG and do some magic to prepare the distribution (GRIFF)- [ ] 
- [ ] Thank you video? CS + ecosystem (prepare this for Newsletter)
- [ ] Newsletter (wait until July 14th? make it a full wrap-up: results & TYs)
- [ ] tell grant owners via discord DM to thank their donors (PETER) https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit#
- [ ] Thank you templates: https://docs.google.com/document/d/1bnfdHFdkjrNGEV_O2g6Z-H0o-SC1vLGtJ4CFMsbhFL8/edit

**LINKS TO GITCOIN GRANTS**
- [x] [Commons Stack Community Fund - Panvala League](https://gitcoin.co/grants/1127/commons-stack-community-fund-panvala-league) (GRIFF)
- [x] [Commons Stack Iteration 0](https://gitcoin.co/grants/539/the-commons-stack-iteration-0) (JESS)
- [x] [Token Engineering Commons](https://gitcoin.co/grants/1155/token-engineering-commons) (CRAIG)
- [x] [Commons Simulator](https://gitcoin.co/grants/277/commons-simulator-modeling-sustainable-funding-for) (GRIFF/DANI)
- [x] [Giveth](https://gitcoin.co/grants/795/giveth-20) (GRIFF/DANI)
- [x] [cadCAD](https://gitcoin.co/grants/308/cadcad-computer-aided-design-for-complex-systems) (JEFF)
- [x] [Conviction Voting cadCAD Model Improvements: 1Hive Luna Swarm 🐝](https://gitcoin.co/grants/1141/conviction-voting-cadcad-model-feature-improvemen) (JEFF)
- [x] Crypto Commons Gathering (JEFF)
https://gitcoin.co/grants/2073/crypto-commons-gathering-2021
- [x] TE Academy (NATHALIA)
https://gitcoin.co/grants/517/tokenengineering-community
- [x] HG2TE (JESS/SEBNEM)
https://gitcoin.co/grants/798/a-hitchhikers-guide-to-token-engineering
- [x] Bloom (MAGENTA)
https://gitcoin.co/grants/1595/bloom-network
- [x] Impact Pirates (SEBNEM)
https://gitcoin.co/grants/1638/electric-circus-proudly-presents-impact-pirates
- [ ] LIBRARY OF GITCOIN TEMPLATES/CONTENT LIVES IN OUR CS NOTION
https://www.notion.so/Public-Goods-Ecosystem-Accelerator-Partnerships-Funding-7c54f478955b42028625398e6a37fc09

## 🤼‍♂️   Reviewer

@krisjpi @Jeff-Emmett @GriffGreen @tamarandom @jessicazartler

**Comment by cranders1** [comment]
@jessicazartler @GriffGreen or other giveth admin, can i get access to the notion doc? won't let me in currently.
cranders1@gmail.com

**Comment by Jeff-Emmett** [comment]
Sent you full access to the Giveth/Commons Stack Notion Craig! 👌

**Comment by jessicazartler** [comment]
@cranders1 we are having a co-working hack session in Commons Stack Discord @4pm EST today if you would like to join :D

**Comment by jessicazartler** [comment]
Gitcoin Tweets/Threads (created for this round and future templating - adding to Notion ecosystem gitcoin section)
https://docs.google.com/document/d/16kysuMw_rNwQ34HxOM5FNsDE6EM8Z7MHTY5TU7lEtUI/edit

**Comment by tamarandom** [comment]
This was such an excellent thread @jessicazartler !!

**Comment by jessicazartler** [comment]
Thank you @tamarandom !!! <3 Sorry I didn't get a chance to break everything out in issues.. hoping people will do their own - we had to crunch fast.. appreciate the love! <3

**Comment by jessicazartler** [comment]
The only thing left for this is to put final PAN count in Newlsetter and dish CSTK for donations - anything else?
@krisjpi @GriffGreen Thanks guys! Nice work :D

**Comment by tamarandom** [comment]
@jessicazartler @GriffGreen @krisjpi : Looks like this can be closed now, right?

**Comment by jessicazartler** [comment]
Actually, @GriffGreen @krisjpi we never announced the final PAN results... are those out? We could include it in our next newsletter as a small mention. Otherwise, it is all wrapped - just want to keep this as a template for the next round (I added the recurring by monthly label). Thanks @tamarandom !

**Comment by cranders1** [comment]
TEC done

**Comment by jessicazartler** [comment]
Heya @krisjpi @phacker3 can we update this blog to do a push for submit & vote by tomorrow? 
https://medium.com/commonsstack/commons-stack-community-fund-round-2-3919b522409a

Can discuss in Comms meeting but also would be great to sync on Comms for Gitcoin later today - I will message in Comms channel

**Comment by tamarandom** [comment]
@phacker3 does it make sense to pull the process captured in this issues into a separate document so that we can close this. We can open a new issues for the next round with a link to the process doc. What do  you think?

**Comment by phacker3** [comment]
Aw but we were really trying to beat the record for longest unclosed issue! ... 😄 Yes, we can definitely do that! Should it be g:docs? any particular folder? happy to take it from there :)

**Comment by phacker3** [comment]
@tamarandom oops, not sure if I have to tag you but ^

**Comment by tamarandom** [comment]
March 2!? I think we can find longer but this was a good run!

@phacker3 gdocs is fine and no specific folder, no. We'll just want to keep track of where the doc lives and you can drop it in this issue when it's ready.

**Comment by cranders1** [comment]
thnx for covering @phacker3. i've done the last several GC rounds. feel free to ask any questions.

**Comment by phacker3** [comment]
Saved this issue here: https://docs.google.com/document/d/1w-tMH-JbWHyeEM0y64mWHM10dQyuqZ30M4Wf2p_16lA/edit?usp=sharing

And the new issue for GCR12 is here -> https://github.com/commons-stack/iteration0/issues/1104

**Comment by tamarandom** [comment]
HI @YineisyM - is this epic useful for you to do the GGR13 or can it be closed now? I suggest that we update the template to be used for each round. Can you take that on?

**Comment by tamarandom** [comment]
@usama9500 and I were looking at this together and put together this template that can be used for all future Rounds. Please do update it so that it reflects the current process (and any improvements you make to the process). 

https://docs.google.com/document/d/1adbs05kkiS4YTsPryTwT5tPc-enJ3s_TejopjbH0EGU/edit?usp=sharing

The template (really a checklist!) is based on the R12 issue here: https://github.com/commons-stack/iteration0/issues/1104

**Comment by YineisyM** [comment]
Thank you for this @tamarandom and @usama9500! It will be applied in [this issue](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/1259) which is the one we are using for round 13
