### ISSUE TITLE
Optimize Trusted Seed signup form 

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#67]
## 🎉   Subtasks

- [x] Optimize intro (refer to cstk, updated explanation on trusted seed)
- [x] Add an opt-in checkbox for newsletters
- [x] change last Q to requesting more info on who they are 
- [x] review & discuss fall-off rate (proposal to move email lower)

## 🤼‍♂️   Reviewer

@lorelei1 @GriffGreen 

## 🔗   Work doc - inspirational links
 https://docs.google.com/document/d/1eGwpwc_vnqSairF4GNvxJ9cEHKRgvfnPGTtdXqWMkTU/edit?usp=sharing

**Comment by krrisis** [comment]
- kris to review text change proposals by @liviade1 & integrate 
- optimize text thank you, see #31 comment

**Comment by krrisis** [comment]
live on http://commonsstack.org/apply
