### ISSUE TITLE
Monitor info@commonsstack.org

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#673]
## 📋   Anything to add?

This is the email where we currently get direct contacts incoming from our website. Is often forgotten but folks reaching out need a reply.

## 🎉   Subtasks

- [x] Monitor per sprint
- [x] Redirected contract work requests on ABCs and similar to Block Science (elsewhere?)
- [x] Channel other requests / contacts per case

## 🤼‍♂️   Reviewer

@

**Comment by YineisyM** [comment]
I think @Ekeneodigwe should be the assignee to this issue? @mafer-cordovas

**Comment by tamarandom** [comment]
@mafer-cordovas - can you show @iviangita how you have been doing this?
