### ISSUE TITLE
Hiring a Project Manager for Giveth

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#69]
## 📋   Anything to add?
We need a full time project manager that will assist Giveth 1 and 2 and figure out what's blocking progress and help us be fast.
## 🎉   Subtasks

- [x] write job description
- [x] have job description review by Giveth teams
- [x] give job description to Frederik and get his help promoting it
- [x] tweet the job description
- [x] Juliet & Griff meet to determine filters
- [x] Juliet finds top 10 candidates and does pre-interview
- [x] Griff interviews top candidates

## 🤼‍♂️   Reviewer

@
