### ISSUE TITLE
Write Job description for Distribution lead 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#692]
## 📋   Anything to add?

Find, hire & train someone to take on the comms distribution.

## 🎉   Subtasks

- [x] Create job description & choose closing date
- [x] Post on Linkedin
- [x] Schedule Tweets
- [ ] Post in our Discord/TE Discord

---- for later -----

- [ ] Review resumes
- [ ] Hold interviews
- [ ] Advice process
- [ ] Hire
- [ ] Train

## 🤼‍♂️   Reviewer

@tamarandom @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1if2TvOgxhnbn2nkSOHLEXCHMjhxnicxEqAv24Rbs3cY/edit#heading=h.f7q51gor33bx

**Comment by jessicazartler** [comment]
@tamarandom you and I can discuss on our sync tomorrow :D

**Comment by jessicazartler** [comment]
Finished! :D Will post/host on our CS linkedin and circulate via Twitter and channels on Monday - thank you again @tamarandom for your support/editing!

[Commons Stack_Content Distribution Manager Job Description.pdf](https://github.com/commons-stack/iteration0/files/6327748/Commons.Stack_Content.Distribution.Manager.Job.Description.pdf)

**Comment by jessicazartler** [comment]
Posted on Linkedin https://www.linkedin.com/feed/update/urn:li:activity:6789990972676812800/

Passed to Ivy for Twitter, and once it Tweets - will post it around in channels - thanks team!!

**Comment by iviangita** [comment]
UPDATE! Worked on the tweets with Jess and have scheduled them as well on Wednesdays and Sundays until May 15th :)

_Version 1:_
📣JOB OPENING: CONTENT DISTRIBUTION & SOCIAL MEDIA MANAGER

Do you have digital content management experience in web3? Are you passionate about changing the world? 

Join us & explore endless opportunities to grow & make an impact🌱

To learn more & apply: https://www.linkedin.com/posts/the-commons-stack_commons-stack-job-opening-content-distribution-activity-6789990972676812800-IM_v 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/1576b900-f4d3-420b-98b0-7fb0267ef2ae)


_Version 2:_
🌱 WE’RE HIRING! 

The Commons Stack is looking for an experienced marketing professional for a Content Distribution and Social Media Manager role to support our mission.

To learn more & apply, check out this job description: https://www.linkedin.com/posts/the-commons-stack_commons-stack-job-opening-content-distribution-activity-6789990972676812800-IM_v 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/56499bba-17f7-4205-8318-07cdb842b738)

**Comment by jessicazartler** [comment]
Awesome!! Thank you @iviangita :D

**Comment by iviangita** [comment]
Closing! Tam created separate issues for the remaining tasks under [Epic 778](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/778)
