### ISSUE TITLE
Schedule, promote & run CS AMA

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#697]
## 📋   Anything to add?

April 28 - 8am PST / 11am EST / 5pm CET 

## 🎉   Subtasks

- [x] Add to CS public calendar with all of the necessary links
- [x] Make graphic (Ivy)
- [x] Schedule Tweets (Ivy)
- [x] promote in channels (Jess)
- [x] Join / Record (Kris J)
- [x] Distribute recording ((Ivy & Jess)

## 🤼‍♂️   Reviewer

@knobsdao @krisjpi

**Comment by jessicazartler** [comment]
Do we want open or a theme? Could make sense this round to have a focus of "Activate the Trusted Seed" and 45min on that and 15 for other questions.. @tamarandom @knobsdao @GriffGreen will discuss on the sprint call today

**Comment by jessicazartler** [comment]
![Graphics (2)](https://user-images.githubusercontent.com/43972522/112374316-5140bb80-8cb8-11eb-9d00-e2641b325d19.jpg)

**Comment by jessicazartler** [comment]
@krisjpi @iviangita can you Tweet//distribute the recording?

- [ ] Write/schedule tweet
- [ ] Distribute Tweet in CS discord/telegram
- [ ] @knobsdao please file all CS AMA recordings in TS notion (check box for this one :D )

Thanks guys!

**Comment by iviangita** [comment]
@jessicazartler I scheduled it this Wednesday :)

**Comment by jessicazartler** [comment]
You rock @iviangita !!!! Thank you!

**Comment by jessicazartler** [comment]
Shall we use this again for April I suppose @tamarandom ?

**Comment by GriffGreen** [comment]
TIME BOOKED! https://calendar.google.com/event?action=TEMPLATE&tmeid=NG5zZ2l1c2ZjZG83bmNnOTg5N2gxN3RuMXIgY192amRja2ZqNGJoYXJ1b3ZoZDRybW8zZHR2NEBn&tmsrc=c_vjdckfj4bharuovhd4rmo3dtv4%40group.calendar.google.com

**Comment by tamarandom** [comment]
@jessicazartler Yes, definitely! We can keep this a monthly repeat.

**Comment by jessicazartler** [comment]
Thank you :D and thank you @iviangita !!!

**Comment by jessicazartler** [comment]
Promoted in our Telegram -- set alarm to promote 1hr before as well

**Comment by jessicazartler** [comment]
No one showed up - so no need for distribution... closing for April round.. will send out in newsletter next month to see if this makes a difference.. otherwise all good :D thanks everyone!

**Comment by iviangita** [comment]
Hi @jessicazartler do we already have a new date for the next AMA? :)

**Comment by jessicazartler** [comment]
Thank you Ivy for the reminder - will talk to the team about it today and circle back - thanks! :D

**Comment by jessicazartler** [comment]
WEDNESDAY May 26 @ 11am - KrisJ Hosts
Theme: AMA The First Commons Hatch - The TEC 
Let's send email announcement Monday May 24 w/ calendar invite @krisjpi 
@iviangita if you can prepare the calendar/Tweets

**Comment by jessicazartler** [comment]
@iviangita @krisjpi Next AMA scheduled for WEDNESDAY, July 28 will be focused on Regen Network & CS as the first community staking DAO 

Here is the doc we are working from - will talk more in Comms tomorrow about it and drop more comments here as needed - thanks!

https://docs.google.com/document/d/13OWwovgSI8KI4onapRwd16QFBq_YcOcHhBGmMAoYKhs/edit

**Comment by iviangita** [comment]
Added to the calendar: https://calendar.google.com/event?action=TEMPLATE&tmeid=NWFzNm9nNWY3cTg4aXVkZzJ2ajBhcW9kdjcgY192amRja2ZqNGJoYXJ1b3ZoZDRybW8zZHR2NEBn&tmsrc=c_vjdckfj4bharuovhd4rmo3dtv4%40group.calendar.google.com

**Comment by jessicazartler** [comment]
Sorry @iviangita we will be changing the time so @GriffGreen can attend - Griff and @krisjpi can you confirm Thursday, July 29 at 11am EST or? So Ivy can update that? Also, would be good to put a line or two description if you have a sec Kris.. thanks guys!

**Comment by GriffGreen** [comment]
REGEN AMA!! :-D

**Comment by tamarandom** [comment]
Update: 
Goal is two tweets, 24h and 1hr before. 
Theme: collaborative economics
- @Ekeneodigwe will draft and share with @iviangita.

(Griff) Need to invite: Mitch & Vitor, Marko

**Comment by Ekeneodigwe** [comment]
**Twitter** 

- AMA Tweet  https://twitter.com/commonsstack/status/1453026582155563016?s=20

- 1hour reminder of AMA https://twitter.com/commonsstack/status/1453360840569094144?s=20 

- The Distribution https://twitter.com/commonsstack/status/1455195998863732743?s=20

**LinkedIn**

- AMA October Post https://www.linkedin.com/feed/update/urn:li:activity:6858767511530287104 

- The AMA Distribution Post https://www.linkedin.com/feed/update/urn:li:activity:6860961547158609920

**Comment by tamarandom** [comment]
Reopened this one for ya, @Ekeneodigwe, for the Nov just talked on Comms call.

**Comment by Ekeneodigwe** [comment]
- Ekene will draft the announcement 1 week before, 24 hours earlier and 1 hour to the AMA. 

-

**Comment by Ekeneodigwe** [comment]
- Ekene will make a draft to go out on Wednesday 24th November, 2021
- Ivy will make the graphics to go with the post 
- Ekene distributes the announcement thus 1 week ahead, 24 hour before and 1 hour reminder post

**Comment by Ekeneodigwe** [comment]
The first tweet announcing the AMA went out today - - https://twitter.com/commonsstack/status/1463878763435995145?t=N8UlpB_Ip0m_75UY8HJbfQ&s=19

LinkedIn - 
https://www.linkedin.com/feed/update/urn:li:activity:6869709220086853632

**Comment by Ekeneodigwe** [comment]
The AMA was a huge success, The community hall was filled and it was so interactive. 
Really proud of the turn out. 

Next will be the distribution

**Comment by tamarandom** [comment]
Need date and theme. Talking about skipping the Dec AMA (with so few ppl around) and doing first or second week of Jan.

**Comment by Ekeneodigwe** [comment]
Thinking It is time, we start brainstorming on what the theme and time for the Jan AMA would be

**Comment by Ekeneodigwe** [comment]
- Ekene will make a draft to go out on Wednesday 5th January, 2021
- Ivy will make the graphics to go with the post
- Ekene distributes the announcement 24 hour before and 1 hour reminder post

---- Griff will reach out to Sam, Mitch & Lauren. Theme is Giveth & Commons Stack
AMA is on Friday Jan 7, 5pm CET

**Comment by GriffGreen** [comment]
I got Confirmation from the whole Giveth Team, we will be all together for the call in one room ;-D It will have Ashley too: https://twitter.com/WhyldW

**Comment by Ekeneodigwe** [comment]
The First Announcement of January AMA has been made 

- https://twitter.com/commonsstack/status/1478698906582138880?s=20

- https://www.linkedin.com/feed/update/urn:li:activity:6884828685652779008

Tam has also confirmed that she will be available to moderate the session

**Comment by Ekeneodigwe** [comment]
The Distribution was on 

- 

Twitter https://twitter.com/commonsstack/status/1480531683980062726?t=K-ai7JmNUREBTsP4evQbHw&s=19


- LInkedIn https://www.linkedin.com/feed/update/urn:li:activity:6886315078367358976

**Comment by Ekeneodigwe** [comment]
February AMA plan is in the planning stage. 
TEC Commons Upgrade has been chosen as the theme and 11th February is the day, 5/6 PM CET

[ AMA TEC Commons Upgrade](https://docs.google.com/document/d/1qN6L3WAfS_oNDSVSwm3x72_I6pEDspJenZUMmVk7Vvc/edit)

**Comment by Ekeneodigwe** [comment]
This task has achieved its goal for this month, The distributed content can be found here https://twitter.com/commonsstack/status/1492392965712527367?t=GdQMCt8jXlAUh3RCj_8Urg&s=19

**Comment by tamarandom** [comment]
Update: will have AMA's for special topics as needed.
