### ISSUE TITLE
TE Commons Roadmap

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#7]
## 🎉   Subtasks
- [x] Livia and Lorelei make proposal 
- [x] Griff Review
- [x] Meeting on Monday
- [x] Share with TEC chat, and ask for async feedback from Angela and Z
- [x] Make doodle for vision call

## 🤼‍♂️   Reviewer
@Jeff-Emmett 
## 🔗   Links
https://docs.google.com/document/d/1Ft77V5cqHAiyV04jbHnhR0jND0Mc3d8KTqNwDbUObY8/edit?usp=sharing
