### ISSUE TITLE
MetaFest Promotion - Tweets

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#709]
## 🎉   Subtasks

- [x] Full week schedule thread
- [x] 1hr before Kris/Jess
- [x] New time of Griff day before
- [x] 1hr before Griff/Jeff

## 🤼‍♂️   Reviewer

@GriffGreen @krisjpi @Jeff-Emmett

**Comment by jessicazartler** [comment]
Thank you whoever did the hour before Tweets for Kris/I -- I have scheduled the rest for the week so closing - thank you guys! Especially and big shout out to Nate for making the graphics/drafting :D Nice job team!
