### ISSUE TITLE
Send funds to Sintezis.co

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#711]
## 📋   Anything to add?

We received $1538 in funding from various tokens from Gitcoin Round 8 donors and 405 Dai from quadratic funding's match and 21,222.64 PAN... To avoid the Gas fees and operation requirements with the Giveth DApp, I directly sent your 15% in 2 transactions

#1 (1538+405)*.15 = 291.45 DAI

#2 21222.64*.15 = 3183.396 PAN 

https://etherscan.io/tx/0x8cb0c6c415b391b4e128e8825f189bd9f263031a88b59a7d9da51f3cc3d226ea

the address: 0x66800C149Af1dDD0A2d0ecCb559346288c59e49C

## 🎉   Subtasks

- [x] send their address the PAN with a low gas price
- [x] wait till we get 291 dai in our address
- [x] send their address the DAI with a low gas price
- [ ] make the comment in the milestone

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
We received $1538 in funding from various tokens from Gitcoin Round 8 donors and 405 Dai from quadratic funding's match and 21,222.64 PAN... To avoid the Gas fees and operation requirements with the Giveth DApp, I directly sent your 15% in 2 transactions

#1 (1538+405)*.15 = 291.45 DAI

https://etherscan.io/tx/0xfe8cdd5113a16dcdf6513b6dd282cb444febc4787ddd47e225022d20c8649609

#2 21222.64*.15 = 3183.396 PAN

https://etherscan.io/tx/0x8cb0c6c415b391b4e128e8825f189bd9f263031a88b59a7d9da51f3cc3d226ea

the address: 0x66800C149Af1dDD0A2d0ecCb559346288c59e49C

**Comment by tamarandom** [comment]
Closed.
