### ISSUE TITLE
Host Weekly Contributors Sync Call

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#715]
## 📋   Anything to add?
Scheduled for Thursday's at noon EST over Discord voice channel.

## 🎉   Subtasks

- [x] Make sure a member of the team can be present to host in case @knobsdao can't.
- [ ] Sync with the core team on where contributions of time are needed.
- [ ] Review issues marked "For Contributors"; and make new ones if needed.
- [ ] If a question, idea, etc. can't be answered there, make a note to channel it to the right space and/or follow-up.
- [ ] Continue to fine-tune the process.

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
- [Calendar link](https://calendar.google.com/event?action=TEMPLATE&tmeid=N2ZyOXYycHYzMDhmOGI5b2QxdmdiMmc1bDlfMjAyMTAzMThUMTYwMDAwWiBjX3ZqZGNrZmo0YmhhcnVvdmhkNHJtbzNkdHY0QGc&tmsrc=c_vjdckfj4bharuovhd4rmo3dtv4%40group.calendar.google.com&scp=ALL) just for this call.
- [Calendar link](https://calendar.google.com/calendar/u/0/embed?src=c_vjdckfj4bharuovhd4rmo3dtv4@group.calendar.google.com&ctz=Eastern/Time/New/York) for all calls.

**Comment by liviade1** [comment]
I'm taking the "for contributor" label out of this one so only action items for contributors have the label :)

**Comment by tamarandom** [comment]
Hey @YineisyM I think we should keep this on the CS Sprint Board and not move it to the Trusted Seed Sprint Board as it is part of building community (which includes non-TS members too). What do you think?

**Comment by YineisyM** [comment]
I think is ok having this issue on the CS Sprint Board, thanks @tamarandom!

**Comment by tamarandom** [comment]
Update: 
@YineisyM will cancel this call. Eventually refine once we have a more clear contributor model.
