### ISSUE TITLE
Research calls : Video recording, prepping for Youtube

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#721]
## 📋   Anything to add?

Research team needs support on recording calls and making them look good (title, description) on Youtube. 
@iviangita and Zep are doing this so well for TEC. Going to ask them for help to set this up for us too. 

It's likely to take a whole Sprint to work out the best process. Coordinate first with @Jeff-Emmett  and @jessicazartler on which calendar sessions need to be recorded, finding volunteers, training them and setting up the schedule for recorders. 

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by iviangita** [comment]
@Jeff-Emmett @jessicazartler can you please share with me the sessions that need to be recorded? We can set up a group DM on Discord if it will be easier to coordinate there :)

cc: @Zeptimus

**Comment by GriffGreen** [comment]
@Jeff-Emmett @jessicazartler please explicitly state the calls you need to review

**Comment by GriffGreen** [comment]
- [ ] we need a list of calls (and their dates & Times)
- [ ] we need to create a similar system as TEC
- [ ] We need to find a reliable set of contributors to record them with OBS and post them on youtube, nicely

**Comment by GriffGreen** [comment]
There may be a BOT!!! OMG!!

**Comment by GriffGreen** [comment]
@MerlinEgalite is a hero! Going to record cadCAD calls :-D

**Comment by MerlinEgalite** [comment]
Or a wizard whatever haha

**Comment by tamarandom** [comment]
@jessicazartler @Jeff-Emmett Is there more left to be done for this issue? Are there other calls besides cadCAD that will need recorders planned?

**Comment by jessicazartler** [comment]
Not at this time.. but there could be some emergent ones.. I was thinking we table this process building until we get the new distribution person - so perhaps we could put this on icebox? Or close and do an epic for recording -- and put issues inside for specific collaborations/projects/community calls.. I defer to you :D OB-Github-Kenobi
