### ISSUE TITLE
How can we use the data in our Trusted Seed input form in best way?

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#723]
## 📋   Anything to add?

We have a lot of information about our members, what can we do to use this well? 

## 🎉   Subtasks

- [x] Brainstorm call with Dan 
- [x] Decide areas of interest to add to the typeform
- [ ] Update typeform
- [ ] Create tags on Github to add to the "for contributors" issues 

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by liviade1** [comment]
Having a sync with Dan on Monday to go over details

**Comment by liviade1** [comment]
We are missing a focused data point in the TS typeform. 
So we are gonna add a multiple choice question for the specific areas applicants are interested in contributing. These questions will be available on the CRM and we can easily send engagement opportunities to each area.  

ideas: 
- swag design
- UI design
- UX design 
- Content (writing - editing )
- Content distribution 
- Research 
- Development 

Once we have the areas of interest decided, we can create tags to add to the contributor issues. Once a week, Dan or I can match the issues we have open with the people that responded to a specific area of interest. 

@jessicazartler @Jeff-Emmett @krisjpi thoughts?

**Comment by knobsdao** [comment]
Legacy TEC contribution tags: ![Screen Shot 2021-04-13 at 2.56.17 PM.png](https://images.zenhubusercontent.com/5f9b35816d32216fe3d07c7e/d1596b82-7ec7-4348-9e42-d4f54682cbce)

**Comment by jessicazartler** [comment]
Maybe one more - fundraising
Not just swag design but maybe graphic design / animation

**Comment by liviade1** [comment]
Thanks @jessicazartler! 
@knobsdao I updated the initial comment with the suggestions. If you think is good we can add to the typeform

**Comment by knobsdao** [comment]
I'm happy with the categories, they are on point and practical. Want me to go ahead and do the Typeform update @liviade1? Glad to.
