### ISSUE TITLE
Host Weekly Trusted Seed Lounge Call

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#724]
## 📋   Anything to add?
Scheduled for Tuesday's at noon EST over Discord voice channel.

## 🎉   Subtasks

- [x] Make sure a member of the team can be present to host in case @knobsdao can't.
- [ ] Sync with the core team on any questions raised by the community on the Trusted Seed.
- [ ] Invite recent successful applicants to join.
- [ ] If a question, idea, etc. can't be answered there, make a note to channel it to the right space and/or follow-up.
- [ ] Continue to fine-tune the process.

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
- [Calendar link](https://calendar.google.com/event?action=TEMPLATE&tmeid=MXRkMjhqbGZxdjlqc2p1bmNpYXA5MjJwMDlfMjAyMTAzMjNUMTYwMDAwWiBjX3ZqZGNrZmo0YmhhcnVvdmhkNHJtbzNkdHY0QGc&tmsrc=c_vjdckfj4bharuovhd4rmo3dtv4%40group.calendar.google.com&scp=ALL) just for this call.
- [Calendar link](https://calendar.google.com/calendar/u/0/embed?src=c_vjdckfj4bharuovhd4rmo3dtv4@group.calendar.google.com&ctz=Eastern/Time/New/York) for all calls.

**Comment by tamarandom** [comment]
Moved to Trusted Seed Sprint Board
https://app.zenhub.com/workspace/o/trusted-seed/coordination/issues/53
