### ISSUE TITLE
Calendar, graphic & promote cadCAD Community Call April 7

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#725]
## 🎉   Subtasks

- [x] Update calendar invites
- [x] Create graphic
- [x] Sync with presenters
- [x] Schedule Tweets one week before/one day before/1hr before
- [x] post Tweet in channels
- [x] Find person to record

## 🤼‍♂️   Reviewer

@Jeff-Emmett @tamarandom 

## 🔗   Work doc - inspirational links
Calendar Link
https://calendar.google.com/event?action=TEMPLATE&tmeid=MTlxbmdhYXIwbnI4ZzV1dWtxc3JwNDVkY3FfMjAyMTA0MDdUMTgwMDAwWiBjYWRjYWQub3JnQG0&tmsrc=cadcad.org%40gmail.com&scp=ALL

Graphic
https://docs.google.com/presentation/d/1zcisOx79Ia5bCwzxQALYR29J4DN-_0ndIBJHo0yE5Dg/edit#slide=id.ga4e5186a1b_0_0

**Comment by jessicazartler** [comment]
![Graphics (3)](https://user-images.githubusercontent.com/43972522/112374340-5a318d00-8cb8-11eb-8612-4240aa0b31d1.jpg)

**Comment by Jeff-Emmett** [comment]
Can we put the date next to the time?

Also, I'm not sure Balancer will be presenting, but TEA is presenting ON
Balancer might be more accurate?

**Comment by jessicazartler** [comment]
Yes can move that - that is what Angela said is the preferred title

**Comment by jessicazartler** [comment]
Actually, I will leave this open - I forgot I left it open to promote on telegram/Discord channels when the Tweet posts
