### ISSUE TITLE
Train a new payroll person to approve Scholarships 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#728]
## 🎉   Subtasks

- [x] Have a call with the new payroll person and do it together.
- [ ] Do a second call to confirm she has it
- [ ] Make it a repeating task twice a week

## 🤼‍♂️   Reviewer

@
