### ISSUE TITLE
Activate the Trusted Seed Tweet Scheduling

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#729]
## 🎉   Subtasks

- [ ] Make Tweet Thread for Swiss membership dapp

Post Tweet thread link w/ tailored message in:
- [ ] CS Discord or Telegram
- [ ] TEC general discord
- [ ] TE general discord

## 🤼‍♂️   Reviewer

@tamarandom @krisjpi @Jeff-Emmett

**Comment by tamarandom** [comment]
Hey @krisjpi Can you drop an update in here!

**Comment by tamarandom** [comment]
Closing ...
