### ISSUE TITLE
Distribute Praise Case Study

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#733]
## 📋   Anything to add?

Host PDF on the CS website with landing page to download + distribution campaign (newsletter/channels)

## 🎉   Subtasks

- [ ] Create landing page w/ PDF download
- [ ] Newsletter
- [ ] Distribute in channels - Discord/Telegram
- [ ] Distribute to academic/research groups/one on one reachouts

## 🤼‍♂️   Reviewer

@jessicazartler @ataberkcasur @liviade1 @GriffGreen @Jeff-Emmett

**Comment by jessicazartler** [comment]
We might consider making it available via email - give email, download gets sent to grow list

**Comment by jessicazartler** [comment]
Oh there is one :D @krisjpi linking too PDF issue https://github.com/commons-stack/iteration0/issues/574#event-4583323877

**Comment by tamarandom** [comment]
Hey @krisjpi - Might you have an ETA for when the Praise PDF will be available on our website? (or is it already!?) 

Could we some something very simple like on commonsstack.org that we can use to share it with other? (It's also going to be linked in the 2021 direction article).

Something like: commonsstack.org/case-study-praise.pdf

**Comment by krisjpi** [comment]
Just finished the mapping/email/publishing! We have it live here: https://commonsstack.hubspotpagebuilder.com/praise-case-study
However, I haven't connected it to the website yet. We can use that link for now, but I will work on setting up a simpler address that we can set to forward there.

Please test the form and email and let me know if there are edits needed or bugs needing to be squashed!

**Comment by tamarandom** [comment]
Tested! (It arrived and one thing to note is that the email sender name is Kris Jones not Commons Stack)

Can having a look at the site + copy be added to the Comms Agenda to look at again, please!

**Comment by Jeff-Emmett** [comment]
Hey Kris, this looks great!  Would be awesome to see a simplified URL when
you have the time to set that up.

Another thought I had was whether we needed so many fields for the
download, just thought it might turn some ppl away vs a simple email field.

Also happy to help streamline copy & fine print on the page if needed -
noted for discussion in the next comms call.  Great stuff!

**Comment by krisjpi** [comment]
Yeah, I had left the email from me as I simply fit the template which asked for a rep from the organization to sign it. Definitely can switch it to all show as coming from the CS generally.

As for the fields, we can definitely eliminate some! Although, none of the fields except for Email are required, so it's possible to only submit the email and still get the PDF. Keeping the other fields will help us compile and combine existing Hubspot contacts and give us much better communication routes if they fill any of the additional fields in, but I would reconsider if there is considerable dropoff from the length of the form.

**Comment by jessicazartler** [comment]
A/B is always great.. One more thought - you could leave a few of the other fields and there's usually an option to show "optional" inside of them or next to.. nice work Kris!!!
