### ISSUE TITLE
Distribute Commons Simulator "Deep Dive" Part 1

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/iteration0#736]
## 📋   Anything to add?
Need to publish on medium, then draft post and share in all channels. Should be personalized to the channel, and could be shared by different people so as not to be too spammy.

## 🎉   Subtasks

- [x]  Publish on Medium 
- [x]  Twitter
- [x]  CS dDev telegram
- [x]  CS Telegram
- [x]  cadCAD telegram
- [ ]  Partner Discord Channels:
     - [x]  RadicalxChange
     - [x]  Giveth
     - [ ] 1hive
     - [x]  Metagame
     - [x] TEC general
- [ ]  CS newlsetter (at end of April, after all 3 pieces are published)

## 🤼‍♂️   Reviewer

@GriffGreen @jessicazartler @marthendalnunes 

## 🔗   Work doc - inspirational links
See: https://github.com/commons-stack/commons-simulator/issues/146
https://docs.google.com/document/d/1WqCwElE56B2zNdT3SSB_j5ExnWgxpSzB43O_RgwTakA/edit
https://medium.com/commonsstack/the-magic-behind-the-commons-simulator-part-1-game-flow-8fa2bed8437b

**Comment by laurenluz** [comment]
Shilled around :D Wasn't sure the appropriate channel in 1hive, so didn't blast it there. Will create a new issue for distribution when Parts 2 and 3 are done
