### ISSUE TITLE
Work Sesh to Improve Discord Onboarding and organization

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#739]
What room should i use to invite people? 

What is the onboarding process now? maybe in our monday or tuesday call we can go thru it

## 🎉   Subtasks

- [x] Reorganization/Cleanup of Categories/Channels
- [x] Setup the initial welcome screen
- [ ] improve the onboarding flow - ensure it is easy enough to get through while maintaining security for members.

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/1XqyGLYBpfZKVhRHuYyZFLYKL1fPJLsI4oq4xmNoCP24/edit?usp=sharing

**Comment by GriffGreen** [comment]
Sched a work sesh with @liviade1 @krisjpi @jessicazartler

**Comment by knobsdao** [comment]
From Discord: Hey, @Kris#8703! Ivy and I were chatting about CSLOVE just now, and she had a great idea to include a claim reminder on the Trusted Seed gated channels as part of the pinned messages plan.

**Comment by tamarandom** [comment]
Wondering whether we can bump this up in priority and pull it into an upcoming Sprint? With @krisjpi leaving... maybe we can talk on our Sprint planning today about who else can take it on?

**Comment by YineisyM** [comment]
Can we have this work sesh this week? Tam, since I don't have as many calls as you do I would prefer if you tell me your availability for having this sesh together and review what I have advanced. @tamarandom @mafer-cordovas

**Comment by tamarandom** [comment]
Hey @mafer-cordovas since you will be working on this with Innov8r, should we close this issue so you can create new ones for the work you are doing?

**Comment by tamarandom** [comment]
Closing this issue. The audit is really nice to come back to when we want to revisit the onboarding. Most likely not before Q1-23.
