### ISSUE TITLE
Distribute CS 2021 Direction Article

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#741]
## 📋   Anything to add?

Host the paper on the CS website and distribute via email campaign with Praise Case Study

## 🎉   Subtasks

- [x]  Publish on Medium
- [x]  Write 2 tweets
- [x] CS Newsletter
- [x] Tweet
- [x] Put in evergreen distribution pipeline here:
https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit?ts=601004ae#gid=1031817319

- [x] Distribute Tweet in channels:
- [x] TEC Discord
- [x] TE Discord
- [x] CS Discord
- [ ] ....

## 🤼‍♂️   Reviewer

@Jeff-Emmett @jessicazartler @tamarandom @krisjpi @GriffGreen 

## 🔗   Work doc - inspirational links
https://medium.com/commonsstack/zen-and-the-art-of-understanding-commons-stack-f5266b300912

**Comment by jessicazartler** [comment]
This is ready to hit publish COMLETELY FINISHED - we pushed Hatch piece instead, so will wait a few days to space out content - thanks! :D

**Comment by jessicazartler** [comment]
Medium link https://medium.com/commonsstack/zen-and-the-art-of-understanding-commons-stack-f5266b300912

**Comment by jessicazartler** [comment]
Ivy will distribute in TG/Discord channels this THURSDAY

**Comment by jessicazartler** [comment]
Done and DONE! Moved to Evergreen pipeline..
Thank you @iviangita for your support!
