### ISSUE TITLE
Junior gardener for the Trusted Seed 🌰👩‍🌾🌱

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/iteration0#753]
## 🎉   Subtasks

- [x]  Scope the profile requirements, tasks, time dedication, etc.
- [x]  Keep a close sync with Griff.
- [x]  Start scouting.
- [x]  Filer candidates
- [x]  Schedule 1-1s
- [x]  Review best candidates
- [x]  Hire a Junior Gardener!

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by knobsdao** [comment]
Junior Gardener job description/post here: https://www.upwork.com/freelance-jobs/apply/Data-Analyst-Community-Support-CRM-Junior-Gardener_~01e523a86d9638a6bc/

**Comment by kosmostasis** [comment]
We hired two awesome profiles and will be guiding them through the ropes in the next few weeks!
