### ISSUE TITLE
cadCAD Model context for Proposal Inverter repos

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#759]
## 📋   Anything to add?
Jeff to work with Shawn YGG & Tannr on putting more context into Proposal Inverter cadCAD repos

## 🎉   Subtasks

- [ ] Meet with YGG & Tannr
- [ ] Enter context into READMEs
- [ ] Determine next steps for this collaboration

## 🤼‍♂️   Reviewer

@mzargham 

## 🔗   Work doc - inspirational links
https://github.com/BlockScience/automated-general-contractor/tree/main/model
https://github.com/BlockScience/revenue-sharing

**Comment by GriffGreen** [comment]
Riding development interest on this

**Comment by GriffGreen** [comment]
Office hours!

**Comment by GriffGreen** [comment]
Needs to be rescheduled cause thursday doesnt work
