### ISSUE TITLE
Announce Regen Network Partnership Proposal

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#766]
## 🎉   Subtasks

- [x] Kris/Jess/Jeff scaffold/draft 
- [x] Jess edit/review/add additional sections & quotes
- [x] Pass to Regen for review
- [x] Jess publish on Medium
- [x] Ekene write Tweet / Ivy schedule AMA https://github.com/commons-stack/iteration0/issues/976
- [x] Kris write newlsetter / Jess edit
- [x] Kris send newsletter

## 🤼‍♂️   Reviewer

@Jeff-Emmett @krisjpi @GriffGreen @tamarandom @knobsdao @liviade1 

## 🔗   Work doc - inspirational links
(Final proposal below)

Partnershi Planning doc
https://docs.google.com/document/d/13OWwovgSI8KI4onapRwd16QFBq_YcOcHhBGmMAoYKhs/edit

Announcement/Blog draft
https://docs.google.com/document/d/11a66nSZX8wttQqY9LURqdsnh-WfTxI8VH_u93yzkaqU/edit

**Comment by GriffGreen** [comment]
Need onboarding, will be a call inviting @krisjpi

**Comment by jessicazartler** [comment]
Call scheduled for this Friday - bringing in @krisjpi to talk about the onboarding/tech involved in the gov token distribution and solidify our agreement - CS team chat needs to look at how we would distribute these tokens

**Comment by tamarandom** [comment]
Woot!

**Comment by jessicazartler** [comment]
Sent the final proposal draft to their team and working to schedule a follow up tech call to get our Kepler wallet set up and a second call with Revathi to look at doing a community AMA with Regen team in the next 4-6 weeks to talk about Community Staking DAOs and start the conversation. Will also be looking to write an announcement of the parntership for July.

**Comment by jessicazartler** [comment]
[Regen Network __ Commons Stack Partnership (1).pdf](https://github.com/commons-stack/iteration0/files/6717808/Regen.Network.__.Commons.Stack.Partnership.1.pdf)

**Comment by jessicazartler** [comment]
Had a call with @krisjpi @knobsdao and Regen team - we are setting up a tech call to go over the token transfer/how governance decision making will work on Regen/Governance decisions over the staking interest from a tech perspective

We will do a joint blog/press release announcement explaining benefits/plans of the partnership to both communities - @krisjpi will lead and create an issue scaffolding/draft with input from Regen team for the July 5-19 CS sprint - to be edited by @Jeff-Emmett and myself and Regen team. The announcement blog/press release will go out one week ahead of our CS Community AMA which will feature this as a topic July 28 @11am EST - Regen will present for 10min on their vision/plans/work, with some opportunity for questions for 10min - then we will chat about CS / Trusted Seed becoming 1st Community Staking DAO on Regen, governance decisions that will need to be made on Regen, and about the interest generating tokens and the TS having governance and the new TS dashboard.

We can chat a bit more as a team before the announcement goes out.

**Comment by jessicazartler** [comment]
@tamarandom making this an epic as there are multiple tasks inside - next one is Kris' partnership announcement draft and the next AMA - plus some meetings

**Comment by jessicazartler** [comment]
Thank you so much @krisjpi for the draft! I will move to review before end of week to pass to Regen for final review

**Comment by jessicazartler** [comment]
Finished the draft! Thank you Kris for your writing/edits - passing to Jeff for edits then will pass to Regen during our meeting with them tomorrow :D where we will finalize token transfer, governance responsibilities and AMA details

**Comment by jessicazartler** [comment]
@krisjpi would you like the honor of closing this baby? :D

**Comment by krisjpi** [comment]
This massive task is complete! We are just preparing for the Regen focused AMA on Wednesday. Very excited to see this all fall into place!
