### ISSUE TITLE
Research roundup with Jeff - September

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#77]
## 🎉   Subtasks

- [x] Gather Links and do call on the 11th
- [x] Fill out the youtube description 
- [x] Post it in the Trusted Seed Channel
- [x] Tweet it! - @krrisis 
- [x] Gather Links and do call on the 25th
- [x] Fill out the youtube description 
- [x] Post it in the Trusted Seed Channel
- [x] Tweet it! - @krrisis 

## 🤼‍♂️   Reviewer

@Jeff-Emmett 

## 🔗   Work doc - inspirational links
Notes doc: https://docs.google.com/document/d/1SQC4BzxG8rclVNhokommQB2o5SEblIZm1NMBgK0RVeg/edit#heading=h.4kx90ruztmrw
