### ISSUE TITLE
Computer-Aided Governance Tweet Thread

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#773]
## 🎉   Subtasks

- [ ] Draft Tweet thread in Chirapp
- [ ] Jeff review w/ Jess
- [ ] Publish on Twitter

## 🤼‍♂️   Reviewer

@Jeff-Emmett @GriffGreen
