### ISSUE TITLE
publish the roadmap on Github for Commons Simulator

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#78]
## 🎉   Subtasks

- [ ] Marko, Griff and Frontend dev agree and approve the specification doc
- [x] Timeline, process and budget is agreed upon
- [ ] Share with the community in the CS Dev Channel

## 🤼‍♂️   Reviewer

@markoprljic

**Comment by Kisgus** [comment]
Current specification doc https://docs.google.com/document/d/1oSUkW5IDRmkrLcNNwp1vfLNIU0yH5JqsmLxpMB-OuJY/edit#heading=h.8ywnezfv7lnx
