### ISSUE TITLE
Audit the Trusted Seed

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#786]
## 📋   Anything to add?

@GriffGreen hopes to help like a lot with this one :-D

## 🎉   Subtasks

- [x] Figure out how to track if they have Activated
- [x] Transparency list (104!!!)
- [x] Look for sybil "attacks" on Transparency list
- [x] Create a burn list
- [x] Talk to Kristofer and Merlin about the Swiss Membership DApp
- [x] Make a spec for the changes to the membership dapp
- [x] Create a tab that tracks the unminted CSTK 
- [x] Burn and add data to track tokens for non-activated TS members
- [x] Review and update the registry amounts (Do sanity check)
- [x] Look for sybil "attacks" on the unminted list
- [ ] Look at a way to thwart impersonations
- [ ] identify requirements for a new spreadsheet (include nice to have data)
- [ ] Onboard the junior gardener or make a job application
- [ ] Create a new spreadsheet

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Make the Transparency list part of the Membership DApp ... Talk to Kristopher

**Comment by tamarandom** [comment]
Update: closing, opened new issue for the thwarting.
