### ISSUE TITLE
Participate w/ Livia on Enspiral Panel May 6

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#791]
## 🎉   Subtasks

- [ ] Send bio & photo to & Anna-Marie
- [ ] Crowdsource talking points / prepare slides or graphics
- [ ] Participate
- [ ] Send recording to Comms for distribution process

## 🤼‍♂️   Reviewer

@liviade1 @krisjpi
