### ISSUE TITLE
Check TS for UX/UI designers / audio wizards

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#796]
## 🎉   Subtasks

- [ ] Check from a database mail campaign perspective
- [ ] Check from a 1-1 perspective
- [x] Provide a list to the team

## 🤼‍♂️   Reviewer

@

**Comment by kosmostasis** [comment]
Made a list of TS successful applicants and activated members with the skillsets of Design, Content Production & UX/UI: https://docs.google.com/spreadsheets/d/1YqvqwEehYKq9X_oAO_LvWYBamUm1o_AgiqYebbhxdt4/edit?usp=sharing
