### ISSUE TITLE
Update Budget for October

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#80]
## 📋   Anything to add?

This is very much a bureaucratic milestone where Griff needs to update a few different spreadsheets and pay people for their monthly milestones.

If you put commonsstack.eth into zapper.fi you can see our current holdings

## 🎉   Subtasks

- [x] Update this month's Donations tab in the Iteration 0 Budget Spreadsheet
- [ ] Update this month's Projections tab in the Iteration 0 Budget Spreadsheet
- [ ] Update this month's Holdings tab in the Iteration 0 Budget Spreadsheet
- [x] Catherd Commons Stack Core team to put in monthly milestones: 
- [x] Livia
- [ ] Gus
- [x] Loie 
- [x] Jeff 
- [ ] Griff 
- [ ] Juliet 
- [ ] Jess
- [ ] Payout Monthly Milestones 

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links
https://docs.google.com/spreadsheets/d/1DdwfoA7u6U2hnfgmJzT5adWExnorutxKSRh_L_-u_5Y/edit#gid=1546169124
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e
