### ISSUE TITLE
Distribute Commons Simulator Deep Dive Part 2

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/iteration0#801]
## 📋   Anything to add?
Need to publish on medium, then draft posts & tweets and share in all channels.

## 🎉   Subtasks

- [x]  Publish on Medium 
- [x] Write 2 Tweets
- [x]  Tweet
- [ ]  CS newsletter
- [x] Put in evergreen distribution pipeline here:
https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit?ts=601004ae#gid=1031817319

Distribute Tweet in channels:
- [x]  CS dDev telegram
- [x]  CS Telegram
- [x]  cadCAD telegram
- [x]  Partner Discord Channels:
     - [x]  RadicalxChange
     - [x]  Giveth
     - [x] 1hive
     - [x]  Metagame
     - [x] TEC general

## 🤼‍♂️   Reviewer

@marthendalnunes @Jeff-Emmett @krisjpi @GriffGreen @tamarandom 

## 🔗   Work doc - inspirational links
See: https://github.com/commons-stack/commons-simulator/issues/146
https://docs.google.com/document/d/1WqCwElE56B2zNdT3SSB_j5ExnWgxpSzB43O_RgwTakA/edit
https://medium.com/@vitormarthendal/93da1b8b3abe

**Comment by laurenluz** [comment]
Draft submitted by @marthendalnunes to the Commons Stack and is ready for publishing.

Tweets and shills drafted here:
https://docs.google.com/document/d/1NaHpNteot2KQrdejODXiGLhLyh5lKeP7_ApHJIQ2Bpw/edit

**Comment by laurenluz** [comment]
This was published on medium today: https://medium.com/commonsstack/the-magic-behind-the-commons-simulator-part-2-initialization-93da1b8b3abe

I can't add it to the evergreen list because I don't have access to that doc

@iviangita - can you schedule the tweets for tomorrow AM EST? I made a 4-part tweet thread here: https://docs.google.com/document/d/1NaHpNteot2KQrdejODXiGLhLyh5lKeP7_ApHJIQ2Bpw/edit

**Comment by iviangita** [comment]
Hey @laurenluz sure I'll post the tweets today and add it to the evergreen content as well :)

**Comment by laurenluz** [comment]
Shared in all the channels, just needs to go on the CS newsletter - closing this :)
