### ISSUE TITLE
Handover TEC's HubSpot

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/iteration0#831]
## 🎉   Subtasks

- [x] Coordinate and hold a work session.
- [x] Overview of what's been done in CS HubSpot, data we have, and next steps.
- [x] Compile TEC subscribers data that we may have and share.
- [ ] Review.

## 🤼‍♂️   Reviewer

@
