### ISSUE TITLE
IASC Panel: Are Blockchain Commons Actually a Commons?

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#838]
## 📋   Anything to add?
Jeff, Zargham, Felix, Primavera, Kelsie, and Seth Frey are hosting a panel at the International Association of the Study of the Commons on June 9.

Unfortunately it's a $50 attendance fee for non IASC members, and primarily aimed at academics, but we can probably do a small push to our community to get it out there that it's happening!

## 🎉   Subtasks

- [ ] Add to CS calendar
- [ ] Push on twitter ASAP
- [ ] Jeff to prepare materials on panel with Seth

## 🤼‍♂️   Reviewer

@jessicazartler

## 🔗   Work doc - inspirational links

Registration call to action:
https://iasc-commons.wildapricot.org/event-4108725

**Comment by jessicazartler** [comment]
Cool @Jeff-Emmett if you can put the times/panel names, etc. here and I will ask for @iviangita 's help to get this going
