### ISSUE TITLE
Improve Contributor Management Back End Tracking

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#839]
## 🎉   Subtasks

- [x] Ivy and Jess kick off meeting June 7
- [x] Ivy to integrate two tracking docs & improve, suggest "onboarding kit" and process
- [x] Ivy advice process with Tam & Griff
- [ ] Ivy & Jess circle back to refine
- [ ] Ivy present process to team

## 🤼‍♂️   Reviewer

@tamarandom @GriffGreen @Jeff-Emmett @knobsdao @krisjpi @liviade1 @jessicazartler 

## 🔗   Work doc - inspirational links
https://docs.google.com/spreadsheets/d/1DdwfoA7u6U2hnfgmJzT5adWExnorutxKSRh_L_-u_5Y/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1XnNEszQJ1vJNGsOZutyKIy322eWnGMftovXCVAp1ulY/edit#gid=390705803

**Comment by iviangita** [comment]
Tracker in progress: https://docs.google.com/spreadsheets/d/1lv00-eIrVWlhkTKZrMoLey637AXA-T8JXZPio5XHE5o/edit?usp=sharing

**Comment by jessicazartler** [comment]
Awesome @iviangita this is looking great!!! We could probably combine exploring/potential and if you could move special projects underneat the active sheet would be great.. otherwise, nice work! Let me know when you are ready for a follow up on this - we could meet with @tamarandom to discuss these processes and improvements all together - thank you SO MUCH!!!!!

**Comment by jessicazartler** [comment]
@tamarandom @iviangita how are we doing on this? We still need some improvements and maybe we make an ongoing issue or rather epic with more specific tasks underneath - this is my bad, probably this should have been back end processes, still need some work on "front end" and onboarding - I'll change the title of this task and maybe we can close it? Or there is still work that needs to be done?

Or again, make an epic and break down further into issues - Ivy and I did an agreement template from Ekene's so I suppose that needs review, and to see if we want to do anything further with the spreadsheet tracker

**Comment by jessicazartler** [comment]
@tamarandom @iviangita should we close this since we now are pretty good with the work agreements part? Is the team keeping up with the tracking doc? Are there any further improvements needed to this process? I feel there is definitely still a need for a contributor manager/community manager who can be the touchpoint for people reaching out to contribute and identifying tasks/actions those people can take. I feel maybe we close this issue and start another one at least where @krisjpi @knobsdao @Jeff-Emmett and I to discuss the overall CS "funnel" and continuing to work on that.

**Comment by tamarandom** [comment]
Let's leave this open until we have tracking of both paid and unpaid contributors.

**Comment by tamarandom** [comment]
@iviangita added unpaid to the active tab. Closing!
