### ISSUE TITLE
CCA calls regular TODOs - August

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/iteration0#84]
## 📋   Anything to add?

(Make September for 8th and 9th calls (and maybe 10th if it's in September?))
## 🎉   Subtasks

- [x]  Make Video link and description for 7th call on (insert date) - Julio
- [x]  Promote Call on 7th call Via Tweet - Gus
- [x]  Connect with the 7th call attendees Via Telegram - Griff
- [x]  Do the 7th Call - Griff & Julio
- [x]  Add any links to the description - Julio
- [ ]  Tweet the video again with Commons Stack - Kris

## 🤼‍♂️   Reviewer

@Kisgus
