### ISSUE TITLE
Distribute Commons Simulator Deep Dive Part 2 - Final Part!

### ISSUE THREAD

**Issue by laurenluz** [commons-stack/iteration0#846]
## 📋   Anything to add?
Need to publish on medium, then draft posts & tweets and share in all channels.

## 🎉   Subtasks

- [x]  Publish on Medium 
- [x] Write 2 Tweets
- [x]  Tweet
- [x]  CS newsletter
- [ ] Put in evergreen distribution pipeline here:
https://docs.google.com/spreadsheets/d/1QJnratmpodDOuTY-21Lgr6wHr8AK4BOBa-cBI37rHNo/edit?ts=601004ae#gid=1031817319

Distribute Tweet in channels:
- [x]  CS dDev telegram
- [x]  CS Telegram
- [x]  cadCAD telegram
- [x]  Partner Discord Channels:
     - [x]  RadicalxChange
     - [x]  Giveth
     - [x] 1hive
     - [x]  Metagame
     - [x] TEC general

## 🤼‍♂️   Reviewer

@marthendalnunes @Jeff-Emmett @krisjpi @GriffGreen @tamarandom 

## 🔗   Work doc - inspirational links
See: https://github.com/commons-stack/commons-simulator/issues/146
https://docs.google.com/document/d/1WqCwElE56B2zNdT3SSB_j5ExnWgxpSzB43O_RgwTakA/edit

**Comment by laurenluz** [comment]
Tweet thread and shilling post draft: https://docs.google.com/document/d/1n0wH88OlGbVQb-mKR95bMmJV82tPCpYiqPGpmKh6Hzk/edit
