### ISSUE TITLE
Hold Kick off for Gitcoin Grants Round 10 & Onboard New Collaborators

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#857]
## 📋   Anything to add?

Hold kickoff meeting and follow ups to onboard Peter to PM, Ekene to Content Distribution and develop the timeline/strategy for content/distribution/community engagement for the CS Community Fund and Round 10.

## 🎉   Subtasks

- [x] Update Github Epic https://github.com/commons-stack/iteration0/issues/658
- [x] Schedule & host kickoff meeting 
- [x] Onboarding meeting for Peter & Ekene
- [x] Follow ups throughout the round to monitor progress / edit content / coordinate team members

## 🤼‍♂️   Reviewer

@GriffGreen @tamarandom

**Comment by jessicazartler** [comment]
@phacker3 @Ekeneodigwe on board and are doing a FANTASTIC job! Thank you guys and @krisjpi for supporting this onboarding anf the GGR10 push - team work makes the dream work!!! Appreciate you <3
