### ISSUE TITLE
Set up the Giveth DAF

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#87]
## 🎉   Subtasks

- [x] Figure out who wants to be the Donor Advisors (Lorelei, Dani, Willy, Cam?)
- [x] Check in with Unicorn DAC
- [x] Understand if people need to be from the US to be Donor Advisors (They do not)
- [x] Figure out who wants to be back up beneficiaries to the Donor Advisors (2-3)
- [x] Fill out the SDG Impact Fund forms 
- [x] Have the Donor Advisors sign off on the SDG Impact Fund forms
- [x] Turn the forms in Bryan and crew
- [x] Confirm there are no other steps
- [x] Set up accounts 
- [x] Put money (at least 5k) in the accounts
- [x] Set up distributions
- [x] Create a real payment as a Proof of Concept
- [x] Ask our DAF contact to execute the Proof of Concept Payment!!!

## 🤼‍♂️   Reviewer

@lorelei1 via CoachB

## 🔗   Work doc - inspirational links

Previous Issue: https://github.com/commons-stack/iteration0/issues/48
DAF Forms: https://www.sdgimpactfund.org/get-started 
Gdoc with research: https://docs.google.com/document/d/10-esS0tbr5WzA88MeQ6TGBoT1-GQLjOfBU8ikIR9GeM/edit?usp=sharing

**Comment by GriffGreen** [comment]
Dani is leading this effort
