### ISSUE TITLE
GitcoinDAO Anti-Fraud WG wrangling

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#877]
## 📋   Anything to add?
Jess and Jeff are helping to organize and corral the GitcoinDAO Anti-Fraud working group!

## 🎉   Subtasks

- [x] Set up workgroup structure and processes & steward training sessions
- [x] Assign delegates for sub-workstreams
- [ ] Progressively hand off coordination for the workgroup 

## 🤼‍♂️   Reviewer

@jessicazartler

**Comment by jessicazartler** [comment]
@Jeff-Emmett can we call this done?

Created this map from Z's template and sorting paying contributors with the Gitcoin Grant

https://docs.google.com/document/d/1OD1KhBP2csEaPhZr2uZWuMkvrONbSts5EfHnSDAjHs8/edit#
