### ISSUE TITLE
Review Case Study Map 

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#882]
## 🎉   Subtasks

- [ ] Edited Case Study #
- [ ] Meeting with Livia to discuss moving forward and process improvements (July 30)
- [ ] Review Map
- [ ] Suggest scaffolding template

## 🤼‍♂️   Reviewer
@liviade1 @tamarandom @GriffGreen @Jeff-Emmett 

## 🔗   Work doc - inspirational links
https://docs.google.com/spreadsheets/d/1KaLbNATFLcbRNFFF0H64j0tkxw6jvoUK3O8BPy7DLC8/edit#gid=0

**Comment by GriffGreen** [comment]
Case Study on weekly calls is edited!

**Comment by jessicazartler** [comment]
Had a great chat with @liviade1 and will be supporting the process going forward in organizing our resources/advisors to improve the case studies. I will personally be supporting Livia and the process with scaffolding/editing/advice process.

**Comment by tamarandom** [comment]
Closing these old case study issues. New issues can be open once we have the new direction mapped out.
