### ISSUE TITLE
Setup initial onboarding meeting with Justice and Jess

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#904]
## 🎉   Subtasks

- [ ] Initial scoping meeting  (Kris/Jess)
- [ ] Set meeting time with Justice and Jess
- [ ] Infographics and light design (start with CSTK journey and ...?)
- [ ] Additional Projects to support - Newsletter, CRM, Ambassador program, etc
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by krisjpi** [comment]
Had the call, we are working on drafting an agreement to move forward with Justice as a contributor.
