### ISSUE TITLE
Work with Justice on Infographic requests

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/iteration0#905]
## 🎉   Subtasks

- [ ] Coordinate the initial scope with Jess
- [ ] Share info and resources to build into infographics
- [ ] Steps to become a member and see your CSTK (based on Vyvy-vi's gtihub list)
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Has an agreement going :-D

**Comment by GriffGreen** [comment]
in progress... talking about some of the conceptual things... wants to bring in more gamification...

Become a CS Super Hero! Public Goods... watch out!

**Comment by tamarandom** [comment]
Closing.
