### ISSUE TITLE
Migration to gsuite

### ISSUE THREAD

**Issue by krrisis** [commons-stack/iteration0#91]
## 🎉   Subtasks

- [ ] discuss options for pricing 
- [ ] start with commons stack
- [ ] create new addresses on commons stack
- [ ] move giveth

## 🤼‍♂️   Reviewer

@krrisis

**Comment by geleeroyale** [comment]
![image](https://user-images.githubusercontent.com/317685/91768878-9a2b0880-ebde-11ea-885a-8e2b81945c2c.png)

I can click `next` - but please also be aware that no matter what - you will have to invite people to meetings who are not using gsuite. 

I also recommend sharing the following, which works for me at least with any invites I get:

`To save the event to your calendar, make sure you click on the attached .ics file. This will be opened as a new event in your calendar that you can then save.`

**Comment by lorelei1** [comment]
Not happening - too expensive?

**Comment by geleeroyale** [comment]
Yea - this was put on hold for Kris leaving (and before being too expensive)

We had actually settled on putting everything on Zoho Mail, but that would mean adding the domain to Giveth Email putting us in the position to have to upgrade the plan there (we are still on the free one BUHAHAHA) - which would also be kinda expensive.

I am looking at lots of email stuff and [I may have found a good solution we could try](https://www.migadu.com/). It's not gsuite, but it does not such either - the benefits lie in the pudding - we can have as many email addresses across our domains as we want.
