### ISSUE TITLE
Write Job Description for a Fundraiser Role

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#914]
## 📋   Anything to add?

Research other job descriptions for fundraisers and take the best ofs along with input from the Commons Stack team for what tasks/skills are needed for this role and write a description to be reviewed by CS team.

## 🎉   Subtasks

- [ ] Research best fundraiser role job descriptions
- [ ] Collect input from CS team for skills/requirements for the role
- [ ] Draft
- [ ] Collect edits/feedback
- [ ] Discuss next steps with CS team

## 🤼‍♂️   Reviewer

@tamarandom @GriffGreen @jessicazartler @Jeff-Emmett @krisjpi @Ekeneodigwe

**Comment by tamarandom** [comment]
The updated doc here: https://docs.google.com/document/d/1BjAotazmAyue8j8c5WSBW8VAxmjjRO5AimhntQX-dfw/edit

Next step is feedback before it goes out.

**Comment by jessicazartler** [comment]
I requested that we please use this template for the job description @hanners717 :
https://docs.google.com/document/d/1Rtf1lJxq3TjgiKOsuiuIhq6TwAfGsv3M3qal-cH2BP8/edit

And also do a bit of research around language/responsibilities for fundraiser roles - looking at both VCs and non-profits to include in the job description.

The main tasks/responsibilities that should also be included in the description are:
-Developing/iterating on the fundraising/business model strategy & development
-Leading Gitcoin Grants (You can check out this issue for more details around the work: https://github.com/commons-stack/iteration0/issues/658) 
-Grant & proposal writing for grant submission to DAOs & organizations
-Relationship management for private donors / angel donors
-Working with accountant/Program Manager/association board/legal on budgets/entity agreements/compliance

-Ideally the person would have experience in fundraising for non-profits/VC/CFO/accounting experience
-At least basic knowledge of Web3/Crypto

@GriffGreen @tamarandom feel free to weigh in further, or we can schedule a brief call to discuss. I would say this role falls under Operations circle, however a lot of this work I have been doing (Gitcoin/Grant writing) and I would like to hand it off to a role/person, or the person leading fundraising strategy that can hire a part-time support for these roles or tap existing collaborators i.e. Peter who currently support PMing Gitcoin grants / Ruben for DAO proposal.

**Comment by jessicazartler** [comment]
Just checking in @hanners717 any update or do you need any support on this? Thank you!

**Comment by tamarandom** [comment]
Hey @hanners717 - will you be able to slot this into this Sprint? We are ready to move forward with it again.

**Comment by tamarandom** [comment]
Closing, new open open.
