### ISSUE TITLE
Onboard people to CRM

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#92]
## 🎉   Subtasks

- [x] Research, again! (mainly can mailchimp *be* our CRM)
- [x] Make proposal for the expense, get approval, set up payment plan
- [x] Import contacts - @JulietEA can perhaps help with this set-up

## 🤼‍♂️   Reviewer

@lorelei1 

## 🔗   Work doc - inspirational links
The work doc is called "Contributor Account Management" in our drive

**Comment by lorelei1** [comment]
Juliet is now working on importing various spreadsheet data into Hubspot. We'll continue on free program for perhaps a week, perhaps a month, but know pretty securely that we will outgrow this soon and then move to either a $50/mo plan or $100/mo

**Comment by lorelei1** [comment]
@liviade1 when we move to the new plan we'll be able to create a second "lifecycle" path for volunteers and can start managing/tracking them with CRM!!

**Comment by lorelei1** [comment]
Next month action would be show Livia & add volunteer life cycle

**Comment by Kisgus** [comment]
Closing this and moving to #175
