### ISSUE TITLE
Turn current CSTK holders into Association Members

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#93]
## 🎉   Subtasks

- [ ] They will need to sign (updated) statutes again? (@lorelei1 message Coach B about this)
- [ ] Schedule a board meeting (Coach B, Jeff, Loie must attend: Zargham, Griff, Kris optional)
- [ ] Vote them in during the official motions of board meeting

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by Kisgus** [comment]
Closing due to duplicate with #94
