### ISSUE TITLE
Provide legal protection to CSTK holders

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#94]
## 🎉   Subtasks

- [ ] They will need to sign (updated) statutes again? (@lorelei1 message Coach B about this)
- [ ] Schedule a board meeting (Coach B, Jeff, Loie must attend: Zargham, Griff, Kris optional)
- [ ] Vote them in during the official motions of board meeting

## 🤼‍♂️   Reviewer

@lorelei1

**Comment by lorelei1** [comment]
board meeting can just be a circular resolution

**Comment by lorelei1** [comment]
We've decided providing a budget to cover legal fees for any member who gets into a suit because of Commons Stack-approved actions is the way that we will provide legal protection.
