### ISSUE TITLE
Support TEC Hatch Comms from CS

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#941]
## 🎉   Subtasks

- [x] Suggested strategy https://docs.google.com/document/d/1vQb7DCFqWMmJxK7uRfYEOzyTugbqwTjoJDtLrQqmuoY/edit
- [x] Edit Eduardo's TL;DR post https://forum.tecommons.org/t/how-do-i-participate-in-the-hatch-tl-dr/523
- [x] Edited 2 CS email about TEC hatch
- [x] Edited Ekene's distribution plan

## 🤼‍♂️   Reviewer

@krisjpi @GriffGreen @liviade1 @Jeff-Emmett
