### ISSUE TITLE
Onboard Junior Gardeners into TS & Team Processes

### ISSUE THREAD

**Issue by kosmostasis** [commons-stack/iteration0#944]
## 🎉   Subtasks

- [x] Praise Quantification
- [x] Minting CSTK
- [x] CSTK Score Increase Notification
- [x] Updating the Burn Log
- [x] Trusted Seed Office Hours Call
- [x] Contributors Sync Call
- [x] Weekly Comms Call
- [x] Praising
- [x] Sharing the Review Call
- [x] Trusted Seed Application
- [x] Trusted Seed New Applicant Assessment
- [x] Updating the xDai Registry
- [x] Updating Trusted Seed Membership List
- [x] General HubSpot Machinations
- [x] Dupe Processing
- [x] Community Moderation
- [x] Identifying Trolls/Scammers
- [x] Trusted Seed Scholarship
- [x]  Trusted Seed Dashboard Call
- [x] CSLOVE swag claim 1:1 notifications
- [x] "Wait, what's the TEC?"
- [ ] Octalysis Board
- [x] CS Notion
- [x] Using xDai

## 🤼‍♂️   Reviewer

@

**Comment by kosmostasis** [comment]
Porting the "Octalysis Board into issue #763.
