### ISSUE TITLE
Terms & Conditions final

### ISSUE THREAD

**Issue by lorelei1** [commons-stack/iteration0#95]
## 🎉   Subtasks

- [x] Contact Coach B and lawyers to schedule review
- [x] Revise internally
- [x] Have lawyers review
- [ ] Add final doc as a screen of the CSTK token DApp

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
There is a doc up... Griff knows where to find it

**Comment by lorelei1** [comment]
oops, duplicated
