### ISSUE TITLE
Starting Governance in the Hatch DAO

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/iteration0#950]
## 📋   Anything to add?

4 votes to get going on my side

## 🎉   Subtasks

- [ ] 75% governance rights to deducted people
- [ ] Lost Keys... minting and burning
- [ ] Initial Buy for TEC tokens to be used for something? SourceCred?
- [ ] Covenant
- [ ] What to do with the funds from Gitcoin 

## 🤼‍♂️   Reviewer

@
