### ISSUE TITLE
IXO Airdrop

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#951]
## 📋   Anything to add?

IXO is offering an airdrop of 500 IXO tokens to the Trusted Seed, when they sign up for their Earth State membership (first 12 months free membership - then $500/year) and show proof of TS membership. They must also have a Keplr wallet/address to receive tokens.

We need to get it out around 8/24 or 25 -- DEADLINE TO CLAIM IS AUGUST 31 (or before the DEX launches Sept. 5 - need to check with IXO)

## 🎉   Subtasks

- [x] Draft announcement (Jess) https://docs.google.com/document/d/1ve8pD_zZZhEx3diGBkOiJllbhDKOI8zGPu0mTfTK4yk/edit#
- [x] Draft landing page content (Kris)
https://docs.google.com/document/d/1KxXn5FMKnQOKJHj-LCShANz_H4QSTFJHJpa6tLrbVZA/edit
- [x] Review announcement (Kris / IXO team)
- [x] Review landing page (Jess / IXO team)
- [x] Create email campaign (Kris / Jess)

## 🤼‍♂️   Reviewer

@Jeff-Emmett @GriffGreen @krisjpi @knobsdao @liviade1 @tamarandom @Ekeneodigwe @iviangita 

## 🔗   Work doc - inspirational links
https://earthstate.ixo.world/welcome-regenerate/
https://earthstate.ixo.world/ixo-earth-state-drop/

**Comment by jessicazartler** [comment]
Based on partner feedback, IXO have removed the requirement for partner network invitees to use their credit card for identity verification to receive the Earth State Launch Offer IXO token drop.

Example offer https://earthstate.ixo.world/welcome-regenerate/ 

Need:
Eligibility criteria which are easy to validate (up to you who you would like to make eligible)
Edits on the offer landing page (using the Regen example as the template)
An article which we co-write (with some support from IXO comms team) describing our partnership, accomplishments and intentions for further collaboration, to promote on CS channels, and ixo will publish from their perspective on their Medium
An offer / email campaign to activated TS email list
Validation of who signs up - cross check list IXO gives us to verify - check against your eligible email list (and any other criteria)
Estimated number of participants 

Target dates are:
Wednesday 18th: Confirmation or participation, expected numbers & eligibility criteria
Friday 20th: Draft Landing Page on Earth State
Monday 23rd: Internal testing if the campaign
Wednesday 25th: Publish article about our collaboration
Friday 27th: Final landing page
Tuesday 31: You send the email offer to your networks
Friday 3rd Sept: Offer ends
Monday 6th Sep: Validate list of airdrop claims
Tuesday 7th Sep: Airdrop distributed
TBC Wednesday 8th Sep: Public DEX launch of IXO:ATOM on Cosmos Gravity DEX

**Comment by jessicazartler** [comment]
Announcement draft done and under review 
https://docs.google.com/document/d/1ve8pD_zZZhEx3diGBkOiJllbhDKOI8zGPu0mTfTK4yk/edit#

Landing page content drafted 
https://docs.google.com/document/d/1KxXn5FMKnQOKJHj-LCShANz_H4QSTFJHJpa6tLrbVZA/edit

Landing page is up already and under review by Kris/me/IXO team
Https://earthstate.ixo.world/welcome-trusted-seed/

**Comment by jessicazartler** [comment]
It's out!
https://twitter.com/commonsstack/status/1432457685518192646

Closing this issue - thank you to @krisjpi for all your work on this!!!!
