### ISSUE TITLE
Trusted Seed x TEC Hatch Support

### ISSUE THREAD

**Issue by kosmostasis** [commons-stack/iteration0#956]
## 🎉   Subtasks

- [x] Hatcher Outreach & Tracking Support
- [x] CS Community Support
- [x] Speedy Up TS Processes
- [x] Post-Hatch Audit Support

## 🤼‍♂️   Reviewer

@GriffGreen
