### ISSUE TITLE
Revisiting Orbit

### ISSUE THREAD

**Issue by kosmostasis** [commons-stack/iteration0#957]
## 🎉   Subtasks

- [x] Give access to team members
- [x] Setup an exploratory work sesh with the Juniors
- [x] Expand to the rest of the team
- [ ] Explore doing the same for TEC

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links
https://app.orbit.love/cs

**Comment by kosmostasis** [comment]
Several convos between the comms and TS teams happened. So far the tool seems like a nice-to-have, but it certainly could be used to identify and push forward desired behaviors if we want.
