### ISSUE TITLE
Update a the Property on HubSpot for New Blog Suscribers

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#966]
## 🎉   Subtasks

- [x] Reach @krisjpi to check out if there's anything I need to know first.
- [x] Create HubSpot property.
- [x] Communicate it to the team.

## 🤼‍♂️   Reviewer

@knobsdao
