### ISSUE TITLE
TS Scholarship Spreadsheet

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#967]
## 📋   Anything to add?
The goal for this spreadsheet is to get the total scholarships awarded by month, trace activity, and track membership activations. This spreadsheet will be updated by the Junior Gardeners 👩🏼‍🌾🌱
## 🎉   Subtasks

- [x] Update Data from Giveth 
- [ ] Report monthly results 
- [ ] Track any issues that might come up with Scholarship traces

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by YineisyM** [comment]
@mafer-cordovas I assigned this issue to you because you are reviewing the current scholarships

**Comment by usama9500** [comment]
Moved to Trusted Seed Repo:
https://app.zenhub.com/workspace/o/trusted-seed/coordination/issues/48
