### ISSUE TITLE
CSLove Swag Claims Spreadsheet

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#968]
## 📋   Anything to add?
The purpose is to have an overview of members who haven't claim their Swag items, item trends, and reach out reminders.
## 🎉   Subtasks

- [ ] Update CSLove airdrop data
- [ ] Update claimed items 
- [ ] Keep reminder fields updated with the latest reach out to members

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by usama9500** [comment]
Moving it to Trusted Seed Repo:
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/47
