### ISSUE TITLE
Hubspot Upgrade Research

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#969]
## 📋   Anything to add?
We will be having a call with Hubspot customer service to discuss a possiblepackage adapted to our Comms/TS team needs.
## 🎉   Subtasks

- [x] Call with Hubspot CS
- [x] Discuss results with Comms team
- [ ] Demo meeting pending with HubSpot to take a final decision on this.

## 🤼‍♂️   Reviewer

@krisjpi @iviangita @knobsdao

**Comment by YineisyM** [comment]
Hey team!

Based on last week email about our impressions with HubSpot and upgrading our current plan. Are we going to have the demo meeting with them? If so can you suggest a day and a time? or if you disagree let me know your thoughts about it :).

@knobsdao @krisjpi @iviangita

**Comment by YineisyM** [comment]
I'll close this issue since we are going to first audit our data and make some trials before deciding to upgrade. I wrote back to Carlos from HubSpot that we will contact them in the future if we decide go further on this.
