### ISSUE TITLE
TS successful applicants revision of activations

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#970]
## 🎉   Subtasks

- [x] Gather data from the application sheet and hubspot
- [x] Cross match data
- [x] Review applicants/members email behavior

## 🤼‍♂️   Reviewer

@knobsdao

**Comment by mafer-labs** [comment]
Spreadsheet's data is done, and revised with Dan. We have established an strategy to initiate phase 2, which will be the reach out to the successful applicants to activate their memberships. 
A new issue (#989), has been opened to work on the reach out.
