### ISSUE TITLE
HubSpot Properties Audit

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#973]
## 📋   Anything to add?

By taking the time to look through the ways we are and aren't using HubSpot, we're able to identify areas where we could be better or take more advantage on the software features eg reports, dashboards, or easily export what is needed.

## 🎉   Subtasks

- [x] Create views and edit columns.
- [x] Clear/Define unwanted or unused contact properties
- [x] Clean up contact data where needed e.g. fix data formats
- [x] If needed: properly update status or any valuable information
- [x] Create a Data Dictionary: based on the properties that are valuable to look at in HubSpot (Contacts based).

## 🤼‍♂️   Reviewer

@knobsdao
