### ISSUE TITLE
Promote Regen Network AMA

### ISSUE THREAD

**Issue by iviangita** [commons-stack/iteration0#976]
## 📋   Anything to add?

Announce and promote Regen Network AMA (Sept 15th, 11am EST/5pm (CET)

Calendar invite: https://calendar.google.com/event?action=TEMPLATE&tmeid=Mzljb2ZvMGw3cWNzNHJibm5zaWNmbHA3b2IgY192amRja2ZqNGJoYXJ1b3ZoZDRybW8zZHR2NEBn&tmsrc=c_vjdckfj4bharuovhd4rmo3dtv4%40group.calendar.google.com

## 🎉   Subtasks

- [x] Add to the calendar and send the calendar link to Jess (IVY)
- [x] Write the tweets - 1 week before, 1 day before, 1 hour before (EKENE)
- [x] Schedule tweets on Tweetdeck (IVY)

## 🤼‍♂️   Reviewer

@jessicazartler @Ekeneodigwe @krisjpi

**Comment by Ekeneodigwe** [comment]
1 week AMA announcement draft...

What do you know about Regen Network? 

Are you curious about the Commons Stack new partnership? 

Join our “Ask Me Anything” call next Wednesday! 
Sept 15th, 11 am EST/5 pm (CET)


❓ Reply to this tweet w/ your questions 

📆 Add to your calendar https://calendar.google.com/event?action=TEMPLATE&tmeid=Mzljb2ZvMGw3cWNzNHJibm5zaWNmbHA3b2IgY192amRja2ZqNGJoYXJ1b3ZoZDRybW8zZHR2NEBn&tmsrc=c_vjdckfj4bharuovhd4rmo3dtv4%40group.calendar.google.com 

#CommonsStack #SeptemberAMA

**Comment by jessicazartler** [comment]
Looks great! Maybe also link the partnership announcement once it's published - should have it up by end of day today so maybe we wait for that? .. also maybe tease that the Trusted Seed will be governing a pool of funding or something about regenerative/ecological impact -- here is the announcement draft in case there is anything interesting in there for you @Ekeneodigwe for the content https://docs.google.com/document/d/11a66nSZX8wttQqY9LURqdsnh-WfTxI8VH_u93yzkaqU/edit

**Comment by Ekeneodigwe** [comment]
Amazing, once the announcement is made, I will quote the partnership announcement and tweet the AMA call.

**Comment by Ekeneodigwe** [comment]
> Looks great! Maybe also link the partnership announcement once it's published - should have it up by end of the day today so maybe we wait for that? .. also maybe tease that the Trusted Seed will be governing a pool of funding or something about regenerative/ecological impact -- here is the announcement draft in case anything is interesting in there for you @Ekeneodigwe for the content https://docs.google.com/document/d/11a66nSZX8wttQqY9LURqdsnh-WfTxI8VH_u93yzkaqU/edit

- Let me know what you think: The Trusted Seed members will act as stewards of the c-REGEN tokens by voting to allocate, fund mission-aligned proposals & participate in the governance of the Regen Network. It's an opportunity for other Commons and their associated tools within the Regen Network ecosystem.

**Comment by jessicazartler** [comment]
@Ekeneodigwe Can you do it as a thread with two tweets for this first one --- leave your first part as is with the graphic for the AMA (do we have one yet?) -- and the 2nd tweet you wrote there in that paragraph about stewarding tokens with the link for the partnership blog

**Comment by jessicazartler** [comment]
Then also please schedule a day before and a one hour before the event with the graphic & link to announcement blog

**Comment by Ekeneodigwe** [comment]
> @Ekeneodigwe Can you do it as a thread with two tweets for this first one --- leave your first part as is with the graphic for the AMA (do we have one yet?) -- and the 2nd tweet you wrote there in that paragraph about stewarding tokens with the link for the partnership blog

Yes, I can and the Graphic is also ready to go.

**Comment by jessicazartler** [comment]
One more thing - can you create a Telegram message as well to push the AMA and send it on our Discord general channel today? And send a reminder one day before, and one hour before as well @Ekeneodigwe ? Thank you!

**Comment by Ekeneodigwe** [comment]
The post has been made on Twitter -  https://twitter.com/commonsstack/status/1436281135697383432?s=19

**Comment by iviangita** [comment]
This is DONE! The AMA is uploaded on Youtube and shared on Twitter too. Thanks to @Ekeneodigwe @krisjpi @jessicazartler for their support :)
https://twitter.com/commonsstack/status/1440249115791691781?s=20

**Comment by jessicazartler** [comment]
Thank you @iviangita @Ekeneodigwe @krisjpi you guys are awesome! I really appreciate you <3
