### ISSUE TITLE
Activate & Educate cadCAD Community - October

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#98]
## 📋   Anything to add?
I will be managing & fostering participation in the cadCAD community, facilitating calls, translating models, communicating, educating & bridge building for cadCAD over the coming month.

## 🎉   Subtasks

- [x] Set up & promote Community call
- [x] Facilitate call
- [x] Post processing wrap up & distribution
- [x] Twitter, telegram & forum comms
- [x] Model walkthrough videos & AMAs

## 🤼‍♂️   Reviewer

@mzargham

**Comment by lorelei1** [comment]
Same issue will be made for Oct :)

**Comment by jessicazartler** [comment]
@Jeff-Emmett would you like to close this and make same for November? :D
