### ISSUE TITLE
TS Activation Reminders

### ISSUE THREAD

**Issue by YineisyM** [commons-stack/iteration0#989]
## 📋   Anything to add?

Monthly reach out to applicants that were but haven't activated their memberships yet.

## 🎉   Subtasks

- [ ] Send a mass email for those who opened the acceptance email and still did not activate.
 - [ ] 1:1 for those who never opened the acceptance email.
 - [ ] 1:1 for those who have email issues (eg hard bounced).
 - [ ] **Follow up:** 1:1 for those who after 1 week of the monthly mass email haven't activated.

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
Moved to Trusted Seed Repo.
https://app.zenhub.com/workspaces/trusted-seed-622f1226114e700018cb2c83/issues/trusted-seed/coordination/46
