### ISSUE TITLE
Spec cadCAD & Generalized BC funding for Iteration 1

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/iteration0#99]
## 📋   Anything to add?
I will speak with Z and spec out funding needs / plan for improving cadCAD education & development, as well as the Generalized Bonding Curve working group to determine costs and feature priorities.

## 🎉   Subtasks

- [x] Call with Z to discuss.
- [x] Call with Griff to confirm for iteration 1 roadmap.
- [ ] Convene GBC working group and spec out roadmap and costs.
- [ ] Create Giveth milestone for cadCAD improvements & funding.
- [ ] Create Giveth milestone for GBC funding.

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1BtHNOBU9eTPtq_lctgGmiOwiiKiZOFGf0U_S2qhWepM/edit
https://docs.google.com/document/d/1E4kshoi8gy6vYYHn6Mc7KXwZ4MQLqZicp7HkRjPQBzM/edit?usp=sharing

**Comment by lorelei1** [comment]
working group is October task

**Comment by Jeff-Emmett** [comment]
Can we close this issue out @GriffGreen?  Feels like our fundraising / iteration plan is shifting away from needing to scope out hard costs for these kinds of initiatives?

**Comment by tamarandom** [comment]
Closing
