### ISSUE TITLE
Organize Trusted Seed Gardener 🌱 Notion Dashboard 🌱

### ISSUE THREAD

**Issue by mafer-labs** [commons-stack/iteration0#991]
## 🎉   Subtasks

- [x] Discuss w/ team improvements/suggestions
- [x] Team Dashboard Flow 
- [x] Create a spreadsheet vault 
- [x] Create Process library
- [x] Create Knowledge base

## 🤼‍♂️   Reviewer

@knobsdao
