### ISSUE TITLE
Research, analysis & documentation - Governance Tools in the TEC 

### ISSUE THREAD

**Issue by jessicazartler** [commons-stack/iteration0#993]
## 📋   Anything to add?

Turning this into a Gitbook for faster publishing until the article is more fleshed out:
https://docs.google.com/document/d/1yfAbB7-lKDjXXciGuHUr1vbPsTikhdMAxNFg8g1Ihac/edit#

## 🎉   Subtasks

- [x] Get Gitbook sign in details from Livia
- [x] Schedule / hack session with Livia for structure / advice process
- [x] Input tabs and document all of the tooling
- [ ] Feedback from Livia & Griff
- [ ] Write blog as intro about Poly Gov pointing to Gitbook
- [ ] Promote -> pass to Suga for blog, distribution treatment

## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen @tamarandom 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1yfAbB7-lKDjXXciGuHUr1vbPsTikhdMAxNFg8g1Ihac/edit#

**Comment by jessicazartler** [comment]
Dup'd https://github.com/commons-stack/iteration0/issues/841
Needed a fresh one :D

**Comment by tamarandom** [comment]
Related post of the forum: https://forum.tecommons.org/t/decision-making-guide/609

**Comment by jessicazartler** [comment]
@liviade1 @GriffGreen @tamarandom -- Here is a first iteration Gitbook https://app.gitbook.com/@token-engineering-commons/s/tec-handbook/governance/polycentric-governance-in-the-tec

Chatted with Livia today to get some feedback - lmk if you have any other thoughts for other sections you want to add.. the next step is writing a short Medium article to point to the Gitbook section -- I will do another review tomorrow also on fresh brain

Thank you!!

**Comment by tamarandom** [comment]
To update or change the wording to reflect toolkit or glossary or encyclopedia. https://app.gitbook.com/o/-MRe_DImEWCFDsZ_TQd2/s/-MRe_M_mUIIB11A-MQyZ/c/EiHirP16ZZNt5Jlp1b58/governance/polycentric-governance-in-the-tec

**Comment by tamarandom** [comment]
Update: closing.
